// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_template_allocations.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSharedTemplateAllocations = `-- name: DeleteSharedTemplateAllocations :exec
DELETE FROM agent_template_allocations WHERE user_id IS NULL
`

// Clear the whole global-default set (admin replace-set half).
func (q *Queries) DeleteSharedTemplateAllocations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSharedTemplateAllocations)
	return err
}

const deleteUserTemplateAllocations = `-- name: DeleteUserTemplateAllocations :exec
DELETE FROM agent_template_allocations WHERE user_id = $1
`

// Clear the caller's whole overlay (user replace-set half).
func (q *Queries) DeleteUserTemplateAllocations(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTemplateAllocations, userID)
	return err
}

const insertSharedTemplateAllocation = `-- name: InsertSharedTemplateAllocation :exec
INSERT INTO agent_template_allocations (template_id, user_id, enabled)
VALUES ($1, NULL, true)
ON CONFLICT DO NOTHING
`

// Mark a builtin/global template as a global default. Idempotent.
func (q *Queries) InsertSharedTemplateAllocation(ctx context.Context, templateID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertSharedTemplateAllocation, templateID)
	return err
}

const insertUserTemplateAllocation = `-- name: InsertUserTemplateAllocation :exec
INSERT INTO agent_template_allocations (template_id, user_id, enabled)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertUserTemplateAllocationParams struct {
	TemplateID uuid.UUID   `json:"template_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Enabled    bool        `json:"enabled"`
}

// Set one of the caller's overlay decisions (enabled true = force-on, false =
// force-off). Callers delete-then-insert for replace semantics, so DO NOTHING on
// a duplicate (deduped caller-side anyway).
func (q *Queries) InsertUserTemplateAllocation(ctx context.Context, arg InsertUserTemplateAllocationParams) error {
	_, err := q.db.Exec(ctx, insertUserTemplateAllocation, arg.TemplateID, arg.UserID, arg.Enabled)
	return err
}

const listClaimAgentTemplates = `-- name: ListClaimAgentTemplates :many
SELECT t.id, t.name, t.description, t.model, t.tools, t.prompt_body, t.is_builtin, t.updated_by, t.created_at, t.updated_at, t.scope, t.user_id, t.customized FROM agent_templates t
LEFT JOIN agent_template_allocations uo ON uo.template_id = t.id AND uo.user_id = $1
LEFT JOIN agent_template_allocations g  ON g.template_id = t.id AND g.user_id IS NULL
WHERE (t.scope IN ('builtin', 'global') OR (t.scope = 'user' AND t.user_id = $1))
  AND CASE WHEN uo.template_id IS NOT NULL THEN uo.enabled ELSE COALESCE(g.enabled, false) END
  AND NOT (
    t.scope = 'user'
    AND EXISTS (SELECT 1 FROM agent_templates s WHERE s.scope <> 'user' AND s.name = t.name)
  )
ORDER BY t.name
`

// The templates delivered to a claim for @user_id: visible to the user AND
// resolved as allocated. A user overlay (enabled) wins; absent an overlay, the
// global default (user_id NULL) decides; absent both, the template is not
// delivered. Shared rows are always enabled=true, so COALESCE(g.enabled, false)
// reduces to "a global-default row exists". Replaces the all-templates claim read.
//
// SHARED precedence (audit acceptance criterion): a user template whose name
// exists in the shared (builtin/global) namespace is dropped from the claim
// entirely — the curated shared subagent must never be replaced by a user's
// same-named one (the worker keys subagents by name with no scope tiebreak). With
// this drop, plus the two partial uniques (shared names unique; per-user names
// unique), every delivered name is unique, so the worker never sees a collision.
func (q *Queries) ListClaimAgentTemplates(ctx context.Context, userID pgtype.UUID) ([]AgentTemplate, error) {
	rows, err := q.db.Query(ctx, listClaimAgentTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTemplate{}
	for rows.Next() {
		var i AgentTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Model,
			&i.Tools,
			&i.PromptBody,
			&i.IsBuiltin,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scope,
			&i.UserID,
			&i.Customized,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateAllocationsForViewer = `-- name: ListTemplateAllocationsForViewer :many

SELECT t.id, t.name, t.description, t.scope, t.is_builtin,
       (g.template_id IS NOT NULL)::boolean AS global_default,
       uo.enabled AS my_override
FROM agent_templates t
LEFT JOIN agent_template_allocations g  ON g.template_id = t.id AND g.user_id IS NULL
LEFT JOIN agent_template_allocations uo ON uo.template_id = t.id AND uo.user_id = $1
WHERE $2::boolean
   OR t.scope IN ('builtin', 'global')
   OR (t.scope = 'user' AND t.user_id = $1)
ORDER BY t.scope, t.name
`

type ListTemplateAllocationsForViewerParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	IsAdmin  bool        `json:"is_admin"`
}

type ListTemplateAllocationsForViewerRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	Scope         string      `json:"scope"`
	IsBuiltin     bool        `json:"is_builtin"`
	GlobalDefault bool        `json:"global_default"`
	MyOverride    pgtype.Bool `json:"my_override"`
}

// Agent template allocations (PRD #18 M7) ----------------------------------
// Every template visible to the viewer, with its allocation state: whether a
// global-default (shared) row exists, and the viewer's own overlay value (NULL =
// no overlay). The delivered decision is my_override when present, else
// global_default (see ListClaimAgentTemplates). Same visibility rule as
// ListAgentTemplatesForViewer so a user never sees another user's templates.
func (q *Queries) ListTemplateAllocationsForViewer(ctx context.Context, arg ListTemplateAllocationsForViewerParams) ([]ListTemplateAllocationsForViewerRow, error) {
	rows, err := q.db.Query(ctx, listTemplateAllocationsForViewer, arg.ViewerID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateAllocationsForViewerRow{}
	for rows.Next() {
		var i ListTemplateAllocationsForViewerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.IsBuiltin,
			&i.GlobalDefault,
			&i.MyOverride,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedSharedTemplateAllocationByName = `-- name: SeedSharedTemplateAllocationByName :exec
INSERT INTO agent_template_allocations (template_id, user_id, enabled)
SELECT id, NULL, true FROM agent_templates WHERE name = $1 AND scope <> 'user'
ON CONFLICT DO NOTHING
`

// Auto-seed a builtin's global-default row the first time the reconciler inserts
// that builtin (gated on the insert actually happening, so an admin's later
// removal is never re-added on a subsequent boot). Keyed by name over the shared
// namespace so it targets the builtin/global row, never a user template.
func (q *Queries) SeedSharedTemplateAllocationByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, seedSharedTemplateAllocationByName, name)
	return err
}
