// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: board_prefs.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getBoardPrefs = `-- name: GetBoardPrefs :one

SELECT id, user_id, repo_id, extra_labels, show_all, created_at, updated_at FROM board_prefs WHERE user_id = $1 AND repo_id = $2
`

type GetBoardPrefsParams struct {
	UserID uuid.UUID `json:"user_id"`
	RepoID uuid.UUID `json:"repo_id"`
}

// Board preferences (PRD #196 M3) ------------------------------------------
// The board view preferences for (user, repo). No ownership join: the owner read
// path (repoForRequest) has already authorized the repo. Absent ⇒ no rows ⇒ the
// handler returns the unset defaults ({extra_labels: null, show_all: false}).
func (q *Queries) GetBoardPrefs(ctx context.Context, arg GetBoardPrefsParams) (BoardPref, error) {
	row := q.db.QueryRow(ctx, getBoardPrefs, arg.UserID, arg.RepoID)
	var i BoardPref
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.ExtraLabels,
		&i.ShowAll,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBoardPrefsForOwner = `-- name: UpsertBoardPrefsForOwner :one
INSERT INTO board_prefs (user_id, repo_id, extra_labels, show_all)
SELECT $1, r.id, $2, $3
FROM repos r
JOIN forge_connections c ON c.id = r.connection_id
WHERE r.id = $4 AND c.user_id = $1
ON CONFLICT (user_id, repo_id) DO UPDATE
    SET extra_labels = EXCLUDED.extra_labels,
        show_all     = EXCLUDED.show_all,
        updated_at   = now()
RETURNING id, user_id, repo_id, extra_labels, show_all, created_at, updated_at
`

type UpsertBoardPrefsForOwnerParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ExtraLabels []byte    `json:"extra_labels"`
	ShowAll     bool      `json:"show_all"`
	RepoID      uuid.UUID `json:"repo_id"`
}

// Owner-only write: inserts/updates the row ONLY when repo_id belongs to a
// connection owned by user_id (the SELECT yields a row only then), so a non-owner
// or unknown id writes nothing → no rows → 404 in the handler (defense-in-depth
// mirroring UpsertRepoToolProfileForOwner). extra_labels is nullable jsonb: NULL is
// the "not customized" sentinel, a JSON array is the user's absolute set.
func (q *Queries) UpsertBoardPrefsForOwner(ctx context.Context, arg UpsertBoardPrefsForOwnerParams) (BoardPref, error) {
	row := q.db.QueryRow(ctx, upsertBoardPrefsForOwner,
		arg.UserID,
		arg.ExtraLabels,
		arg.ShowAll,
		arg.RepoID,
	)
	var i BoardPref
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.ExtraLabels,
		&i.ShowAll,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
