// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: code_snapshot_cleanup.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCodeSnapshotCleanup = `-- name: GetCodeSnapshotCleanup :one
SELECT lead.id AS lead_run_id,
       cc.head_commit,
       cc.outcome,
       lead.status AS lead_status,
       COALESCE(lead.worker_id = $1::uuid AND lead.claim_released_at IS NULL, false)::boolean AS owned_by_worker,
       child.id AS checker_run_id,
       child.claim_generation AS checker_claim_generation,
       child.status AS checker_status
FROM runs AS lead
JOIN cross_checks AS cc ON cc.lead_run_id = lead.id AND cc.stage = 'code'
JOIN runs AS child ON child.id = cc.checker_run_id
    AND child.user_id = lead.user_id
    AND child.kind = 'cross_check'
    AND child.target_run_id = lead.id
    AND child.worker_id = $1::uuid
WHERE lead.id = $2::uuid
  AND lead.user_id = $3::uuid
`

type GetCodeSnapshotCleanupParams struct {
	WorkerID  uuid.UUID `json:"worker_id"`
	LeadRunID uuid.UUID `json:"lead_run_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetCodeSnapshotCleanupRow struct {
	LeadRunID              uuid.UUID   `json:"lead_run_id"`
	HeadCommit             pgtype.Text `json:"head_commit"`
	Outcome                pgtype.Text `json:"outcome"`
	LeadStatus             string      `json:"lead_status"`
	OwnedByWorker          bool        `json:"owned_by_worker"`
	CheckerRunID           uuid.UUID   `json:"checker_run_id"`
	CheckerClaimGeneration int64       `json:"checker_claim_generation"`
	CheckerStatus          string      `json:"checker_status"`
}

func (q *Queries) GetCodeSnapshotCleanup(ctx context.Context, arg GetCodeSnapshotCleanupParams) (GetCodeSnapshotCleanupRow, error) {
	row := q.db.QueryRow(ctx, getCodeSnapshotCleanup, arg.WorkerID, arg.LeadRunID, arg.UserID)
	var i GetCodeSnapshotCleanupRow
	err := row.Scan(
		&i.LeadRunID,
		&i.HeadCommit,
		&i.Outcome,
		&i.LeadStatus,
		&i.OwnedByWorker,
		&i.CheckerRunID,
		&i.CheckerClaimGeneration,
		&i.CheckerStatus,
	)
	return i, err
}
