// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential_disabled.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const hasEnabledAnthropicForJudgeAuto = `-- name: HasEnabledAnthropicForJudgeAuto :one
SELECT EXISTS (
    SELECT 1 FROM user_secrets
    WHERE user_id = $1 AND kind = 'anthropic_token' AND disabled_at IS NULL
      AND (is_default OR auto_eligible)
)::boolean AS available
`

// Promoter step (4) for a Judge/self-improve auto lane: an enabled pooled token or an
// enabled default can serve it (the #1140 fallback). Read under the user's secret
// mutation lock, which every enablement and default writer takes.
func (q *Queries) HasEnabledAnthropicForJudgeAuto(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasEnabledAnthropicForJudgeAuto, userID)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const listCredentialDisabledRuns = `-- name: ListCredentialDisabledRuns :many
SELECT id, user_id, status_since FROM runs
WHERE user_id = $1 AND status = 'paused' AND hold_reason = 'credential_disabled'
  AND ($2::timestamptz IS NULL
       OR (status_since, id) > ($2::timestamptz,
                                $3::uuid))
ORDER BY status_since ASC, id ASC
LIMIT $4::int
`

type ListCredentialDisabledRunsParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	AfterStatusSince pgtype.Timestamptz `json:"after_status_since"`
	AfterID          pgtype.UUID        `json:"after_id"`
	PageSize         int32              `json:"page_size"`
}

type ListCredentialDisabledRunsRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	StatusSince pgtype.Timestamptz `json:"status_since"`
}

// The M1 partial index narrows this owner-scoped page to held runs. The caller
// re-evaluates the current credential requirement before promoting each row.
func (q *Queries) ListCredentialDisabledRuns(ctx context.Context, arg ListCredentialDisabledRunsParams) ([]ListCredentialDisabledRunsRow, error) {
	rows, err := q.db.Query(ctx, listCredentialDisabledRuns,
		arg.UserID,
		arg.AfterStatusSince,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialDisabledRunsRow{}
	for rows.Next() {
		var i ListCredentialDisabledRunsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.StatusSince); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialDisabledUsers = `-- name: ListCredentialDisabledUsers :many
SELECT DISTINCT user_id FROM runs
WHERE status = 'paused' AND hold_reason = 'credential_disabled'
  AND ($1::uuid IS NULL OR user_id > $1::uuid)
ORDER BY user_id
LIMIT $2::int
`

type ListCredentialDisabledUsersParams struct {
	AfterUserID pgtype.UUID `json:"after_user_id"`
	PageSize    int32       `json:"page_size"`
}

// Sweep fallback worklist: one keyset page of owners with at least one run held on
// credential_disabled. The partial promoter index serves the DISTINCT scan.
func (q *Queries) ListCredentialDisabledUsers(ctx context.Context, arg ListCredentialDisabledUsersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCredentialDisabledUsers, arg.AfterUserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCredentialDisabledRunForPromotion = `-- name: LockCredentialDisabledRunForPromotion :one
SELECT id, user_id, kind, harness, status, hold_reason, pause_requested_at, pause_mode,
       credential_override_mode, credential_override_secret_id, codex_secret_id, worker_id
FROM runs
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type LockCredentialDisabledRunForPromotionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type LockCredentialDisabledRunForPromotionRow struct {
	ID                         uuid.UUID          `json:"id"`
	UserID                     uuid.UUID          `json:"user_id"`
	Kind                       string             `json:"kind"`
	Harness                    string             `json:"harness"`
	Status                     string             `json:"status"`
	HoldReason                 pgtype.Text        `json:"hold_reason"`
	PauseRequestedAt           pgtype.Timestamptz `json:"pause_requested_at"`
	PauseMode                  pgtype.Text        `json:"pause_mode"`
	CredentialOverrideMode     pgtype.Text        `json:"credential_override_mode"`
	CredentialOverrideSecretID pgtype.UUID        `json:"credential_override_secret_id"`
	CodexSecretID              pgtype.UUID        `json:"codex_secret_id"`
	WorkerID                   pgtype.UUID        `json:"worker_id"`
}

// Promoter step (2): the candidate run row, locked AFTER the user's secret mutation
// advisory lock and BEFORE any requirement source or credential row.
func (q *Queries) LockCredentialDisabledRunForPromotion(ctx context.Context, arg LockCredentialDisabledRunForPromotionParams) (LockCredentialDisabledRunForPromotionRow, error) {
	row := q.db.QueryRow(ctx, lockCredentialDisabledRunForPromotion, arg.ID, arg.UserID)
	var i LockCredentialDisabledRunForPromotionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Harness,
		&i.Status,
		&i.HoldReason,
		&i.PauseRequestedAt,
		&i.PauseMode,
		&i.CredentialOverrideMode,
		&i.CredentialOverrideSecretID,
		&i.CodexSecretID,
		&i.WorkerID,
	)
	return i, err
}

const lockDefaultAnthropicSecretForShare = `-- name: LockDefaultAnthropicSecretForShare :one
SELECT id, (disabled_at IS NULL)::boolean AS enabled
FROM user_secrets
WHERE user_id = $1 AND kind = 'anthropic_token' AND is_default
FOR SHARE
`

type LockDefaultAnthropicSecretForShareRow struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

// Promoter step (4) for a default requirement: the owner's current Anthropic default.
// pgx.ErrNoRows means the slot is empty (D4: every default is enabled, and the last
// disable clears the slot).
func (q *Queries) LockDefaultAnthropicSecretForShare(ctx context.Context, userID uuid.UUID) (LockDefaultAnthropicSecretForShareRow, error) {
	row := q.db.QueryRow(ctx, lockDefaultAnthropicSecretForShare, userID)
	var i LockDefaultAnthropicSecretForShareRow
	err := row.Scan(&i.ID, &i.Enabled)
	return i, err
}

const lockSecretEnablementForShareNowait = `-- name: LockSecretEnablementForShareNowait :one
SELECT (disabled_at IS NOT NULL)::boolean AS disabled
FROM user_secrets
WHERE id = $1 AND user_id = $2
FOR SHARE NOWAIT
`

type LockSecretEnablementForShareNowaitParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// The claim finisher's in-transaction enablement re-check of the credential the payload
// resolved, taken under the exact-claim run lock and after the Codex alias/account locks.
// FOR SHARE blocks a concurrent disable (which locks the row FOR UPDATE under the user's
// secret mutation lock) until the claim decision commits; NOWAIT means the finisher never
// waits on that writer: a held row returns 55P03 and finishRunClaim retries the whole
// transaction. Owner-scoped; a missing row is pgx.ErrNoRows.
func (q *Queries) LockSecretEnablementForShareNowait(ctx context.Context, arg LockSecretEnablementForShareNowaitParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockSecretEnablementForShareNowait, arg.ID, arg.UserID)
	var disabled bool
	err := row.Scan(&disabled)
	return disabled, err
}

const lockSecretForPromotion = `-- name: LockSecretForPromotion :one
SELECT (disabled_at IS NULL)::boolean AS enabled
FROM user_secrets
WHERE id = $1 AND user_id = $2
FOR SHARE
`

type LockSecretForPromotionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Promoter step (4): the exact requirement credential. Owner-scoped.
func (q *Queries) LockSecretForPromotion(ctx context.Context, arg LockSecretForPromotionParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockSecretForPromotion, arg.ID, arg.UserID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const lockUserJudgeBindingForShare = `-- name: LockUserJudgeBindingForShare :one
SELECT judge_anthropic_bind_mode, judge_anthropic_secret_id
FROM users
WHERE id = $1
FOR SHARE
`

type LockUserJudgeBindingForShareRow struct {
	JudgeAnthropicBindMode string      `json:"judge_anthropic_bind_mode"`
	JudgeAnthropicSecretID pgtype.UUID `json:"judge_anthropic_secret_id"`
}

// Promoter step (3b): the owner's Judge binding, the requirement source for judge and
// self_improve runs.
func (q *Queries) LockUserJudgeBindingForShare(ctx context.Context, id uuid.UUID) (LockUserJudgeBindingForShareRow, error) {
	row := q.db.QueryRow(ctx, lockUserJudgeBindingForShare, id)
	var i LockUserJudgeBindingForShareRow
	err := row.Scan(&i.JudgeAnthropicBindMode, &i.JudgeAnthropicSecretID)
	return i, err
}

const lockWorkerBindingForShare = `-- name: LockWorkerBindingForShare :one
SELECT anthropic_bind_mode, anthropic_secret_id,
       (draining_since IS NOT NULL
        OR (last_heartbeat_at IS NOT NULL AND last_heartbeat_at >= $1::timestamptz))::boolean
           AS holds_affinity
FROM workers
WHERE id = $2 AND user_id = $3
FOR SHARE
`

type LockWorkerBindingForShareParams struct {
	HeartbeatCutoff pgtype.Timestamptz `json:"heartbeat_cutoff"`
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
}

type LockWorkerBindingForShareRow struct {
	AnthropicBindMode string      `json:"anthropic_bind_mode"`
	AnthropicSecretID pgtype.UUID `json:"anthropic_secret_id"`
	HoldsAffinity     bool        `json:"holds_affinity"`
}

// Promoter step (3a): the recorded worker's Anthropic binding, the requirement source for an
// ordinary Claude run without a per-run override. Owner-scoped. holds_affinity mirrors
// ClaimRun's affinity pin on a queued run's own worker: the row exists and is draining or
// heartbeat-fresh at @heartbeat_cutoff (now - WORKER_HEARTBEAT_STALE). A worker that does
// not hold affinity will not be the next claimant, so its binding is not the requirement.
func (q *Queries) LockWorkerBindingForShare(ctx context.Context, arg LockWorkerBindingForShareParams) (LockWorkerBindingForShareRow, error) {
	row := q.db.QueryRow(ctx, lockWorkerBindingForShare, arg.HeartbeatCutoff, arg.ID, arg.UserID)
	var i LockWorkerBindingForShareRow
	err := row.Scan(&i.AnthropicBindMode, &i.AnthropicSecretID, &i.HoldsAffinity)
	return i, err
}

const parkCredentialDisabledChatRun = `-- name: ParkCredentialDisabledChatRun :execrows
UPDATE runs SET
    status = 'paused',
    status_since = now(),
    hold_reason = 'credential_disabled',
    health = 'ok', health_reason = NULL, health_since = NULL,
    updated_at = now()
WHERE runs.id = $1 AND runs.worker_id = $2
  AND runs.kind = 'chat'
  AND runs.status = 'claimed'
`

type ParkCredentialDisabledChatRunParams struct {
	ID       uuid.UUID   `json:"id"`
	WorkerID pgtype.UUID `json:"worker_id"`
}

// The chat lane's twin of ParkCredentialDisabledRun (PRD #1732 D2/D14). ClaimChatRun has no
// claim generation, capability or custody hold, so the fence is the claimed chat row this
// worker just claimed. Chat is not bindable: it parks only when the owner's default resolves to
// a disabled row or every Anthropic token is disabled (no default), and the promoter queues it
// again once the slot has an enabled default. worker_id is kept as resume affinity.
func (q *Queries) ParkCredentialDisabledChatRun(ctx context.Context, arg ParkCredentialDisabledChatRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, parkCredentialDisabledChatRun, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const parkCredentialDisabledRun = `-- name: ParkCredentialDisabledRun :execrows
UPDATE runs SET
    status = 'paused',
    status_since = now(),
    hold_reason = 'credential_disabled',
    claim_released_at = now(),
    codex_cap_hash = NULL,
    codex_claim_epoch = codex_claim_epoch + 1,
    health = 'ok', health_reason = NULL, health_since = NULL,
    updated_at = now()
WHERE runs.id = $1 AND runs.worker_id = $2
  AND runs.claim_generation = $3
  AND runs.claim_released_at IS NULL
  AND runs.status = 'claimed'
`

type ParkCredentialDisabledRunParams struct {
	ID              uuid.UUID   `json:"id"`
	WorkerID        pgtype.UUID `json:"worker_id"`
	ClaimGeneration int64       `json:"claim_generation"`
}

// Credential disablement parks an UNDELIVERED claim (status 'claimed', exact worker and
// generation) without consuming any pending owner pause or changing its session, phase,
// custody, or recovery state. A running flight is never parked (D3): its claim finishes.
//
// The payload was never handed to the worker, so there is no flight to fence: the D19
// released-incarnation pair (released_worker_id / released_worker_nonce) is deliberately
// NOT written. Writing it would bar the parking worker's own live incarnation from ever
// reclaiming the run after promotion (a single-worker deployment would strand it queued). worker_id is kept as
// resume affinity, exactly like RequeueClaimAssemblyExact; the claim capability is revoked
// (codex_cap_hash NULL, epoch + 1) and claim_released_at rejects any report at this
// generation until the next ClaimRun clears it.
//
// hold_reason is overwritten whatever it was. The only annotation a 'claimed' row can carry
// is 'completion_blocked' from a completion decision that already resumed the run
// (ResumePausedRun keeps it until SetRunRunning): the owner's decision is already recorded
// (its follow_up input and audit row are durable), so the credential is now the actionable
// reason. hold_captured_head is kept for the later SetRunRunning clear. Guarding on
// hold_reason IS NULL instead would match 0 rows after the custody release, roll the
// finisher back and leak this claim's custody hold on every ClaimGrace requeue.
func (q *Queries) ParkCredentialDisabledRun(ctx context.Context, arg ParkCredentialDisabledRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, parkCredentialDisabledRun, arg.ID, arg.WorkerID, arg.ClaimGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteCredentialDisabledRun = `-- name: PromoteCredentialDisabledRun :one
UPDATE runs SET
    status = 'queued',
    status_since = now(),
    budget_paused_seconds = budget_paused_seconds
        + GREATEST(0, EXTRACT(EPOCH FROM (now() - status_since))::int),
    hold_reason = NULL,
    -- Resume affinity is kept: the undelivered-claim park fences no incarnation. Only a row
    -- that carries a D19 released incarnation drops its worker, as ResumePausedRun does.
    worker_id = CASE WHEN released_worker_id IS NOT NULL THEN NULL ELSE worker_id END,
    codex_cap_hash = NULL,
    codex_claim_epoch = codex_claim_epoch + 1,
    health = 'ok', health_reason = NULL, health_since = NULL,
    updated_at = now()
WHERE id = $1 AND user_id = $2
  AND status = 'paused' AND hold_reason = 'credential_disabled'
  AND pause_requested_at IS NULL
  -- The requirement the promoter evaluated must still be the run's requirement: a
  -- concurrent reassignment or rebind that is not serialized by the caller's locks
  -- makes this match 0 rows instead of promoting on a stale requirement.
  AND credential_override_mode IS NOT DISTINCT FROM $3::text
  AND credential_override_secret_id IS NOT DISTINCT FROM $4::uuid
  AND codex_secret_id IS NOT DISTINCT FROM $5::uuid
  AND worker_id IS NOT DISTINCT FROM $6::uuid
  -- Untimed runs (chat, judge, interactive) have no wall (RequestWallParks' own exclusions),
  -- so the spent-budget guard applies only to a timed run.
  AND (kind IN ('chat', 'judge') OR interactive OR started_at IS NULL OR
       (COALESCE(budget_wall_seconds, $7::int)
          + budget_extension_seconds + budget_finalize_seconds)
       - (GREATEST(0, EXTRACT(EPOCH FROM (status_since - started_at))::int)
          - budget_paused_seconds) > 0)
RETURNING id, user_id, status
`

type PromoteCredentialDisabledRunParams struct {
	ID                       uuid.UUID   `json:"id"`
	UserID                   uuid.UUID   `json:"user_id"`
	ExpectedOverrideMode     pgtype.Text `json:"expected_override_mode"`
	ExpectedOverrideSecretID pgtype.UUID `json:"expected_override_secret_id"`
	ExpectedCodexSecretID    pgtype.UUID `json:"expected_codex_secret_id"`
	ExpectedWorkerID         pgtype.UUID `json:"expected_worker_id"`
	GlobalTimeoutSeconds     int32       `json:"global_timeout_seconds"`
}

type PromoteCredentialDisabledRunRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

// Promotion banks only the parked interval. The active time already spent before
// parking must still fit the frozen budget; the hold interval is excluded.
func (q *Queries) PromoteCredentialDisabledRun(ctx context.Context, arg PromoteCredentialDisabledRunParams) (PromoteCredentialDisabledRunRow, error) {
	row := q.db.QueryRow(ctx, promoteCredentialDisabledRun,
		arg.ID,
		arg.UserID,
		arg.ExpectedOverrideMode,
		arg.ExpectedOverrideSecretID,
		arg.ExpectedCodexSecretID,
		arg.ExpectedWorkerID,
		arg.GlobalTimeoutSeconds,
	)
	var i PromoteCredentialDisabledRunRow
	err := row.Scan(&i.ID, &i.UserID, &i.Status)
	return i, err
}

const reassignCredentialDisabledRun = `-- name: ReassignCredentialDisabledRun :one
UPDATE runs SET
    credential_override_mode = $1,
    credential_override_secret_id = $2,
    status = 'queued',
    status_since = now(),
    budget_paused_seconds = budget_paused_seconds
        + GREATEST(0, EXTRACT(EPOCH FROM (now() - status_since))::int),
    hold_reason = NULL,
    -- Resume affinity is kept: the undelivered-claim park fences no incarnation. Only a row
    -- that carries a D19 released incarnation drops its worker, as ResumePausedRun does.
    worker_id = CASE WHEN released_worker_id IS NOT NULL THEN NULL ELSE worker_id END,
    codex_cap_hash = NULL,
    codex_claim_epoch = codex_claim_epoch + 1,
    health = 'ok', health_reason = NULL, health_since = NULL,
    updated_at = now()
WHERE id = $3 AND user_id = $4
  AND status = 'paused' AND hold_reason = 'credential_disabled'
  AND pause_requested_at IS NULL
  -- Untimed runs (chat, judge, interactive) have no wall (RequestWallParks' own exclusions),
  -- so the spent-budget guard applies only to a timed run.
  AND (kind IN ('chat', 'judge') OR interactive OR started_at IS NULL OR
       (COALESCE(budget_wall_seconds, $5::int)
          + budget_extension_seconds + budget_finalize_seconds)
       - (GREATEST(0, EXTRACT(EPOCH FROM (status_since - started_at))::int)
          - budget_paused_seconds) > 0)
RETURNING id, user_id, status
`

type ReassignCredentialDisabledRunParams struct {
	Mode                 pgtype.Text `json:"mode"`
	SecretID             pgtype.UUID `json:"secret_id"`
	ID                   uuid.UUID   `json:"id"`
	UserID               uuid.UUID   `json:"user_id"`
	GlobalTimeoutSeconds int32       `json:"global_timeout_seconds"`
}

type ReassignCredentialDisabledRunRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

// An owner reassignment of an existing credential hold that can go straight back to the queue
// (no pending pause, budget left): the override and the promotion in one statement. The caller
// holds the user lock and the run row. On a held row this matches 0 rows only for a pending
// pause or a spent budget; the caller then writes the override and settles the hold into that
// pause or budget_exhausted, as the promoter does. The whole reassignment is one transaction,
// so a refusal leaves no override behind.
func (q *Queries) ReassignCredentialDisabledRun(ctx context.Context, arg ReassignCredentialDisabledRunParams) (ReassignCredentialDisabledRunRow, error) {
	row := q.db.QueryRow(ctx, reassignCredentialDisabledRun,
		arg.Mode,
		arg.SecretID,
		arg.ID,
		arg.UserID,
		arg.GlobalTimeoutSeconds,
	)
	var i ReassignCredentialDisabledRunRow
	err := row.Scan(&i.ID, &i.UserID, &i.Status)
	return i, err
}

const settleCredentialDisabledPause = `-- name: SettleCredentialDisabledPause :one
WITH settled_inputs AS (
    UPDATE run_user_inputs u SET consumed_at = COALESCE(u.consumed_at, now()), applied_at = now()
    WHERE u.run_id = $1 AND u.kind = 'pause' AND u.applied_at IS NULL
      AND EXISTS (SELECT 1 FROM runs r WHERE r.id = $1 AND r.user_id = $2
                  AND r.status = 'paused' AND r.hold_reason = 'credential_disabled'
                  AND r.pause_requested_at IS NOT NULL)
)
UPDATE runs SET
    hold_reason = CASE WHEN runs.pause_mode = 'wall' THEN 'budget_exhausted' ELSE NULL END,
    claim_released_at = CASE WHEN runs.pause_mode = 'wall' THEN runs.claim_released_at ELSE NULL END,
    pause_requested_at = NULL,
    pause_mode = NULL,
    pause_after_count = NULL,
    health = 'ok', health_reason = NULL, health_since = NULL,
    updated_at = now()
WHERE runs.id = $1 AND runs.user_id = $2
  AND runs.status = 'paused' AND runs.hold_reason = 'credential_disabled'
  AND runs.pause_requested_at IS NOT NULL
  AND runs.credential_override_mode IS NOT DISTINCT FROM $3::text
  AND runs.credential_override_secret_id IS NOT DISTINCT FROM $4::uuid
  AND runs.codex_secret_id IS NOT DISTINCT FROM $5::uuid
  AND runs.worker_id IS NOT DISTINCT FROM $6::uuid
RETURNING runs.id, runs.status, runs.hold_reason
`

type SettleCredentialDisabledPauseParams struct {
	ID                       uuid.UUID   `json:"id"`
	UserID                   uuid.UUID   `json:"user_id"`
	ExpectedOverrideMode     pgtype.Text `json:"expected_override_mode"`
	ExpectedOverrideSecretID pgtype.UUID `json:"expected_override_secret_id"`
	ExpectedCodexSecretID    pgtype.UUID `json:"expected_codex_secret_id"`
	ExpectedWorkerID         pgtype.UUID `json:"expected_worker_id"`
}

type SettleCredentialDisabledPauseRow struct {
	ID         uuid.UUID   `json:"id"`
	Status     string      `json:"status"`
	HoldReason pgtype.Text `json:"hold_reason"`
}

// A held run that also carries a PENDING pause request converges into that pause once its
// credential requirement is met (PRD #1732 D14: the promoter never bypasses an owner pause).
// A pending request survives the involuntary parks by design (SetRunPaused's comment), so a
// run whose worker died after CreatePauseInput is requeued, reclaimed and parked here still
// carrying it. Promoting it to queued would run it past the pause the owner asked for, and
// leaving it held would strand it: ResumePausedRun refuses this hold and CancelPauseInput
// only matches a running row. So the request is CONSUMED exactly as the park it asked for
// would consume it: an owner 'milestone'/'now' request lands in the ordinary owner pause
// (hold_reason NULL, resumed by the owner through ResumePausedRun); a system 'wall' request
// lands in the budget_exhausted hold the wall park writes (resumed by extend). The status
// stays 'paused', so status_since is kept: the resume that later leaves the pause banks the
// whole parked interval, credential hold included, exactly once. The pause's unapplied
// steering inputs are settled so a resumed flight is never handed a stale pause, and the
// same requirement guards as the promotion apply.
//
// The owner arm clears claim_released_at, so the owner's later ResumePausedRun keeps worker_id
// as resume affinity exactly as it does for an ordinary owner pause (SetRunPaused never sets
// it; D14 keeps the existing affinity rules). ResumePausedRun reads a set claim_released_at as
// a server park and drops the worker. The undelivered claim ParkCredentialDisabledRun fenced
// was never handed to a worker and its capability is already revoked (codex_cap_hash NULL);
// the next ClaimRun bumps claim_generation, and a paused row takes no running report. The wall
// arm keeps it: budget_exhausted keeps the server-park semantics (extend drops the worker).
// The caller serializes this with every requirement writer (user lock, then run row).
func (q *Queries) SettleCredentialDisabledPause(ctx context.Context, arg SettleCredentialDisabledPauseParams) (SettleCredentialDisabledPauseRow, error) {
	row := q.db.QueryRow(ctx, settleCredentialDisabledPause,
		arg.ID,
		arg.UserID,
		arg.ExpectedOverrideMode,
		arg.ExpectedOverrideSecretID,
		arg.ExpectedCodexSecretID,
		arg.ExpectedWorkerID,
	)
	var i SettleCredentialDisabledPauseRow
	err := row.Scan(&i.ID, &i.Status, &i.HoldReason)
	return i, err
}

const settleCredentialDisabledSpentBudget = `-- name: SettleCredentialDisabledSpentBudget :one
UPDATE runs SET
    hold_reason = 'budget_exhausted',
    hold_captured_head = NULL,
    health = 'ok', health_reason = NULL, health_since = NULL,
    updated_at = now()
WHERE id = $1 AND user_id = $2
  AND status = 'paused' AND hold_reason = 'credential_disabled'
  AND pause_requested_at IS NULL
  AND credential_override_mode IS NOT DISTINCT FROM $3::text
  AND credential_override_secret_id IS NOT DISTINCT FROM $4::uuid
  AND codex_secret_id IS NOT DISTINCT FROM $5::uuid
  AND worker_id IS NOT DISTINCT FROM $6::uuid
  AND kind NOT IN ('chat', 'judge') AND NOT interactive AND started_at IS NOT NULL
  AND (COALESCE(budget_wall_seconds, $7::int)
         + budget_extension_seconds + budget_finalize_seconds)
      - (GREATEST(0, EXTRACT(EPOCH FROM (status_since - started_at))::int)
         - budget_paused_seconds) <= 0
RETURNING id, user_id, status
`

type SettleCredentialDisabledSpentBudgetParams struct {
	ID                       uuid.UUID   `json:"id"`
	UserID                   uuid.UUID   `json:"user_id"`
	ExpectedOverrideMode     pgtype.Text `json:"expected_override_mode"`
	ExpectedOverrideSecretID pgtype.UUID `json:"expected_override_secret_id"`
	ExpectedCodexSecretID    pgtype.UUID `json:"expected_codex_secret_id"`
	ExpectedWorkerID         pgtype.UUID `json:"expected_worker_id"`
	GlobalTimeoutSeconds     int32       `json:"global_timeout_seconds"`
}

type SettleCredentialDisabledSpentBudgetRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

// A held TIMED run whose requirement is met but whose active budget is already spent (no
// pending pause: SettleCredentialDisabledPause owns that case) cannot be promoted, since
// PromoteCredentialDisabledRun's budget guard refuses it, and must not stay on
// credential_disabled with nothing left to wait for. It settles into the budget_exhausted hold
// the wall park writes, so the owner's Extend (ExtendAndResumeWallPark) resumes it, the same
// place SettleCredentialDisabledPause's wall arm lands (PRD #1732 D14: the promoter never
// bypasses budget exhaustion). The status stays 'paused' and status_since is kept, so Extend
// measures the active time at the park and banks the whole parked interval. claim_released_at
// is kept (server-park semantics, like the wall arm). A hold_captured_head a resumed
// completion hold left behind is not a wall capture, so it is cleared, as ParkRunsAtWall does.
// The exemptions and the budget expression are exactly PromoteCredentialDisabledRun's, negated,
// so the two never both match. The same requirement guards apply.
func (q *Queries) SettleCredentialDisabledSpentBudget(ctx context.Context, arg SettleCredentialDisabledSpentBudgetParams) (SettleCredentialDisabledSpentBudgetRow, error) {
	row := q.db.QueryRow(ctx, settleCredentialDisabledSpentBudget,
		arg.ID,
		arg.UserID,
		arg.ExpectedOverrideMode,
		arg.ExpectedOverrideSecretID,
		arg.ExpectedCodexSecretID,
		arg.ExpectedWorkerID,
		arg.GlobalTimeoutSeconds,
	)
	var i SettleCredentialDisabledSpentBudgetRow
	err := row.Scan(&i.ID, &i.UserID, &i.Status)
	return i, err
}
