// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dispositions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRecommendationDisposition = `-- name: DeleteRecommendationDisposition :execrows
DELETE FROM recommendation_dispositions
WHERE review_id = $1 AND category = $2 AND target = $3
`

type DeleteRecommendationDispositionParams struct {
	ReviewID uuid.UUID `json:"review_id"`
	Category string    `json:"category"`
	Target   string    `json:"target"`
}

// Undo (Decision 6): delete the coordinate row, returning the recommendation to whatever
// the settled-filed axis says (settled link → "Filed", else "To do"). Idempotent — a
// second delete affects 0 rows. Returns rows affected so the handler can 404 a coordinate
// that carried no disposition.
func (q *Queries) DeleteRecommendationDisposition(ctx context.Context, arg DeleteRecommendationDispositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecommendationDisposition, arg.ReviewID, arg.Category, arg.Target)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDispositionsForReview = `-- name: ListDispositionsForReview :many
SELECT id, review_id, category, target, status, dismiss_reason, rationale_hash, set_by_user_id, set_at, updated_at, set_via FROM recommendation_dispositions
WHERE review_id = $1
ORDER BY set_at ASC, id ASC
`

// Every disposition for a review (M2 per-review DTO). Stable order (set_at, id) so the
// panel's dispByCoord map is built deterministically.
func (q *Queries) ListDispositionsForReview(ctx context.Context, reviewID uuid.UUID) ([]RecommendationDisposition, error) {
	rows, err := q.db.Query(ctx, listDispositionsForReview, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationDisposition{}
	for rows.Next() {
		var i RecommendationDisposition
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.Category,
			&i.Target,
			&i.Status,
			&i.DismissReason,
			&i.RationaleHash,
			&i.SetByUserID,
			&i.SetAt,
			&i.UpdatedAt,
			&i.SetVia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJudgeTriageRowsForUser = `-- name: ListJudgeTriageRowsForUser :many
SELECT
    d.status AS disposition_status,
    d.dismiss_reason AS dismiss_reason,
    (f.filed_at IS NOT NULL)::bool AS filed_settled
FROM run_reviews rv
JOIN review_recommendations rr ON rr.review_id = rv.id
LEFT JOIN recommendation_dispositions d
    ON d.review_id = rv.id AND d.category = rr.category AND d.target = rr.target
LEFT JOIN recommendation_filed_issues f
    ON f.review_id = rv.id AND f.category = rr.category AND f.target = rr.target
WHERE rv.user_id = $1
`

type ListJudgeTriageRowsForUserRow struct {
	DispositionStatus pgtype.Text `json:"disposition_status"`
	DismissReason     pgtype.Text `json:"dismiss_reason"`
	FiledSettled      bool        `json:"filed_settled"`
}

// The GLOBAL flat join feeding the Go bucketer (Decision 8): from the caller's reviews,
// ONE ROW PER RECOMMENDATION carrying its coordinate's disposition status + dismiss_reason
// (both nullable — dismiss_reason feeds the not_an_issue false-positive sub-count) and
// whether it has a SETTLED filed link (filed_at IS NOT NULL — an in-flight/unsettled claim
// is NOT "filed", matching the per-review path). There is deliberately NO SQL CASE and no
// bucketing here: the ladder (dismissed > done > filed > open) is one Go helper consumed by
// both this global handler and the per-review DTO, so the two counters can't drift. Both
// side-table joins are UNIQUE on the coordinate, so neither fans out. The ::bool cast is
// REQUIRED — without it sqlc types the boolean expression column as interface{}.
func (q *Queries) ListJudgeTriageRowsForUser(ctx context.Context, userID uuid.UUID) ([]ListJudgeTriageRowsForUserRow, error) {
	rows, err := q.db.Query(ctx, listJudgeTriageRowsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJudgeTriageRowsForUserRow{}
	for rows.Next() {
		var i ListJudgeTriageRowsForUserRow
		if err := rows.Scan(&i.DispositionStatus, &i.DismissReason, &i.FiledSettled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const systemDismissDeniedCLIRecommendation = `-- name: SystemDismissDeniedCLIRecommendation :execrows
INSERT INTO recommendation_dispositions
    (review_id, category, target, status, dismiss_reason, rationale_hash, set_via, set_by_user_id)
VALUES
    ($1, $2, $3, 'dismissed', 'wont_do', $4, 'denied_cli', NULL)
ON CONFLICT (review_id, category, target) DO NOTHING
`

type SystemDismissDeniedCLIRecommendationParams struct {
	ReviewID      uuid.UUID `json:"review_id"`
	Category      string    `json:"category"`
	Target        string    `json:"target"`
	RationaleHash string    `json:"rationale_hash"`
}

// The deterministic net (issue #167): auto-dismiss a recommendation whose target names a
// denylisted credential-bearing CLI. status/dismiss_reason/set_via/set_by_user_id are
// SERVER-SIDE LITERALS (never from a request body — same principle as the issue_close sync).
// set_via='denied_cli' is the self-measuring provenance. ON CONFLICT DO NOTHING so a human's
// existing verdict on the coordinate is NEVER overwritten. rationale_hash is stamped so the
// stale flag stays honest, matching UpsertRecommendationDisposition.
func (q *Queries) SystemDismissDeniedCLIRecommendation(ctx context.Context, arg SystemDismissDeniedCLIRecommendationParams) (int64, error) {
	result, err := q.db.Exec(ctx, systemDismissDeniedCLIRecommendation,
		arg.ReviewID,
		arg.Category,
		arg.Target,
		arg.RationaleHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRecommendationDisposition = `-- name: UpsertRecommendationDisposition :one

INSERT INTO recommendation_dispositions
    (review_id, category, target, status, dismiss_reason, rationale_hash, set_by_user_id)
VALUES
    ($1, $2, $3, $4, $5, $6,
     $7)
ON CONFLICT (review_id, category, target) DO UPDATE
    SET status         = EXCLUDED.status,
        dismiss_reason = EXCLUDED.dismiss_reason,
        rationale_hash = EXCLUDED.rationale_hash,
        set_by_user_id = EXCLUDED.set_by_user_id,
        -- set_via is CLEARED, not carried over (PRD #98 M6). This path is a HUMAN write,
        -- so the row's provenance becomes "a person set this". Without the reset, a
        -- coordinate previously auto-resolved by the Filed→Done sync would keep
        -- set_via='issue_close' after the user overrode it, and the panel would label
        -- their own verdict "done via #IID" — attributing a human decision to the system,
        -- the exact mirror of what PF-4 prevents.
        --
        -- Written as a literal NULL, NOT as EXCLUDED.set_via. The two are equivalent only
        -- because the INSERT column list above omits set_via; if anyone ever adds it there,
        -- the EXCLUDED form would silently start carrying system provenance through a human
        -- write with NO edit to this line. NULL states the invariant itself — a human write
        -- always means human provenance — instead of depending on a column list elsewhere
        -- in the same statement staying as it is.
        set_via        = NULL,
        set_at         = now(),
        updated_at     = now()
RETURNING id, review_id, category, target, status, dismiss_reason, rationale_hash, set_by_user_id, set_at, updated_at, set_via
`

type UpsertRecommendationDispositionParams struct {
	ReviewID      uuid.UUID   `json:"review_id"`
	Category      string      `json:"category"`
	Target        string      `json:"target"`
	Status        string      `json:"status"`
	DismissReason pgtype.Text `json:"dismiss_reason"`
	RationaleHash string      `json:"rationale_hash"`
	SetByUserID   pgtype.UUID `json:"set_by_user_id"`
}

// Recommendation-disposition queries (PRD #94). The user's triage verdict on a judge
// recommendation — Done, or Dismissed with a reason — keyed on the
// (review_id, category, target) coordinate, mirroring recommendation_filed_issues
// (PRD #68). Setting a disposition is a single local upsert: no token spend, no forge
// write, no claim-first dance (there is no external side effect to make exactly-once,
// so concurrent writes converge on the last value and a delete is idempotent,
// Decision 6). See 00073_recommendation_dispositions.sql for the table rationale.
// Idempotent upsert on the coordinate (Decision 6): set/switch status, set/clear the
// dismiss reason, and RE-STAMP rationale_hash + set_at + updated_at at set-time (Decision 3,
// the hash is what the stale flag compares against). Re-clicking is safe, last-writer-wins.
// set_at is re-stamped on conflict too so the panel's "resolved Xago" reflects the LATEST
// disposition action (a done→dismissed switch or reason change reads as "just now", not the
// first-ever set); the row is a single triage verdict, not an append log.
// dismiss_reason and set_by_user_id are nullable (sqlc.narg) — a 'done' carries no reason
// and a SET-NULL'd setter leaves the row. The status/reason invariant is enforced by the
// table CHECK, not here.
func (q *Queries) UpsertRecommendationDisposition(ctx context.Context, arg UpsertRecommendationDispositionParams) (RecommendationDisposition, error) {
	row := q.db.QueryRow(ctx, upsertRecommendationDisposition,
		arg.ReviewID,
		arg.Category,
		arg.Target,
		arg.Status,
		arg.DismissReason,
		arg.RationaleHash,
		arg.SetByUserID,
	)
	var i RecommendationDisposition
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.Category,
		&i.Target,
		&i.Status,
		&i.DismissReason,
		&i.RationaleHash,
		&i.SetByUserID,
		&i.SetAt,
		&i.UpdatedAt,
		&i.SetVia,
	)
	return i, err
}
