// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guardrail_requests.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decideGuardrailOverrideRequest = `-- name: DecideGuardrailOverrideRequest :one
UPDATE guardrail_override_requests
SET status        = $1,
    decided_by    = $2::uuid,
    decided_at    = now(),
    decision_note = $3
WHERE id = $4 AND status = 'pending'
RETURNING id, repo_id, requested_by, reason, findings, status, created_at, decided_by, decided_at, decision_note
`

type DecideGuardrailOverrideRequestParams struct {
	Status       string      `json:"status"`
	DecidedBy    uuid.UUID   `json:"decided_by"`
	DecisionNote pgtype.Text `json:"decision_note"`
	ID           uuid.UUID   `json:"id"`
}

// Settle a PENDING request as approved or rejected, stamping the deciding admin and
// an optional note. The `AND status = 'pending'` guard is what makes a decision
// single-shot: a second decide on the same id (already decided, or unknown) matches
// no row and returns pgx.ErrNoRows, so the handler cannot double-decide or race two
// admins into conflicting outcomes. decided_at is now(), never from the request body.
// decision_note is optional (sqlc.narg → nullable). This M1 seam only records the
// decision; applying an approval to repos.guardrail_override_* is a later milestone.
func (q *Queries) DecideGuardrailOverrideRequest(ctx context.Context, arg DecideGuardrailOverrideRequestParams) (GuardrailOverrideRequest, error) {
	row := q.db.QueryRow(ctx, decideGuardrailOverrideRequest,
		arg.Status,
		arg.DecidedBy,
		arg.DecisionNote,
		arg.ID,
	)
	var i GuardrailOverrideRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RequestedBy,
		&i.Reason,
		&i.Findings,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
	)
	return i, err
}

const deletePendingGuardrailOverrideRequestsForRepo = `-- name: DeletePendingGuardrailOverrideRequestsForRepo :exec
DELETE FROM guardrail_override_requests WHERE repo_id = $1 AND status = 'pending'
`

// Settle any PENDING request for a repo when the owner successfully enables it (issue
// #1432 rework): the request is moot, so it is removed rather than left to linger in the
// admin queue (which is unfiltered by repos.enabled). A decided (approved/rejected) request
// is untouched — only the open pending row for this repo is deleted.
func (q *Queries) DeletePendingGuardrailOverrideRequestsForRepo(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingGuardrailOverrideRequestsForRepo, repoID)
	return err
}

const getGuardrailOverrideRequest = `-- name: GetGuardrailOverrideRequest :one
SELECT id, repo_id, requested_by, reason, findings, status, created_at, decided_by, decided_at, decision_note FROM guardrail_override_requests WHERE id = $1
`

// One request by id (the decide handler's preflight; an unknown id returns no rows).
func (q *Queries) GetGuardrailOverrideRequest(ctx context.Context, id uuid.UUID) (GuardrailOverrideRequest, error) {
	row := q.db.QueryRow(ctx, getGuardrailOverrideRequest, id)
	var i GuardrailOverrideRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RequestedBy,
		&i.Reason,
		&i.Findings,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
	)
	return i, err
}

const listGuardrailOverrideRequestsForUser = `-- name: ListGuardrailOverrideRequestsForUser :many
SELECT DISTINCT ON (gor.repo_id) gor.id, gor.repo_id, gor.requested_by, gor.reason, gor.findings, gor.status, gor.created_at, gor.decided_by, gor.decided_at, gor.decision_note
FROM guardrail_override_requests gor
JOIN repos r ON r.id = gor.repo_id
JOIN forge_connections c ON c.id = r.connection_id
WHERE c.user_id = $1
ORDER BY gor.repo_id, gor.created_at DESC
`

// The requesting member's own view: the LATEST request per repo they own, scoped
// through the repo's connection to the caller (c.user_id = $1) so it can never leak
// another tenant's request. DISTINCT ON (gor.repo_id) with the matching ORDER BY
// picks the newest request per repo (a repo may have an old decided request plus a
// fresh pending one). The connection join is the tenant boundary — a request whose
// repo belongs to a different user's connection is never returned.
func (q *Queries) ListGuardrailOverrideRequestsForUser(ctx context.Context, userID uuid.UUID) ([]GuardrailOverrideRequest, error) {
	rows, err := q.db.Query(ctx, listGuardrailOverrideRequestsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuardrailOverrideRequest{}
	for rows.Next() {
		var i GuardrailOverrideRequest
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.RequestedBy,
			&i.Reason,
			&i.Findings,
			&i.Status,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGuardrailOverrideRequests = `-- name: ListPendingGuardrailOverrideRequests :many
SELECT gor.id, gor.repo_id, gor.requested_by, gor.reason, gor.findings, gor.status, gor.created_at,
       r.path_with_namespace, u.id AS owner_id, u.email AS owner_email, c.forge_type
FROM guardrail_override_requests gor
JOIN repos r ON r.id = gor.repo_id
JOIN forge_connections c ON c.id = r.connection_id
JOIN users u ON u.id = c.user_id
WHERE gor.status = 'pending'
ORDER BY u.email ASC, r.path_with_namespace ASC
`

type ListPendingGuardrailOverrideRequestsRow struct {
	ID                uuid.UUID          `json:"id"`
	RepoID            uuid.UUID          `json:"repo_id"`
	RequestedBy       uuid.UUID          `json:"requested_by"`
	Reason            string             `json:"reason"`
	Findings          []byte             `json:"findings"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	PathWithNamespace string             `json:"path_with_namespace"`
	OwnerID           uuid.UUID          `json:"owner_id"`
	OwnerEmail        string             `json:"owner_email"`
	ForgeType         string             `json:"forge_type"`
}

// The admin cross-user queue (PRD #1432): every PENDING request across ALL users,
// joined to its repo (path), owning user (id + email), and connection (forge_type)
// so the admin can triage without a per-row fan-out. UNSCOPED — admin-only, gated in
// the handler (precedent AdminListReposWithPrivilege). Ordered by owner email then
// repo path for a stable, human-scannable queue.
func (q *Queries) ListPendingGuardrailOverrideRequests(ctx context.Context) ([]ListPendingGuardrailOverrideRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingGuardrailOverrideRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingGuardrailOverrideRequestsRow{}
	for rows.Next() {
		var i ListPendingGuardrailOverrideRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.RequestedBy,
			&i.Reason,
			&i.Findings,
			&i.Status,
			&i.CreatedAt,
			&i.PathWithNamespace,
			&i.OwnerID,
			&i.OwnerEmail,
			&i.ForgeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuardrailOverrideRequest = `-- name: UpsertGuardrailOverrideRequest :one

INSERT INTO guardrail_override_requests (repo_id, requested_by, reason, findings)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repo_id) WHERE status = 'pending'
DO UPDATE SET reason     = EXCLUDED.reason,
              findings   = EXCLUDED.findings,
              created_at = now()
RETURNING id, repo_id, requested_by, reason, findings, status, created_at, decided_by, decided_at, decision_note
`

type UpsertGuardrailOverrideRequestParams struct {
	RepoID      uuid.UUID `json:"repo_id"`
	RequestedBy uuid.UUID `json:"requested_by"`
	Reason      string    `json:"reason"`
	Findings    []byte    `json:"findings"`
}

// Guardrail override requests (PRD #1432 M1) ------------------------------
// Open or refresh a member's request that an admin allow this repo through the
// #66 guardrail. The ON CONFLICT arbiter is the partial unique index
// guardrail_override_requests_one_pending (repo_id WHERE status = 'pending'), so a
// SECOND request for the same repo while one is still pending UPDATEs that open row
// in place (new reason/findings, created_at bumped to now()) rather than piling up
// a duplicate. A decided request has dropped out of the partial index, so it does
// not conflict and the next refusal opens a fresh pending row. findings is the
// audit/display snapshot only — no gate reads it back.
func (q *Queries) UpsertGuardrailOverrideRequest(ctx context.Context, arg UpsertGuardrailOverrideRequestParams) (GuardrailOverrideRequest, error) {
	row := q.db.QueryRow(ctx, upsertGuardrailOverrideRequest,
		arg.RepoID,
		arg.RequestedBy,
		arg.Reason,
		arg.Findings,
	)
	var i GuardrailOverrideRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RequestedBy,
		&i.Reason,
		&i.Findings,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
	)
	return i, err
}
