// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentMemory struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	RepoID    uuid.UUID          `json:"repo_id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Basis     pgtype.Text        `json:"basis"`
	Evidence  pgtype.Text        `json:"evidence"`
}

type AgentSkillAllocation struct {
	TemplateID uuid.UUID          `json:"template_id"`
	SkillID    uuid.UUID          `json:"skill_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AgentTemplate struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Model       pgtype.Text        `json:"model"`
	Tools       []byte             `json:"tools"`
	PromptBody  string             `json:"prompt_body"`
	IsBuiltin   bool               `json:"is_builtin"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Scope       string             `json:"scope"`
	UserID      pgtype.UUID        `json:"user_id"`
	Customized  bool               `json:"customized"`
}

type AgentTemplateAllocation struct {
	TemplateID uuid.UUID          `json:"template_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AnthropicRateLimit struct {
	UserSecretID     uuid.UUID          `json:"user_secret_id"`
	UserID           uuid.UUID          `json:"user_id"`
	FiveHourPct      pgtype.Int2        `json:"five_hour_pct"`
	FiveHourResetsAt pgtype.Timestamptz `json:"five_hour_resets_at"`
	SevenDayPct      pgtype.Int2        `json:"seven_day_pct"`
	SevenDayResetsAt pgtype.Timestamptz `json:"seven_day_resets_at"`
	Source           pgtype.Text        `json:"source"`
	SyncedAt         pgtype.Timestamptz `json:"synced_at"`
}

type AppSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AutopilotTrigger struct {
	RepoID      uuid.UUID          `json:"repo_id"`
	IssueIid    int64              `json:"issue_iid"`
	LastEventID int64              `json:"last_event_id"`
	HandledAt   pgtype.Timestamptz `json:"handled_at"`
}

type BoardColumn struct {
	ID        uuid.UUID `json:"id"`
	RepoID    uuid.UUID `json:"repo_id"`
	LabelName string    `json:"label_name"`
	Position  int32     `json:"position"`
}

type BoardPref struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RepoID      uuid.UUID          `json:"repo_id"`
	ExtraLabels []byte             `json:"extra_labels"`
	ShowAll     bool               `json:"show_all"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CiAutofixAttempt struct {
	RepoID         uuid.UUID          `json:"repo_id"`
	Ref            string             `json:"ref"`
	AttemptCount   int32              `json:"attempt_count"`
	LastSignature  pgtype.Text        `json:"last_signature"`
	LastPipelineID pgtype.Int8        `json:"last_pipeline_id"`
	HaltNotified   bool               `json:"halt_notified"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CliAuthRequest struct {
	ID            uuid.UUID          `json:"id"`
	CodeChallenge string             `json:"code_challenge"`
	ClientDesc    string             `json:"client_desc"`
	UserCode      string             `json:"user_code"`
	Status        string             `json:"status"`
	UserID        pgtype.UUID        `json:"user_id"`
	Scope         string             `json:"scope"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type CliToken struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   []byte             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	Scope       string             `json:"scope"`
	Revoked     bool               `json:"revoked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp  *netip.Addr        `json:"last_used_ip"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type FindingDisposition struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	RepoID        uuid.UUID          `json:"repo_id"`
	Location      string             `json:"location"`
	Status        string             `json:"status"`
	FiledIssueIid pgtype.Int8        `json:"filed_issue_iid"`
	FiledIssueUrl string             `json:"filed_issue_url"`
	FilingSince   pgtype.Timestamptz `json:"filing_since"`
	DismissReason pgtype.Text        `json:"dismiss_reason"`
	ContentHash   string             `json:"content_hash"`
	LastTitle     string             `json:"last_title"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
}

type ForgeConnection struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	ForgeType          string             `json:"forge_type"`
	BaseUrl            string             `json:"base_url"`
	BotUsername        string             `json:"bot_username"`
	BotForgeUserID     int64              `json:"bot_forge_user_id"`
	TokenCiphertext    []byte             `json:"token_ciphertext"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastVerifiedAt     pgtype.Timestamptz `json:"last_verified_at"`
	PrivilegeReport    []byte             `json:"privilege_report"`
	PrivilegeCheckedAt pgtype.Timestamptz `json:"privilege_checked_at"`
	PrivilegeStatus    pgtype.Text        `json:"privilege_status"`
	HumanUsername      pgtype.Text        `json:"human_username"`
}

type GithubProjectItem struct {
	RepoID             uuid.UUID          `json:"repo_id"`
	ForgeIssueIid      int64              `json:"forge_issue_iid"`
	ItemNodeID         string             `json:"item_node_id"`
	LastStatusOptionID pgtype.Text        `json:"last_status_option_id"`
	LastSyncedAt       pgtype.Timestamptz `json:"last_synced_at"`
}

type GithubProjectLink struct {
	ID               uuid.UUID          `json:"id"`
	RepoID           uuid.UUID          `json:"repo_id"`
	ProjectNodeID    string             `json:"project_node_id"`
	ProjectNumber    int64              `json:"project_number"`
	StatusFieldID    string             `json:"status_field_id"`
	StatusOptions    []byte             `json:"status_options"`
	OwnedByUzi       bool               `json:"owned_by_uzi"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	LastError        pgtype.Text        `json:"last_error"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UnmatchedColumns []string           `json:"unmatched_columns"`
}

type HostedWorkerToken struct {
	WorkerID        uuid.UUID          `json:"worker_id"`
	TokenCiphertext []byte             `json:"token_ciphertext"`
	DeliveredAt     pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type IncidentalFinding struct {
	ID            uuid.UUID          `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	UserID        uuid.UUID          `json:"user_id"`
	RepoID        uuid.UUID          `json:"repo_id"`
	Location      string             `json:"location"`
	Title         string             `json:"title"`
	DescriptionMd string             `json:"description_md"`
	Labels        []byte             `json:"labels"`
	Confidence    string             `json:"confidence"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Issue struct {
	ID             uuid.UUID          `json:"id"`
	RepoID         uuid.UUID          `json:"repo_id"`
	ForgeIssueIid  int64              `json:"forge_issue_iid"`
	Title          string             `json:"title"`
	State          string             `json:"state"`
	Labels         []byte             `json:"labels"`
	WebUrl         string             `json:"web_url"`
	Author         pgtype.Text        `json:"author"`
	HasPrdLink     bool               `json:"has_prd_link"`
	ForgeUpdatedAt pgtype.Timestamptz `json:"forge_updated_at"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
	BoardPosition  pgtype.Int8        `json:"board_position"`
}

type IssueProposal struct {
	ID              uuid.UUID          `json:"id"`
	RunID           uuid.UUID          `json:"run_id"`
	RepoID          uuid.UUID          `json:"repo_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Labels          []byte             `json:"labels"`
	Status          string             `json:"status"`
	CreatedIssueIid pgtype.Int8        `json:"created_issue_iid"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	ConfirmingSince pgtype.Timestamptz `json:"confirming_since"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Kind      string             `json:"kind"`
	Payload   []byte             `json:"payload"`
	RunID     pgtype.UUID        `json:"run_id"`
	ReviewID  pgtype.UUID        `json:"review_id"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PipelineStatus struct {
	ID             int64              `json:"id"`
	RepoID         uuid.UUID          `json:"repo_id"`
	Ref            string             `json:"ref"`
	PipelineID     int64              `json:"pipeline_id"`
	Sha            string             `json:"sha"`
	Status         string             `json:"status"`
	WebUrl         string             `json:"web_url"`
	ForgeUpdatedAt pgtype.Timestamptz `json:"forge_updated_at"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

type RecommendationDisposition struct {
	ID            uuid.UUID          `json:"id"`
	ReviewID      uuid.UUID          `json:"review_id"`
	Category      string             `json:"category"`
	Target        string             `json:"target"`
	Status        string             `json:"status"`
	DismissReason pgtype.Text        `json:"dismiss_reason"`
	RationaleHash string             `json:"rationale_hash"`
	SetByUserID   pgtype.UUID        `json:"set_by_user_id"`
	SetAt         pgtype.Timestamptz `json:"set_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	SetVia        pgtype.Text        `json:"set_via"`
}

type RecommendationFiledIssue struct {
	ID            uuid.UUID          `json:"id"`
	ReviewID      uuid.UUID          `json:"review_id"`
	Category      string             `json:"category"`
	Target        string             `json:"target"`
	FiledRepoID   pgtype.UUID        `json:"filed_repo_id"`
	FiledIssueIid pgtype.Int8        `json:"filed_issue_iid"`
	FiledIssueUrl string             `json:"filed_issue_url"`
	FiledByUserID pgtype.UUID        `json:"filed_by_user_id"`
	FiledAt       pgtype.Timestamptz `json:"filed_at"`
	FilingSince   pgtype.Timestamptz `json:"filing_since"`
	CloseSyncedAt pgtype.Timestamptz `json:"close_synced_at"`
}

type Repo struct {
	ID                      uuid.UUID          `json:"id"`
	ConnectionID            uuid.UUID          `json:"connection_id"`
	ForgeProjectID          int64              `json:"forge_project_id"`
	PathWithNamespace       string             `json:"path_with_namespace"`
	WebUrl                  string             `json:"web_url"`
	DefaultBranch           pgtype.Text        `json:"default_branch"`
	Enabled                 bool               `json:"enabled"`
	RepoSkillsEnabled       bool               `json:"repo_skills_enabled"`
	RepoDevboxOptIn         bool               `json:"repo_devbox_opt_in"`
	RepoClaudemdEnabled     bool               `json:"repo_claudemd_enabled"`
	GuardrailOverrideReason pgtype.Text        `json:"guardrail_override_reason"`
	GuardrailOverrideBy     pgtype.UUID        `json:"guardrail_override_by"`
	GuardrailOverrideAt     pgtype.Timestamptz `json:"guardrail_override_at"`
	RequiredCapabilities    []string           `json:"required_capabilities"`
}

type RepoToolProfile struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	RepoID    uuid.UUID          `json:"repo_id"`
	Packages  []byte             `json:"packages"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ReviewRecommendation struct {
	ID               uuid.UUID          `json:"id"`
	ReviewID         uuid.UUID          `json:"review_id"`
	Category         string             `json:"category"`
	Target           string             `json:"target"`
	RationaleMd      string             `json:"rationale_md"`
	Confidence       string             `json:"confidence"`
	ProducedByRunID  pgtype.UUID        `json:"produced_by_run_id"`
	ProducedByUserID pgtype.UUID        `json:"produced_by_user_id"`
	AddressedByRunID pgtype.UUID        `json:"addressed_by_run_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Run struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	RepoID               pgtype.UUID        `json:"repo_id"`
	IssueIid             pgtype.Int8        `json:"issue_iid"`
	IssueTitle           string             `json:"issue_title"`
	IssueDescription     string             `json:"issue_description"`
	Status               string             `json:"status"`
	RequeueCount         int32              `json:"requeue_count"`
	WorkerID             pgtype.UUID        `json:"worker_id"`
	SessionID            pgtype.Text        `json:"session_id"`
	LastSeq              int32              `json:"last_seq"`
	Branch               pgtype.Text        `json:"branch"`
	MrIid                pgtype.Int8        `json:"mr_iid"`
	FailureReason        pgtype.Text        `json:"failure_reason"`
	PlanMd               pgtype.Text        `json:"plan_md"`
	IterationCount       int32              `json:"iteration_count"`
	ClaimedAt            pgtype.Timestamptz `json:"claimed_at"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	OriginColumn         pgtype.Text        `json:"origin_column"`
	BoardColumn          pgtype.Text        `json:"board_column"`
	MovePendingSince     pgtype.Timestamptz `json:"move_pending_since"`
	MrState              pgtype.Text        `json:"mr_state"`
	AutoApprove          bool               `json:"auto_approve"`
	AutopilotCommentedAt pgtype.Timestamptz `json:"autopilot_commented_at"`
	Kind                 string             `json:"kind"`
	PipelineID           pgtype.Int8        `json:"pipeline_id"`
	PipelineRef          pgtype.Text        `json:"pipeline_ref"`
	FailureSnapshot      []byte             `json:"failure_snapshot"`
	FixVerdict           pgtype.Text        `json:"fix_verdict"`
	StopKind             pgtype.Text        `json:"stop_kind"`
	AgentSource          pgtype.Text        `json:"agent_source"`
	AgentExclusions      []byte             `json:"agent_exclusions"`
	RepoAgents           []byte             `json:"repo_agents"`
	Title                pgtype.Text        `json:"title"`
	ResumeOfRunID        pgtype.UUID        `json:"resume_of_run_id"`
	LastActivityAt       pgtype.Timestamptz `json:"last_activity_at"`
	Health               string             `json:"health"`
	HealthReason         pgtype.Text        `json:"health_reason"`
	HealthSince          pgtype.Timestamptz `json:"health_since"`
	HealthNotifiedAt     pgtype.Timestamptz `json:"health_notified_at"`
	TargetRunID          pgtype.UUID        `json:"target_run_id"`
	MrWebUrl             pgtype.Text        `json:"mr_web_url"`
	PrdDonePath          pgtype.Text        `json:"prd_done_path"`
	// When the PRD-link patch edge was consumed (patched, no-match, MR closed unmerged, or superseded). NULL with prd_done_path set = still pending.
	PrdPatchSettledAt     pgtype.Timestamptz `json:"prd_patch_settled_at"`
	AnthropicSecretID     pgtype.UUID        `json:"anthropic_secret_id"`
	AnthropicSecretLabel  pgtype.Text        `json:"anthropic_secret_label"`
	AnthropicSelectReason pgtype.Text        `json:"anthropic_select_reason"`
	AnthropicHeadroomPct  pgtype.Int2        `json:"anthropic_headroom_pct"`
	WaitOnLimit           bool               `json:"wait_on_limit"`
	LimitResetsAt         pgtype.Timestamptz `json:"limit_resets_at"`
	RetryNotBefore        pgtype.Timestamptz `json:"retry_not_before"`
	LimitWaitCount        int32              `json:"limit_wait_count"`
	RateLimitType         pgtype.Text        `json:"rate_limit_type"`
	OpenQuestionID        pgtype.Text        `json:"open_question_id"`
	ReviseCount           int32              `json:"revise_count"`
	PlanSource            string             `json:"plan_source"`
	PlannedBaseCommit     pgtype.Text        `json:"planned_base_commit"`
	RequireBaseMatch      bool               `json:"require_base_match"`
	MilestonesCandidate   []byte             `json:"milestones_candidate"`
	MilestonesFrozen      []byte             `json:"milestones_frozen"`
	MilestonesCompleted   []byte             `json:"milestones_completed"`
	MilestonesInProgress  []byte             `json:"milestones_in_progress"`
	BudgetMaxIterations   pgtype.Int4        `json:"budget_max_iterations"`
	BudgetWallSeconds     pgtype.Int4        `json:"budget_wall_seconds"`
	ScheduleID            pgtype.UUID        `json:"schedule_id"`
	LimitDeadSecretID     pgtype.UUID        `json:"limit_dead_secret_id"`
	ReportOnly            bool               `json:"report_only"`
	ReportMd              pgtype.Text        `json:"report_md"`
	CiConfigPaths         []string           `json:"ci_config_paths"`
	Model                 pgtype.Text        `json:"model"`
	OverrideSubagentModel bool               `json:"override_subagent_model"`
	FailOrigin            pgtype.Text        `json:"fail_origin"`
	Priority              pgtype.Int2        `json:"priority"`
	SummaryIntent         pgtype.Text        `json:"summary_intent"`
	SummaryPlan           pgtype.Text        `json:"summary_plan"`
	SummaryDeltas         []byte             `json:"summary_deltas"`
	IssueComments         []byte             `json:"issue_comments"`
	BaseBranch            pgtype.Text        `json:"base_branch"`
	OpenMr                bool               `json:"open_mr"`
	DispatchedAt          pgtype.Timestamptz `json:"dispatched_at"`
	ReviewTargetRunID     pgtype.UUID        `json:"review_target_run_id"`
	ReviewRequested       bool               `json:"review_requested"`
	ThenFixRequested      bool               `json:"then_fix_requested"`
	ThenFixOfRunID        pgtype.UUID        `json:"then_fix_of_run_id"`
	PreservedPatch        pgtype.Text        `json:"preserved_patch"`
	RequiredCapabilities  []string           `json:"required_capabilities"`
	StopReason            pgtype.Text        `json:"stop_reason"`
	RequiredTools         []string           `json:"required_tools"`
	SizeClass             string             `json:"size_class"`
	Interactive           bool               `json:"interactive"`
	OpenFollowupID        pgtype.Int8        `json:"open_followup_id"`
}

type RunMessage struct {
	ID            int64              `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	Seq           int32              `json:"seq"`
	Kind          string             `json:"kind"`
	Agent         pgtype.Text        `json:"agent"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AgentInstance pgtype.Text        `json:"agent_instance"`
	AgentLabel    pgtype.Text        `json:"agent_label"`
}

type RunReview struct {
	ID          uuid.UUID          `json:"id"`
	TargetRunID uuid.UUID          `json:"target_run_id"`
	JudgeRunID  pgtype.UUID        `json:"judge_run_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Verdict     string             `json:"verdict"`
	SummaryMd   string             `json:"summary_md"`
	JudgeModel  string             `json:"judge_model"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RunSchedule struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	RepoID                uuid.UUID          `json:"repo_id"`
	Target                string             `json:"target"`
	IssueIid              pgtype.Int8        `json:"issue_iid"`
	Labels                []byte             `json:"labels"`
	Prompt                pgtype.Text        `json:"prompt"`
	Timing                string             `json:"timing"`
	CronExpr              pgtype.Text        `json:"cron_expr"`
	RunAt                 pgtype.Timestamptz `json:"run_at"`
	Timezone              string             `json:"timezone"`
	NextFireAt            pgtype.Timestamptz `json:"next_fire_at"`
	LastFiredAt           pgtype.Timestamptz `json:"last_fired_at"`
	AutoApprove           bool               `json:"auto_approve"`
	WaitOnLimit           bool               `json:"wait_on_limit"`
	Enabled               bool               `json:"enabled"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	MaxIssues             pgtype.Int4        `json:"max_issues"`
	Guidance              pgtype.Text        `json:"guidance"`
	Model                 pgtype.Text        `json:"model"`
	OverrideSubagentModel bool               `json:"override_subagent_model"`
	LastFire              []byte             `json:"last_fire"`
}

type RunUsage struct {
	RunID               uuid.UUID          `json:"run_id"`
	SessionID           string             `json:"session_id"`
	Model               string             `json:"model"`
	InputTokens         int64              `json:"input_tokens"`
	CacheReadTokens     int64              `json:"cache_read_tokens"`
	CacheCreationTokens int64              `json:"cache_creation_tokens"`
	OutputTokens        int64              `json:"output_tokens"`
	CostUsd             pgtype.Numeric     `json:"cost_usd"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type RunUsageTotal struct {
	RunID               uuid.UUID      `json:"run_id"`
	InputTokens         int64          `json:"input_tokens"`
	CacheReadTokens     int64          `json:"cache_read_tokens"`
	CacheCreationTokens int64          `json:"cache_creation_tokens"`
	OutputTokens        int64          `json:"output_tokens"`
	CostUsd             pgtype.Numeric `json:"cost_usd"`
}

type RunUserInput struct {
	ID         int64              `json:"id"`
	RunID      uuid.UUID          `json:"run_id"`
	Kind       string             `json:"kind"`
	Body       pgtype.Text        `json:"body"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	QuestionID pgtype.Text        `json:"question_id"`
}

type Skill struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Body        string             `json:"body"`
	Scope       string             `json:"scope"`
	UserID      pgtype.UUID        `json:"user_id"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SlackRunMessage struct {
	RunID                       uuid.UUID          `json:"run_id"`
	ChannelID                   string             `json:"channel_id"`
	RootTs                      string             `json:"root_ts"`
	GateTs                      pgtype.Text        `json:"gate_ts"`
	GateState                   pgtype.Text        `json:"gate_state"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	GateGeneration              pgtype.Int4        `json:"gate_generation"`
	QuestionID                  pgtype.Text        `json:"question_id"`
	QuestionTs                  pgtype.Text        `json:"question_ts"`
	MilestonesNotifiedCompleted pgtype.Int4        `json:"milestones_notified_completed"`
	StatusTs                    pgtype.Text        `json:"status_ts"`
}

type TaskReview struct {
	ID          uuid.UUID          `json:"id"`
	TargetRunID uuid.UUID          `json:"target_run_id"`
	ReviewRunID pgtype.UUID        `json:"review_run_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Status      string             `json:"status"`
	SummaryMd   string             `json:"summary_md"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TaskReviewFinding struct {
	ID          uuid.UUID          `json:"id"`
	ReviewID    uuid.UUID          `json:"review_id"`
	File        string             `json:"file"`
	Symbol      string             `json:"symbol"`
	Line        int32              `json:"line"`
	Severity    string             `json:"severity"`
	SummaryMd   string             `json:"summary_md"`
	RationaleMd string             `json:"rationale_md"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ToolAllowlist struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	PinnedVersion pgtype.Text        `json:"pinned_version"`
	Note          pgtype.Text        `json:"note"`
	UpdatedBy     pgtype.UUID        `json:"updated_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                     uuid.UUID          `json:"id"`
	Email                  string             `json:"email"`
	PasswordHash           pgtype.Text        `json:"password_hash"`
	DisplayName            pgtype.Text        `json:"display_name"`
	IsAdmin                bool               `json:"is_admin"`
	IsActive               bool               `json:"is_active"`
	TokenVersion           int32              `json:"token_version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	LastLogin              pgtype.Timestamptz `json:"last_login"`
	DefaultModel           pgtype.Text        `json:"default_model"`
	AutopilotEnabled       bool               `json:"autopilot_enabled"`
	Theme                  pgtype.Text        `json:"theme"`
	SlackMemberID          pgtype.Text        `json:"slack_member_id"`
	SlackNotify            bool               `json:"slack_notify"`
	SlackResolvedID        pgtype.Text        `json:"slack_resolved_id"`
	SlackLinkConfirmedAt   pgtype.Timestamptz `json:"slack_link_confirmed_at"`
	OidcIssuer             pgtype.Text        `json:"oidc_issuer"`
	OidcSubject            pgtype.Text        `json:"oidc_subject"`
	JudgeEnabled           bool               `json:"judge_enabled"`
	JudgeAnthropicSecretID pgtype.UUID        `json:"judge_anthropic_secret_id"`
	WaitOnLimit            bool               `json:"wait_on_limit"`
	CiAutofixEnabled       bool               `json:"ci_autofix_enabled"`
	SidebarTokenIds        []uuid.UUID        `json:"sidebar_token_ids"`
	JudgeModel             pgtype.Text        `json:"judge_model"`
	SummaryModel           pgtype.Text        `json:"summary_model"`
}

type UserSecret struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Kind         string             `json:"kind"`
	Ciphertext   []byte             `json:"ciphertext"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	SealedWith   string             `json:"sealed_with"`
	Label        string             `json:"label"`
	IsDefault    bool               `json:"is_default"`
	AutoEligible bool               `json:"auto_eligible"`
}

type UserVault struct {
	UserID     uuid.UUID          `json:"user_id"`
	KekSalt    []byte             `json:"kek_salt"`
	WrappedDek []byte             `json:"wrapped_dek"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Worker struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	Name               string             `json:"name"`
	TokenHash          []byte             `json:"token_hash"`
	Status             string             `json:"status"`
	LastHeartbeatAt    pgtype.Timestamptz `json:"last_heartbeat_at"`
	Version            pgtype.Text        `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TemplateDeclared   pgtype.Text        `json:"template_declared"`
	TemplateReported   pgtype.Text        `json:"template_reported"`
	MaxConcurrentRuns  pgtype.Int4        `json:"max_concurrent_runs"`
	StatsCpuPct        pgtype.Float4      `json:"stats_cpu_pct"`
	StatsMemBytes      pgtype.Int8        `json:"stats_mem_bytes"`
	StatsMemLimitBytes pgtype.Int8        `json:"stats_mem_limit_bytes"`
	StatsSource        pgtype.Text        `json:"stats_source"`
	Kind               string             `json:"kind"`
	HostedSize         pgtype.Text        `json:"hosted_size"`
	HostedGeneration   int64              `json:"hosted_generation"`
	DockerEnabled      pgtype.Bool        `json:"docker_enabled"`
	AnthropicSecretID  pgtype.UUID        `json:"anthropic_secret_id"`
	AnthropicBindMode  string             `json:"anthropic_bind_mode"`
	OnlineSince        pgtype.Timestamptz `json:"online_since"`
	DrainingSince      pgtype.Timestamptz `json:"draining_since"`
	Capabilities       []string           `json:"capabilities"`
}

type WorkerUpgradeMute struct {
	UserID    uuid.UUID          `json:"user_id"`
	WorkerID  uuid.UUID          `json:"worker_id"`
	Release   string             `json:"release"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkerUpgradeReport struct {
	WorkerID             uuid.UUID          `json:"worker_id"`
	Phase                string             `json:"phase"`
	PhaseSince           pgtype.Timestamptz `json:"phase_since"`
	TargetImage          pgtype.Text        `json:"target_image"`
	PodPhase             pgtype.Text        `json:"pod_phase"`
	BlockingContainer    pgtype.Text        `json:"blocking_container"`
	BlockingReason       pgtype.Text        `json:"blocking_reason"`
	RestartCount         int32              `json:"restart_count"`
	LastExitCode         pgtype.Int4        `json:"last_exit_code"`
	ControllerReportedAt pgtype.Timestamptz `json:"controller_reported_at"`
	ObservedAt           pgtype.Timestamptz `json:"observed_at"`
	UpgradingSince       pgtype.Timestamptz `json:"upgrading_since"`
	PollIntervalSeconds  pgtype.Int4        `json:"poll_interval_seconds"`
	WorkerImageTag       pgtype.Text        `json:"worker_image_tag"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
