// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mr_review_authors.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const admitReviewAuthors = `-- name: AdmitReviewAuthors :exec
WITH numbered AS MATERIALIZED (
    SELECT o.id, nextval('mr_review_author_queue_seq') AS seq
    FROM (
        SELECT u.id, u.ord
        FROM unnest($3::bigint[]) WITH ORDINALITY AS u(id, ord)
        ORDER BY u.ord
    ) o
)
INSERT INTO mr_review_author_queue (repo_id, ref, forge_user_id, queue_seq)
SELECT $1::uuid, $2, n.id, n.seq
FROM numbered n
ORDER BY n.seq
ON CONFLICT (repo_id, ref, forge_user_id) DO NOTHING
`

type AdmitReviewAuthorsParams struct {
	RepoID       uuid.UUID `json:"repo_id"`
	Ref          string    `json:"ref"`
	ForgeUserIds []int64   `json:"forge_user_ids"`
}

// Admit missing authors at the back of the queue, in the order given. queue_seq is nextval of
// mr_review_author_queue_seq, drawn in array order: the MATERIALIZED CTE computes each
// sequence value exactly once per row, from a subquery sorted by array position (a sorted
// subquery is not flattened into its parent, so the projection runs in sorted order). An
// author already queued keeps its place (the conflicting row only burns a sequence value).
// Run under LockReviewAuthorQueue.
func (q *Queries) AdmitReviewAuthors(ctx context.Context, arg AdmitReviewAuthorsParams) error {
	_, err := q.db.Exec(ctx, admitReviewAuthors, arg.RepoID, arg.Ref, arg.ForgeUserIds)
	return err
}

const deleteExpiredReviewAuthorVerdicts = `-- name: DeleteExpiredReviewAuthorVerdicts :execrows
DELETE FROM mr_review_author_verdicts
WHERE repo_id = $1::uuid
  AND not_eligible_at < $2::timestamptz
`

type DeleteExpiredReviewAuthorVerdictsParams struct {
	RepoID uuid.UUID          `json:"repo_id"`
	Before pgtype.Timestamptz `json:"before"`
}

func (q *Queries) DeleteExpiredReviewAuthorVerdicts(ctx context.Context, arg DeleteExpiredReviewAuthorVerdictsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredReviewAuthorVerdicts, arg.RepoID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleReviewAuthorQueue = `-- name: DeleteStaleReviewAuthorQueue :execrows
DELETE FROM mr_review_author_queue
WHERE repo_id = $1::uuid
  AND ref = $2
  AND GREATEST(admitted_at, last_attempt_at) < $3::timestamptz
`

type DeleteStaleReviewAuthorQueueParams struct {
	RepoID uuid.UUID          `json:"repo_id"`
	Ref    string             `json:"ref"`
	Before pgtype.Timestamptz `json:"before"`
}

// Evict rows untouched since @before. Run under LockReviewAuthorQueue.
func (q *Queries) DeleteStaleReviewAuthorQueue(ctx context.Context, arg DeleteStaleReviewAuthorQueueParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleReviewAuthorQueue, arg.RepoID, arg.Ref, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFreshNotEligibleAuthors = `-- name: ListFreshNotEligibleAuthors :many
SELECT forge_user_id
FROM mr_review_author_verdicts
WHERE repo_id = $1::uuid
  AND not_eligible_at >= $2::timestamptz
`

type ListFreshNotEligibleAuthorsParams struct {
	RepoID uuid.UUID          `json:"repo_id"`
	Since  pgtype.Timestamptz `json:"since"`
}

// The authors with a not-eligible verdict recorded at or after @since.
func (q *Queries) ListFreshNotEligibleAuthors(ctx context.Context, arg ListFreshNotEligibleAuthorsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listFreshNotEligibleAuthors, arg.RepoID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var forge_user_id int64
		if err := rows.Scan(&forge_user_id); err != nil {
			return nil, err
		}
		items = append(items, forge_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewAuthorQueue = `-- name: ListReviewAuthorQueue :many
SELECT forge_user_id, queue_seq
FROM mr_review_author_queue
WHERE repo_id = $1::uuid AND ref = $2
ORDER BY queue_seq
`

type ListReviewAuthorQueueParams struct {
	RepoID uuid.UUID `json:"repo_id"`
	Ref    string    `json:"ref"`
}

type ListReviewAuthorQueueRow struct {
	ForgeUserID int64 `json:"forge_user_id"`
	QueueSeq    int64 `json:"queue_seq"`
}

// The queue in attempt order. An unlocked read: the caller uses the max queue_seq it
// observes as the bound of its later prune.
func (q *Queries) ListReviewAuthorQueue(ctx context.Context, arg ListReviewAuthorQueueParams) ([]ListReviewAuthorQueueRow, error) {
	rows, err := q.db.Query(ctx, listReviewAuthorQueue, arg.RepoID, arg.Ref)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewAuthorQueueRow{}
	for rows.Next() {
		var i ListReviewAuthorQueueRow
		if err := rows.Scan(&i.ForgeUserID, &i.QueueSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleReviewAuthorQueueRefs = `-- name: ListStaleReviewAuthorQueueRefs :many
SELECT DISTINCT ref
FROM mr_review_author_queue
WHERE repo_id = $1::uuid
  AND GREATEST(admitted_at, last_attempt_at) < $2::timestamptz
`

type ListStaleReviewAuthorQueueRefsParams struct {
	RepoID uuid.UUID          `json:"repo_id"`
	Before pgtype.Timestamptz `json:"before"`
}

// The refs of one repo that hold queue rows untouched for a long time.
func (q *Queries) ListStaleReviewAuthorQueueRefs(ctx context.Context, arg ListStaleReviewAuthorQueueRefsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listStaleReviewAuthorQueueRefs, arg.RepoID, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var ref string
		if err := rows.Scan(&ref); err != nil {
			return nil, err
		}
		items = append(items, ref)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReviewAuthorQueue = `-- name: LockReviewAuthorQueue :exec

SELECT pg_advisory_xact_lock(
    1970958961,
    hashtext($1::uuid::text || '/' || $2::text)
)
`

type LockReviewAuthorQueueParams struct {
	RepoID uuid.UUID `json:"repo_id"`
	Ref    string    `json:"ref"`
}

// MR review-comment author eligibility (issue #2347 M1) -----------------------
// The verdict cache and the fair-progress queue behind the review-comment
// eligibility assessment (workersvc.ReviewAssessor). Every queue MUTATION
// (admit, requeue, prune, stale eviction) runs in its own short transaction that
// first takes LockReviewAuthorQueue; the reads and the verdict writes do not.
// Serializes every mutation of one (repo, ref) review-author queue. Two-int advisory
// lock: class 1970958961 = 0x757A7271 ("uzrq"), the value of store.ReviewAuthorQueueLockClass
// in migrate.go; TestReviewAuthorQueueLockClassMatchesSQL pins this literal to it. The objid
// is hashtext of the repo and ref, so a collision merely serializes two unrelated queues for
// a moment. XACT-scoped: released on commit or rollback, so it must run on a
// transaction-bound Queries, and it is never held across a forge call.
func (q *Queries) LockReviewAuthorQueue(ctx context.Context, arg LockReviewAuthorQueueParams) error {
	_, err := q.db.Exec(ctx, lockReviewAuthorQueue, arg.RepoID, arg.Ref)
	return err
}

const pruneReviewAuthorQueue = `-- name: PruneReviewAuthorQueue :execrows
DELETE FROM mr_review_author_queue
WHERE repo_id = $1::uuid
  AND ref = $2
  AND queue_seq <= $3::bigint
  AND NOT EXISTS (
      SELECT 1 FROM unnest(COALESCE($4::bigint[], '{}'::bigint[])) AS k(id)
      WHERE k.id = mr_review_author_queue.forge_user_id
  )
`

type PruneReviewAuthorQueueParams struct {
	RepoID         uuid.UUID `json:"repo_id"`
	Ref            string    `json:"ref"`
	ObservedMaxSeq int64     `json:"observed_max_seq"`
	KeepIds        []int64   `json:"keep_ids"`
}

// Drop the authors that are no longer candidates, but only rows the caller could have
// observed: queue_seq <= @observed_max_seq. Because queue_seq comes from a sequence that is
// never reset, a row admitted after the observation always sits above it, so a stale pruner
// can never delete it. Run under LockReviewAuthorQueue.
func (q *Queries) PruneReviewAuthorQueue(ctx context.Context, arg PruneReviewAuthorQueueParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneReviewAuthorQueue,
		arg.RepoID,
		arg.Ref,
		arg.ObservedMaxSeq,
		arg.KeepIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueReviewAuthors = `-- name: RequeueReviewAuthors :exec
WITH numbered AS MATERIALIZED (
    SELECT o.id, nextval('mr_review_author_queue_seq') AS seq
    FROM (
        SELECT u.id, u.ord
        FROM unnest($3::bigint[]) WITH ORDINALITY AS u(id, ord)
        ORDER BY u.ord
    ) o
)
UPDATE mr_review_author_queue q
SET queue_seq = n.seq,
    last_attempt_at = now()
FROM numbered n
WHERE q.repo_id = $1::uuid
  AND q.ref = $2
  AND q.forge_user_id = n.id
`

type RequeueReviewAuthorsParams struct {
	RepoID       uuid.UUID `json:"repo_id"`
	Ref          string    `json:"ref"`
	ForgeUserIds []int64   `json:"forge_user_ids"`
}

// Move the given authors to the back, in the order given, stamping the attempt time. Fresh
// sequence values (drawn exactly as AdmitReviewAuthors does) are always above every existing
// one. An author no longer queued is skipped. Run under LockReviewAuthorQueue.
func (q *Queries) RequeueReviewAuthors(ctx context.Context, arg RequeueReviewAuthorsParams) error {
	_, err := q.db.Exec(ctx, requeueReviewAuthors, arg.RepoID, arg.Ref, arg.ForgeUserIds)
	return err
}

const upsertReviewAuthorVerdict = `-- name: UpsertReviewAuthorVerdict :exec
INSERT INTO mr_review_author_verdicts (repo_id, forge_user_id, not_eligible_at)
VALUES ($1::uuid, $2, $3::timestamptz)
ON CONFLICT (repo_id, forge_user_id) DO UPDATE
SET not_eligible_at = GREATEST(mr_review_author_verdicts.not_eligible_at, EXCLUDED.not_eligible_at)
`

type UpsertReviewAuthorVerdictParams struct {
	RepoID        uuid.UUID          `json:"repo_id"`
	ForgeUserID   int64              `json:"forge_user_id"`
	NotEligibleAt pgtype.Timestamptz `json:"not_eligible_at"`
}

// Record a not-eligible answer. GREATEST keeps the newest time if two writers race.
func (q *Queries) UpsertReviewAuthorVerdict(ctx context.Context, arg UpsertReviewAuthorVerdictParams) error {
	_, err := q.db.Exec(ctx, upsertReviewAuthorVerdict, arg.RepoID, arg.ForgeUserID, arg.NotEligibleAt)
	return err
}
