// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOAuthAuthorizeRequest = `-- name: ClaimOAuthAuthorizeRequest :one
UPDATE oauth_authorize_requests
   SET status = 'approved', user_id = $1
 WHERE id = $2 AND status = 'pending' AND expires_at > now()
RETURNING id, product_id, redirect_uri, scopes, state, code_challenge, binding_hash, source_prefix, status, user_id, grant_id, code_hash, code_expires_at, created_at, expires_at
`

type ClaimOAuthAuthorizeRequestParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     uuid.UUID   `json:"id"`
}

// The single-use approve claim: pending -> approved in one conditional UPDATE, binding the row to
// the approving user. Zero rows (pgx.ErrNoRows) means not pending, expired or unknown: a second
// approve, an approve after deny, or a race lost; the handler maps it to 409. Runs inside the
// approve transaction, after the grant lock (lock order), so a later failure or a lost claim rolls
// the whole approve back and the request stays pending.
func (q *Queries) ClaimOAuthAuthorizeRequest(ctx context.Context, arg ClaimOAuthAuthorizeRequestParams) (OauthAuthorizeRequest, error) {
	row := q.db.QueryRow(ctx, claimOAuthAuthorizeRequest, arg.UserID, arg.ID)
	var i OauthAuthorizeRequest
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.CodeChallenge,
		&i.BindingHash,
		&i.SourcePrefix,
		&i.Status,
		&i.UserID,
		&i.GrantID,
		&i.CodeHash,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const countLivePendingOAuthRequests = `-- name: CountLivePendingOAuthRequests :one
SELECT
    (SELECT count(*) FROM (
        SELECT 1 FROM oauth_authorize_requests
         WHERE status = 'pending' AND expires_at > now()
           AND oauth_authorize_requests.product_id = $1
           AND oauth_authorize_requests.source_prefix = $2
         LIMIT $3::int
    ) s)::bigint AS source_pending,
    (SELECT count(*) FROM (
        SELECT 1 FROM oauth_authorize_requests
         WHERE status = 'pending' AND expires_at > now() AND oauth_authorize_requests.product_id = $1
         LIMIT $4::int
    ) p)::bigint AS product_pending,
    (SELECT count(*) FROM (
        SELECT 1 FROM oauth_authorize_requests
         WHERE status = 'pending' AND expires_at > now()
         LIMIT $5::int
    ) g)::bigint AS global_pending
`

type CountLivePendingOAuthRequestsParams struct {
	ForProduct   uuid.UUID `json:"for_product"`
	ForSource    string    `json:"for_source"`
	SourceLimit  int32     `json:"source_limit"`
	ProductLimit int32     `json:"product_limit"`
	GlobalLimit  int32     `json:"global_limit"`
}

type CountLivePendingOAuthRequestsRow struct {
	SourcePending  int64 `json:"source_pending"`
	ProductPending int64 `json:"product_pending"`
	GlobalPending  int64 `json:"global_pending"`
}

// How many live (pending, unexpired) authorize requests exist for the (product, source), for the
// product and overall, each counted up to its limit so the work is bounded however many rows an
// attacker piles up. The unauthenticated authorize endpoint checks them against its caps (source
// first, the fairness bound; the other two are storage backstops) BEFORE inserting, under
// LockOAuthAuthorize. idx_oauth_authorize_requests_pending serves all three subqueries.
func (q *Queries) CountLivePendingOAuthRequests(ctx context.Context, arg CountLivePendingOAuthRequestsParams) (CountLivePendingOAuthRequestsRow, error) {
	row := q.db.QueryRow(ctx, countLivePendingOAuthRequests,
		arg.ForProduct,
		arg.ForSource,
		arg.SourceLimit,
		arg.ProductLimit,
		arg.GlobalLimit,
	)
	var i CountLivePendingOAuthRequestsRow
	err := row.Scan(&i.SourcePending, &i.ProductPending, &i.GlobalPending)
	return i, err
}

const createOAuthAuthorizeRequest = `-- name: CreateOAuthAuthorizeRequest :one

INSERT INTO oauth_authorize_requests (product_id, redirect_uri, scopes, state, code_challenge, binding_hash, source_prefix, expires_at)
VALUES ($1, $2, $3::text[], $4, $5, $6::bytea, $7, $8)
RETURNING id, product_id, redirect_uri, scopes, state, code_challenge, binding_hash, source_prefix, status, user_id, grant_id, code_hash, code_expires_at, created_at, expires_at
`

type CreateOAuthAuthorizeRequestParams struct {
	ProductID     uuid.UUID          `json:"product_id"`
	RedirectUri   string             `json:"redirect_uri"`
	Scopes        []string           `json:"scopes"`
	State         string             `json:"state"`
	CodeChallenge string             `json:"code_challenge"`
	BindingHash   []byte             `json:"binding_hash"`
	SourcePrefix  string             `json:"source_prefix"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

// PRD #1910 M2: the consent half of the OAuth authorization server (oauth_grants and
// oauth_authorize_requests, migration 00283). Lock order everywhere (D8): the grant row first, then
// that grant's product_tokens rows, then its oauth_authorize_requests rows. The approve transaction
// claims the request it decides LAST (after the grant lock, the narrowing revoke and the superseding
// of the grant's earlier codes), so it never holds a request row while waiting for a grant. Only the
// TTL sweep and deny lock request rows without a grant lock; neither ever waits for a grant.
// Store the pending request GET /api/oauth/authorize validated. The caller has already capped and
// validated every field (oauthsrv), so nothing here is attacker-sized. binding_hash is the sha256
// of the browser-binding cookie nonce; the plaintext nonce is never stored.
func (q *Queries) CreateOAuthAuthorizeRequest(ctx context.Context, arg CreateOAuthAuthorizeRequestParams) (OauthAuthorizeRequest, error) {
	row := q.db.QueryRow(ctx, createOAuthAuthorizeRequest,
		arg.ProductID,
		arg.RedirectUri,
		arg.Scopes,
		arg.State,
		arg.CodeChallenge,
		arg.BindingHash,
		arg.SourcePrefix,
		arg.ExpiresAt,
	)
	var i OauthAuthorizeRequest
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.CodeChallenge,
		&i.BindingHash,
		&i.SourcePrefix,
		&i.Status,
		&i.UserID,
		&i.GrantID,
		&i.CodeHash,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredOAuthAuthorizeRequests = `-- name: DeleteExpiredOAuthAuthorizeRequests :execrows
DELETE FROM oauth_authorize_requests
 WHERE (status IN ('pending', 'denied', 'superseded') AND expires_at < now())
    OR (status IN ('approved', 'redeemed') AND code_expires_at < now() - interval '10 minutes')
`

// TTL sweep (beside DeleteExpiredCLIAuthRequests, in the handler's start path and on the server's
// sweeper ticker). pending, denied and superseded rows go once past expires_at. approved and
// redeemed rows carry a code M3's replay detection (RFC 6749 section 4.1.2) must still recognise,
// so they live until their code expired more than 10 minutes ago. Two ORed range predicates, one
// per index (idx_oauth_authorize_requests_expires, _code_expires), so the planner can BitmapOr
// them; a CASE over status could use neither.
func (q *Queries) DeleteExpiredOAuthAuthorizeRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthAuthorizeRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const denyOAuthAuthorizeRequest = `-- name: DenyOAuthAuthorizeRequest :one
UPDATE oauth_authorize_requests
   SET status = 'denied', user_id = $1
 WHERE id = $2 AND status = 'pending' AND expires_at > now()
RETURNING id, product_id, redirect_uri, scopes, state, code_challenge, binding_hash, source_prefix, status, user_id, grant_id, code_hash, code_expires_at, created_at, expires_at
`

type DenyOAuthAuthorizeRequestParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     uuid.UUID   `json:"id"`
}

// pending -> denied, guarded like the claim; zero rows is a 409 in the handler.
func (q *Queries) DenyOAuthAuthorizeRequest(ctx context.Context, arg DenyOAuthAuthorizeRequestParams) (OauthAuthorizeRequest, error) {
	row := q.db.QueryRow(ctx, denyOAuthAuthorizeRequest, arg.UserID, arg.ID)
	var i OauthAuthorizeRequest
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.CodeChallenge,
		&i.BindingHash,
		&i.SourcePrefix,
		&i.Status,
		&i.UserID,
		&i.GrantID,
		&i.CodeHash,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getOAuthAuthorizeRequest = `-- name: GetOAuthAuthorizeRequest :one
SELECT id, product_id, redirect_uri, scopes, state, code_challenge, binding_hash, source_prefix, status, user_id, grant_id, code_hash, code_expires_at, created_at, expires_at FROM oauth_authorize_requests WHERE id = $1
`

// The request by id (the URL-carried key). The handler compares binding_hash in constant time
// before exposing anything.
func (q *Queries) GetOAuthAuthorizeRequest(ctx context.Context, id uuid.UUID) (OauthAuthorizeRequest, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthorizeRequest, id)
	var i OauthAuthorizeRequest
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.CodeChallenge,
		&i.BindingHash,
		&i.SourcePrefix,
		&i.Status,
		&i.UserID,
		&i.GrantID,
		&i.CodeHash,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertOAuthGrant = `-- name: InsertOAuthGrant :one
INSERT INTO oauth_grants (user_id, product_id, scopes)
VALUES ($1, $2, $3::text[])
ON CONFLICT (user_id, product_id) WHERE revoked_at IS NULL DO NOTHING
RETURNING id, user_id, product_id, scopes, refresh_token_hash, refresh_token_prefix, refresh_issued_at, refresh_last_used_at, created_at, consented_at, revoked_at
`

type InsertOAuthGrantParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProductID uuid.UUID `json:"product_id"`
	Scopes    []string  `json:"scopes"`
}

// First consent: insert the live grant, conflict-safe against uq_oauth_grants_live. On a conflict
// no row is returned (pgx.ErrNoRows) and the handler locks the live grant with a SEPARATE
// statement (LockLiveOAuthGrant): an ON CONFLICT DO NOTHING can meet a row its own statement
// snapshot cannot see (PRD #1910 D8).
func (q *Queries) InsertOAuthGrant(ctx context.Context, arg InsertOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, insertOAuthGrant, arg.UserID, arg.ProductID, arg.Scopes)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Scopes,
		&i.RefreshTokenHash,
		&i.RefreshTokenPrefix,
		&i.RefreshIssuedAt,
		&i.RefreshLastUsedAt,
		&i.CreatedAt,
		&i.ConsentedAt,
		&i.RevokedAt,
	)
	return i, err
}

const issueOAuthAuthorizationCode = `-- name: IssueOAuthAuthorizationCode :one
UPDATE oauth_authorize_requests
   SET code_hash = $1::bytea,
       code_expires_at = $2,
       grant_id = $3
 WHERE id = $4 AND status = 'approved' AND user_id = $5
RETURNING id, product_id, redirect_uri, scopes, state, code_challenge, binding_hash, source_prefix, status, user_id, grant_id, code_hash, code_expires_at, created_at, expires_at
`

type IssueOAuthAuthorizationCodeParams struct {
	CodeHash      []byte             `json:"code_hash"`
	CodeExpiresAt pgtype.Timestamptz `json:"code_expires_at"`
	GrantID       pgtype.UUID        `json:"grant_id"`
	ID            uuid.UUID          `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
}

// Attach the authorization code to the request the approve just claimed: sha256 at rest, 60 s
// expiry, bound to the grant. Guarded on status='approved' and the approving user.
func (q *Queries) IssueOAuthAuthorizationCode(ctx context.Context, arg IssueOAuthAuthorizationCodeParams) (OauthAuthorizeRequest, error) {
	row := q.db.QueryRow(ctx, issueOAuthAuthorizationCode,
		arg.CodeHash,
		arg.CodeExpiresAt,
		arg.GrantID,
		arg.ID,
		arg.UserID,
	)
	var i OauthAuthorizeRequest
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.CodeChallenge,
		&i.BindingHash,
		&i.SourcePrefix,
		&i.Status,
		&i.UserID,
		&i.GrantID,
		&i.CodeHash,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const lockLiveOAuthGrant = `-- name: LockLiveOAuthGrant :one
SELECT id, user_id, product_id, scopes, refresh_token_hash, refresh_token_prefix, refresh_issued_at, refresh_last_used_at, created_at, consented_at, revoked_at FROM oauth_grants
 WHERE user_id = $1 AND product_id = $2 AND revoked_at IS NULL
 FOR UPDATE
`

type LockLiveOAuthGrantParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProductID uuid.UUID `json:"product_id"`
}

// The user's live grant for the product, row-locked for the rest of the transaction. No row means
// there is none (or it was revoked meanwhile); the caller retries the insert.
func (q *Queries) LockLiveOAuthGrant(ctx context.Context, arg LockLiveOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, lockLiveOAuthGrant, arg.UserID, arg.ProductID)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Scopes,
		&i.RefreshTokenHash,
		&i.RefreshTokenPrefix,
		&i.RefreshIssuedAt,
		&i.RefreshLastUsedAt,
		&i.CreatedAt,
		&i.ConsentedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockOAuthAuthorize = `-- name: LockOAuthAuthorize :exec
SELECT pg_advisory_xact_lock(
    1970958177,
    hashtext($1::uuid::text)
)
`

// Serializes one product's authorize inserts, so the pending caps cannot be passed by concurrent
// requests under READ COMMITTED (each would count against its own snapshot): the authorize
// handler runs, in ONE transaction, this lock, then CountLivePendingOAuthRequests, then
// CreateOAuthAuthorizeRequest. The same reasoning as LockProductTokenMint.
//
// Two-int advisory lock: class 1970958177 = 0x757A6F61 ("uzoa"), the value of
// store.OAuthAuthorizeLockClass in migrate.go, distinct from every other class constant there
// (TestOAuthAuthorizeLockClassMatchesSQL pins this literal and TestProductTokenMintLockClassMatchesSQL
// enumerates the collision check). The objid is hashtext of the product id, so two products can
// collide: a moment of contention, never a correctness problem. XACT-scoped: released on commit
// or rollback, so it must run on a transaction-bound Queries.
func (q *Queries) LockOAuthAuthorize(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockOAuthAuthorize, productID)
	return err
}

const oAuthGrantHasTokenOutsideScopes = `-- name: OAuthGrantHasTokenOutsideScopes :one
SELECT EXISTS (
    SELECT 1
      FROM product_tokens
     WHERE grant_id = $1
       AND NOT revoked
       AND NOT (scopes <@ $2::text[])
) AS drops_scope
`

type OAuthGrantHasTokenOutsideScopesParams struct {
	GrantID pgtype.UUID `json:"grant_id"`
	Scopes  []string    `json:"scopes"`
}

// True when some unrevoked access token of the grant, expired or not, holds a scope that is not in
// the given set, i.e. the new scope set drops something a token carries. Re-consent revokes the
// grant's access tokens only then (PRD #1910 D6). Expiry is deliberately ignored: an expired
// jobs:run token may have created a still-running job, and the ListRevokedProductJobs sweep cancels
// by revoked, not by expiry. Run with the grant already locked.
func (q *Queries) OAuthGrantHasTokenOutsideScopes(ctx context.Context, arg OAuthGrantHasTokenOutsideScopesParams) (bool, error) {
	row := q.db.QueryRow(ctx, oAuthGrantHasTokenOutsideScopes, arg.GrantID, arg.Scopes)
	var drops_scope bool
	err := row.Scan(&drops_scope)
	return drops_scope, err
}

const reconsentOAuthGrant = `-- name: ReconsentOAuthGrant :one
UPDATE oauth_grants
   SET scopes = $1::text[],
       consented_at = now(),
       refresh_token_hash = NULL,
       refresh_token_prefix = NULL,
       refresh_issued_at = NULL,
       refresh_last_used_at = NULL
 WHERE id = $2 AND revoked_at IS NULL
RETURNING id, user_id, product_id, scopes, refresh_token_hash, refresh_token_prefix, refresh_issued_at, refresh_last_used_at, created_at, consented_at, revoked_at
`

type ReconsentOAuthGrantParams struct {
	Scopes []string  `json:"scopes"`
	ID     uuid.UUID `json:"id"`
}

// Re-consent on a LOCKED live grant: replace the scopes with the newly approved set, stamp
// consented_at (the 90-day absolute refresh expiry counts from it) and clear the refresh token, so
// the previous one stops working. Guarded on revoked_at IS NULL as a belt on the lock.
func (q *Queries) ReconsentOAuthGrant(ctx context.Context, arg ReconsentOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, reconsentOAuthGrant, arg.Scopes, arg.ID)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Scopes,
		&i.RefreshTokenHash,
		&i.RefreshTokenPrefix,
		&i.RefreshIssuedAt,
		&i.RefreshLastUsedAt,
		&i.CreatedAt,
		&i.ConsentedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeOAuthGrantProductTokens = `-- name: RevokeOAuthGrantProductTokens :execrows
UPDATE product_tokens SET revoked = true WHERE grant_id = $1 AND NOT revoked
`

// Set revoked on every unrevoked access token of the grant, expired or not, so the existing
// ListRevokedProductJobs sweep cancels the jobs they created. Run with the grant already locked
// (lock order: grant, then product_tokens).
func (q *Queries) RevokeOAuthGrantProductTokens(ctx context.Context, grantID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOAuthGrantProductTokens, grantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeOAuthGrantCodes = `-- name: SupersedeOAuthGrantCodes :execrows
UPDATE oauth_authorize_requests
   SET status = 'superseded'
 WHERE grant_id = $1 AND status = 'approved'
`

// Mark the grant's issued-but-unredeemed codes superseded (a re-consent or a newer code replaces
// them). Run with the grant already locked, after its product_tokens (lock order).
func (q *Queries) SupersedeOAuthGrantCodes(ctx context.Context, grantID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeOAuthGrantCodes, grantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
