// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan_cross_check_summary.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestPlanCrossCheckSummary = `-- name: GetLatestPlanCrossCheckSummary :one
SELECT cc.round, cc.verdict, cc.reason_class,
    cc.findings, cc.checker_run_id, cc.checker_model, cc.checker_effort, cc.checker_model_source, cc.checker_effort_source,
    (checker.id IS NOT NULL)::boolean AS has_child,
    (usage.run_id IS NOT NULL)::boolean AS has_usage,
    COALESCE(usage.input_tokens, 0)::bigint AS input_tokens,
    COALESCE(usage.cache_read_tokens, 0)::bigint AS cache_read_tokens,
    COALESCE(usage.cache_creation_tokens, 0)::bigint AS cache_creation_tokens,
    COALESCE(usage.output_tokens, 0)::bigint AS output_tokens,
    usage.cost_usd, usage.cost_status,
    -- Once a human requests revision, this one-round check is earlier-plan
    -- evidence even when the revised presentation retains identical plan fields.
    (CASE WHEN lead.revise_count > 0 THEN true
     WHEN lead.plan_md IS NULL THEN
        cc.lead_claim_generation <> lead.claim_generation OR lead.gate_revision > 0
     ELSE NOT COALESCE(
        cc.lead_claim_generation = lead.claim_generation
        AND cc.plan_md = lead.plan_md
        AND cc.milestones = CASE WHEN lead.status = 'awaiting_approval'
            THEN lead.milestones_candidate ELSE lead.milestones_frozen END
        AND cc.required_capabilities <@ lead.required_capabilities
        AND lead.required_capabilities <@ cc.required_capabilities
        AND cc.required_tools <@ lead.required_tools
        AND lead.required_tools <@ cc.required_tools
        AND cc.size_class = lead.size_class, false)
     END)::boolean AS historical
FROM cross_checks cc
JOIN runs lead ON lead.id = cc.lead_run_id
LEFT JOIN runs checker ON checker.id = cc.checker_run_id
    AND checker.user_id = lead.user_id AND checker.kind = 'cross_check'
    AND checker.target_run_id = lead.id AND checker.harness = cc.checker_harness
LEFT JOIN run_usage_totals usage ON usage.run_id = checker.id
WHERE lead.id = $1 AND lead.user_id = $2
    AND lead.kind <> 'cross_check' AND cc.stage = 'plan' AND cc.round = 1
    AND (cc.findings IS NULL OR octet_length(cc.findings::text) <= 65536)
    AND (cc.checker_model IS NULL OR octet_length(cc.checker_model) <= 512)
    AND (cc.checker_effort IS NULL OR octet_length(cc.checker_effort) <= 512)
ORDER BY cc.round DESC
LIMIT 1
`

type GetLatestPlanCrossCheckSummaryParams struct {
	LeadRunID uuid.UUID `json:"lead_run_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetLatestPlanCrossCheckSummaryRow struct {
	Round               int32          `json:"round"`
	Verdict             string         `json:"verdict"`
	ReasonClass         pgtype.Text    `json:"reason_class"`
	Findings            []byte         `json:"findings"`
	CheckerRunID        pgtype.UUID    `json:"checker_run_id"`
	CheckerModel        pgtype.Text    `json:"checker_model"`
	CheckerEffort       pgtype.Text    `json:"checker_effort"`
	CheckerModelSource  pgtype.Text    `json:"checker_model_source"`
	CheckerEffortSource pgtype.Text    `json:"checker_effort_source"`
	HasChild            bool           `json:"has_child"`
	HasUsage            bool           `json:"has_usage"`
	InputTokens         int64          `json:"input_tokens"`
	CacheReadTokens     int64          `json:"cache_read_tokens"`
	CacheCreationTokens int64          `json:"cache_creation_tokens"`
	OutputTokens        int64          `json:"output_tokens"`
	CostUsd             pgtype.Numeric `json:"cost_usd"`
	CostStatus          pgtype.Text    `json:"cost_status"`
	Historical          bool           `json:"historical"`
}

// Owner detail only; no locks, expiry writes, candidate/diff/context serialization,
// or approval authority. Bound legacy text before transfer. Child metadata is
// optional after deletion, and usage is joined only through the same-owner child.
func (q *Queries) GetLatestPlanCrossCheckSummary(ctx context.Context, arg GetLatestPlanCrossCheckSummaryParams) (GetLatestPlanCrossCheckSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLatestPlanCrossCheckSummary, arg.LeadRunID, arg.UserID)
	var i GetLatestPlanCrossCheckSummaryRow
	err := row.Scan(
		&i.Round,
		&i.Verdict,
		&i.ReasonClass,
		&i.Findings,
		&i.CheckerRunID,
		&i.CheckerModel,
		&i.CheckerEffort,
		&i.CheckerModelSource,
		&i.CheckerEffortSource,
		&i.HasChild,
		&i.HasUsage,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.CacheCreationTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.CostStatus,
		&i.Historical,
	)
	return i, err
}
