// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan_cross_check.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const hasLivePlanCrossCheck = `-- name: HasLivePlanCrossCheck :one
SELECT EXISTS (
    SELECT 1 FROM cross_checks cc
    JOIN runs lead ON lead.id = cc.lead_run_id
    WHERE lead.id = $1 AND lead.plan_cross_check_required
      AND cc.stage = 'plan' AND cc.round = 1 AND cc.verdict = 'pending'
      AND cc.lead_claim_generation = lead.claim_generation
      AND lead.status IN ('claimed', 'running') AND lead.claim_released_at IS NULL
      AND cc.deadline_at > now()
)::boolean AS has_live_plan_cross_check
`

func (q *Queries) HasLivePlanCrossCheck(ctx context.Context, leadRunID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasLivePlanCrossCheck, leadRunID)
	var has_live_plan_cross_check bool
	err := row.Scan(&has_live_plan_cross_check)
	return has_live_plan_cross_check, err
}

const hasPendingPlanCrossCheck = `-- name: HasPendingPlanCrossCheck :one
SELECT EXISTS (
    SELECT 1 FROM cross_checks cc
    WHERE cc.lead_run_id = $1 AND cc.stage = 'plan' AND cc.verdict = 'pending'
)::boolean AS has_pending_plan_cross_check
`

// Strict settlement proof: an expired or stale pending row still requires settlement.
func (q *Queries) HasPendingPlanCrossCheck(ctx context.Context, leadRunID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingPlanCrossCheck, leadRunID)
	var has_pending_plan_cross_check bool
	err := row.Scan(&has_pending_plan_cross_check)
	return has_pending_plan_cross_check, err
}

const lockWorkerRecoveryParents = `-- name: LockWorkerRecoveryParents :many
WITH candidates AS MATERIALIZED (
    SELECT r.id, r.kind, r.target_run_id, r.worker_id, r.claim_generation, r.user_id
    FROM runs r
    JOIN workers w ON w.id = r.worker_id AND w.user_id = r.user_id
    WHERE r.worker_id = $1
      AND (
          r.status IN ('claimed', 'running', 'awaiting_approval', 'awaiting_input', 'awaiting_followup')
          OR r.id = ANY($2::uuid[])
          OR (r.id = ANY($3::uuid[])
              AND r.claim_generation = ($4::bigint[])[
                  array_position($3::uuid[], r.id)])
      )
), frozen_targets AS MATERIALIZED (
    SELECT c.id, c.kind, c.target_run_id, c.worker_id, c.claim_generation,
           cc.id AS cross_check_id, parent.id AS parent_lead_id
    FROM candidates c
    LEFT JOIN cross_checks cc ON c.kind = 'cross_check' AND cc.checker_run_id = c.id
    -- cross_checks is authoritative even if target_run_id disagrees. Preserve both
    -- fields so a later phase can fence that disagreement or a changed association.
    LEFT JOIN runs parent ON parent.id = CASE WHEN c.kind = 'cross_check'
        THEN cc.lead_run_id ELSE c.id END
        AND parent.kind <> 'cross_check' AND parent.user_id = c.user_id
), locked_parents AS MATERIALIZED (
    SELECT parent.id FROM runs parent
    WHERE parent.id IN (SELECT parent_lead_id FROM frozen_targets)
      AND parent.kind <> 'cross_check'
    ORDER BY parent.id
    FOR UPDATE OF parent
), parent_lock_set AS MATERIALIZED (
    -- The aggregate drains the entire ordered lock CTE, including with no targets.
    SELECT COALESCE(array_agg(id ORDER BY id), ARRAY[]::uuid[])::uuid[] AS locked_parent_ids
    FROM locked_parents
)
SELECT target.id, target.kind, target.target_run_id, target.worker_id,
       target.claim_generation, target.cross_check_id, target.parent_lead_id,
       -- Return the parent set once, avoiding targets × parents output growth.
       CASE WHEN row_number() OVER (ORDER BY target.id, target.cross_check_id) = 1
           THEN locks.locked_parent_ids ELSE ARRAY[]::uuid[] END AS locked_parent_ids
FROM parent_lock_set locks CROSS JOIN frozen_targets target
ORDER BY target.id, target.cross_check_id
`

type LockWorkerRecoveryParentsParams struct {
	WorkerID                 pgtype.UUID `json:"worker_id"`
	SnapshotRunIds           []uuid.UUID `json:"snapshot_run_ids"`
	AttestedRunIds           []uuid.UUID `json:"attested_run_ids"`
	AttestedClaimGenerations []int64     `json:"attested_claim_generations"`
}

type LockWorkerRecoveryParentsRow struct {
	ID              uuid.UUID   `json:"id"`
	Kind            string      `json:"kind"`
	TargetRunID     pgtype.UUID `json:"target_run_id"`
	WorkerID        pgtype.UUID `json:"worker_id"`
	ClaimGeneration int64       `json:"claim_generation"`
	CrossCheckID    pgtype.UUID `json:"cross_check_id"`
	ParentLeadID    pgtype.UUID `json:"parent_lead_id"`
	LockedParentIds []uuid.UUID `json:"locked_parent_ids"`
}

// Internal transaction seam: the caller holds the worker row before this query.
// Freeze the conservative union before snapshot replacement can clear leases.
// Phase-specific custody, lease, overflow and budget guards belong to later writes.
// No checker or cross_checks row is locked here, and no recovery is performed.
func (q *Queries) LockWorkerRecoveryParents(ctx context.Context, arg LockWorkerRecoveryParentsParams) ([]LockWorkerRecoveryParentsRow, error) {
	rows, err := q.db.Query(ctx, lockWorkerRecoveryParents,
		arg.WorkerID,
		arg.SnapshotRunIds,
		arg.AttestedRunIds,
		arg.AttestedClaimGenerations,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockWorkerRecoveryParentsRow{}
	for rows.Next() {
		var i LockWorkerRecoveryParentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.TargetRunID,
			&i.WorkerID,
			&i.ClaimGeneration,
			&i.CrossCheckID,
			&i.ParentLeadID,
			&i.LockedParentIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
