// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_storage_health.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recoveryStorageHealth = `-- name: RecoveryStorageHealth :many
WITH contributions AS (
  SELECT c.user_id,
    (CASE WHEN c.state = 'available' THEN 1 ELSE 0 END)::bigint AS available_count,
    (CASE WHEN c.state = 'available' THEN COALESCE(c.byte_size, 0) ELSE 0 END)::bigint AS available_bytes,
    (CASE WHEN c.state = 'preparing' THEN 1 ELSE 0 END)::bigint AS preparing_count,
    (CASE WHEN c.state = 'preparing' THEN COALESCE(c.reserved_bytes, 0) ELSE 0 END)::bigint AS preparing_bytes,
    (CASE WHEN c.state = 'uploading' THEN 1 ELSE 0 END)::bigint AS uploading_count,
    (CASE WHEN c.state = 'uploading' THEN COALESCE(c.reserved_bytes, 0) ELSE 0 END)::bigint AS uploading_bytes,
    0::bigint AS job_count, 0::bigint AS job_bytes, 0::bigint AS reclaimable_bytes,
    (CASE WHEN c.state = 'needs_action' AND c.reason = 'storage quota exceeded' THEN 1 ELSE 0 END)::bigint AS refused_count
  FROM recovery_captures c
  WHERE c.state IN ('available', 'preparing', 'uploading')
     OR (c.state = 'needs_action' AND c.reason = 'storage quota exceeded')
  UNION ALL
  SELECT f.user_id, 0, 0, 0, 0, 0, 0, 1, f.byte_size,
    CASE WHEN (f.state IN ('unattached', 'available') AND f.expires_at IS NOT NULL AND f.expires_at < $1::timestamptz)
                OR f.state = 'available' THEN f.byte_size ELSE 0 END, 0
  FROM job_files f WHERE f.state <> 'expired'
), owners AS (
  SELECT user_id,
    sum(available_count)::bigint AS available_count, sum(available_bytes)::bigint AS available_bytes,
    sum(preparing_count)::bigint AS preparing_count, sum(preparing_bytes)::bigint AS preparing_bytes,
    sum(uploading_count)::bigint AS uploading_count, sum(uploading_bytes)::bigint AS uploading_bytes,
    sum(job_count)::bigint AS job_count, sum(job_bytes)::bigint AS job_bytes,
    sum(reclaimable_bytes)::bigint AS reclaimable_bytes, sum(refused_count)::bigint AS refused_count
  FROM contributions GROUP BY user_id
), totals AS (
  SELECT count(*)::bigint AS owner_count,
    COALESCE(sum(available_count), 0)::bigint AS available_count,
    COALESCE(sum(available_bytes), 0)::bigint AS available_bytes,
    COALESCE(sum(preparing_count), 0)::bigint AS preparing_count,
    COALESCE(sum(preparing_bytes), 0)::bigint AS preparing_bytes,
    COALESCE(sum(uploading_count), 0)::bigint AS uploading_count,
    COALESCE(sum(uploading_bytes), 0)::bigint AS uploading_bytes,
    COALESCE(sum(job_count), 0)::bigint AS job_count,
    COALESCE(sum(job_bytes), 0)::bigint AS job_bytes,
    COALESCE(sum(reclaimable_bytes), 0)::bigint AS reclaimable_bytes,
    COALESCE(sum(refused_count), 0)::bigint AS refused_count
  FROM owners
), examples AS (
  SELECT user_id, available_count, available_bytes, preparing_count, preparing_bytes, uploading_count, uploading_bytes, job_count, job_bytes, reclaimable_bytes, refused_count FROM owners ORDER BY refused_count DESC, user_id LIMIT $2::int
)
SELECT t.owner_count, t.available_count, t.available_bytes, t.preparing_count, t.preparing_bytes, t.uploading_count, t.uploading_bytes, t.job_count, t.job_bytes, t.reclaimable_bytes, t.refused_count, GREATEST(t.owner_count - (SELECT count(*) FROM examples), 0)::bigint AS omitted_count,
  e.user_id AS owner_id,
  COALESCE(e.available_count, 0)::bigint AS owner_available_count,
  COALESCE(e.available_bytes, 0)::bigint AS owner_available_bytes,
  COALESCE(e.preparing_count, 0)::bigint AS owner_preparing_count,
  COALESCE(e.preparing_bytes, 0)::bigint AS owner_preparing_bytes,
  COALESCE(e.uploading_count, 0)::bigint AS owner_uploading_count,
  COALESCE(e.uploading_bytes, 0)::bigint AS owner_uploading_bytes,
  COALESCE(e.job_count, 0)::bigint AS owner_job_count,
  COALESCE(e.job_bytes, 0)::bigint AS owner_job_bytes,
  COALESCE(e.reclaimable_bytes, 0)::bigint AS owner_reclaimable_bytes,
  COALESCE(e.refused_count, 0)::bigint AS owner_refused_count
FROM totals t LEFT JOIN examples e ON true
ORDER BY e.refused_count DESC, e.user_id
`

type RecoveryStorageHealthParams struct {
	Now          pgtype.Timestamptz `json:"now"`
	ExampleLimit int32              `json:"example_limit"`
}

type RecoveryStorageHealthRow struct {
	OwnerCount            int64       `json:"owner_count"`
	AvailableCount        int64       `json:"available_count"`
	AvailableBytes        int64       `json:"available_bytes"`
	PreparingCount        int64       `json:"preparing_count"`
	PreparingBytes        int64       `json:"preparing_bytes"`
	UploadingCount        int64       `json:"uploading_count"`
	UploadingBytes        int64       `json:"uploading_bytes"`
	JobCount              int64       `json:"job_count"`
	JobBytes              int64       `json:"job_bytes"`
	ReclaimableBytes      int64       `json:"reclaimable_bytes"`
	RefusedCount          int64       `json:"refused_count"`
	OmittedCount          int64       `json:"omitted_count"`
	OwnerID               pgtype.UUID `json:"owner_id"`
	OwnerAvailableCount   int64       `json:"owner_available_count"`
	OwnerAvailableBytes   int64       `json:"owner_available_bytes"`
	OwnerPreparingCount   int64       `json:"owner_preparing_count"`
	OwnerPreparingBytes   int64       `json:"owner_preparing_bytes"`
	OwnerUploadingCount   int64       `json:"owner_uploading_count"`
	OwnerUploadingBytes   int64       `json:"owner_uploading_bytes"`
	OwnerJobCount         int64       `json:"owner_job_count"`
	OwnerJobBytes         int64       `json:"owner_job_bytes"`
	OwnerReclaimableBytes int64       `json:"owner_reclaimable_bytes"`
	OwnerRefusedCount     int64       `json:"owner_refused_count"`
}

// One snapshot for all accounting; owner examples are limited only after totals.
// Custody state does not affect stored quota refusals or byte accounting.
func (q *Queries) RecoveryStorageHealth(ctx context.Context, arg RecoveryStorageHealthParams) ([]RecoveryStorageHealthRow, error) {
	rows, err := q.db.Query(ctx, recoveryStorageHealth, arg.Now, arg.ExampleLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryStorageHealthRow{}
	for rows.Next() {
		var i RecoveryStorageHealthRow
		if err := rows.Scan(
			&i.OwnerCount,
			&i.AvailableCount,
			&i.AvailableBytes,
			&i.PreparingCount,
			&i.PreparingBytes,
			&i.UploadingCount,
			&i.UploadingBytes,
			&i.JobCount,
			&i.JobBytes,
			&i.ReclaimableBytes,
			&i.RefusedCount,
			&i.OmittedCount,
			&i.OwnerID,
			&i.OwnerAvailableCount,
			&i.OwnerAvailableBytes,
			&i.OwnerPreparingCount,
			&i.OwnerPreparingBytes,
			&i.OwnerUploadingCount,
			&i.OwnerUploadingBytes,
			&i.OwnerJobCount,
			&i.OwnerJobBytes,
			&i.OwnerReclaimableBytes,
			&i.OwnerRefusedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
