// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindCaptureManifest = `-- name: BindCaptureManifest :one

UPDATE recovery_captures
SET manifest_bound = true,
    byte_size = $1,
    checksum = $2,
    chunk_count = $3,
    prerequisite_shas = $4,
    updated_at = now()
WHERE id = $5
  AND (manifest_bound = false OR (byte_size = $1 AND checksum = $2))
RETURNING id, hold_id, run_id, user_id, original_worker_id, original_worker_identity, source_sha, attempted_head_sha, idempotency_key, state, manifest_bound, byte_size, checksum, chunk_count, prerequisite_shas, reason, context, expires_at, created_at, updated_at
`

type BindCaptureManifestParams struct {
	ByteSize         pgtype.Int8 `json:"byte_size"`
	Checksum         pgtype.Text `json:"checksum"`
	ChunkCount       pgtype.Int4 `json:"chunk_count"`
	PrerequisiteShas []string    `json:"prerequisite_shas"`
	ID               uuid.UUID   `json:"id"`
}

// PRD #1296 M1 (D2/D4/D5): the durable-recovery store contract. These queries are the
// COMPLETE store-query layer M2 (upload/owner API), M3 (worker capture/retry) and M5
// (owner UX) consume, frozen here so those parallel milestones never edit this file.
// Custody holds are opened atomically with the claim (runtime.sql ClaimRun); everything
// below operates on the already-open hold and its captures.
// D2/D4: compare-and-set the byte manifest ONCE. The first bind (manifest_bound=false)
// always wins; a retry with the SAME byte_size+checksum is idempotent (the second
// disjunct matches and re-stamps updated_at); a DIFFERENT manifest under the same
// capture_id matches neither disjunct and returns zero rows (a conflict the caller must
// surface, never an overwrite of bound bytes). Manifest size/checksum/prerequisites need
// not exist at reserve time; this binds them before chunks are accepted.
func (q *Queries) BindCaptureManifest(ctx context.Context, arg BindCaptureManifestParams) (RecoveryCapture, error) {
	row := q.db.QueryRow(ctx, bindCaptureManifest,
		arg.ByteSize,
		arg.Checksum,
		arg.ChunkCount,
		arg.PrerequisiteShas,
		arg.ID,
	)
	var i RecoveryCapture
	err := row.Scan(
		&i.ID,
		&i.HoldID,
		&i.RunID,
		&i.UserID,
		&i.OriginalWorkerID,
		&i.OriginalWorkerIdentity,
		&i.SourceSha,
		&i.AttemptedHeadSha,
		&i.IdempotencyKey,
		&i.State,
		&i.ManifestBound,
		&i.ByteSize,
		&i.Checksum,
		&i.ChunkCount,
		&i.PrerequisiteShas,
		&i.Reason,
		&i.Context,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimCustodyEpisodeNotice = `-- name: ClaimCustodyEpisodeNotice :one
INSERT INTO custody_episode_notices (user_id, notified_at)
VALUES ($1, now())
ON CONFLICT (user_id) DO NOTHING
RETURNING user_id
`

// PRD #1349 M1 (D10): atomically claim the one-per-episode owner Slack DM slot, mirroring
// ClaimVaultLockNotice. Backed by the additive custody_episode_notices table (migration 00226):
// the FIRST caller to observe a blocked-custody episode for a user INSERTs the row and gets it
// back; a concurrent second caller conflicts on the user_id PK, DO NOTHING returns no row
// (pgx.ErrNoRows), so N api pods send EXACTLY ONE DM per episode (at-most-once dedup, the mark
// is set before Notify runs). ClearCustodyEpisodeNotice re-arms it when the owner drops below
// the limit, so a later crossing can notify afresh.
func (q *Queries) ClaimCustodyEpisodeNotice(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimCustodyEpisodeNotice, userID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const clearCustodyEpisodeNotice = `-- name: ClearCustodyEpisodeNotice :exec
DELETE FROM custody_episode_notices WHERE user_id = $1
`

// PRD #1349 M1 (D10): re-arm the owner custody-episode notice by dropping the mark, mirroring
// ClearVaultLockNotice. Called when the owner falls back below the custody-admission limit
// (the episode closes), so a later re-crossing sends a fresh DM. Idempotent: a delete of a
// missing row is a no-op.
func (q *Queries) ClearCustodyEpisodeNotice(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCustodyEpisodeNotice, userID)
	return err
}

const countOpenCustodyHoldsForWorker = `-- name: CountOpenCustodyHoldsForWorker :one
SELECT count(*) FROM recovery_custody_holds
WHERE live_worker_id = $1::uuid AND user_id = $2 AND state = 'open'
`

type CountOpenCustodyHoldsForWorkerParams struct {
	WorkerID uuid.UUID `json:"worker_id"`
	UserID   uuid.UUID `json:"user_id"`
}

// PRD #1296 M4 (D3): the DeleteWorker custody guard's predicate — how many OPEN custody
// holds name this worker as their LIVE holder. Non-zero refuses the delete (deleting the
// worker cascades hosted_worker_tokens, and a preauthorized upload may still need that
// token to authenticate), so the caller surfaces the count of affected captures and
// requires an explicit discard decision before the source's last authenticated retry path
// is destroyed. Reads the same live_worker_id FK the M4 teardown DELETE skip predicate does.
// OWNER-SCOPED (@user_id): the hold carries user_id, and DeleteWorker runs this BEFORE the
// owner-scoped DeleteWorkerForUser, so without the owner filter a FOREIGN owner's held worker
// would return a non-zero count and leak its existence + hold count as a 409 instead of the
// 404 every other sibling ownership check yields. A non-owner therefore counts 0 and falls
// through to the 404 (ErrWorkerNotFound) path.
func (q *Queries) CountOpenCustodyHoldsForWorker(ctx context.Context, arg CountOpenCustodyHoldsForWorkerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenCustodyHoldsForWorker, arg.WorkerID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const discardCaptureForOwner = `-- name: DiscardCaptureForOwner :execrows
WITH owned AS (
    SELECT rc.id AS capture_id FROM recovery_captures rc
    WHERE rc.id = $1 AND rc.run_id = $2 AND rc.user_id = $3
),
del AS (
    DELETE FROM recovery_capture_chunks
    WHERE capture_id IN (SELECT owned.capture_id FROM owned)
)
UPDATE recovery_captures c
SET state = 'discarded', updated_at = now()
WHERE c.id = $1 AND c.run_id = $2 AND c.user_id = $3
`

type DiscardCaptureForOwnerParams struct {
	ID     uuid.UUID `json:"id"`
	RunID  uuid.UUID `json:"run_id"`
	UserID uuid.UUID `json:"user_id"`
}

// D7: owner-initiated explicit discard of one capture. Deletes its byte chunks (freeing
// storage) and marks the capture 'discarded' in ONE statement — the data-modifying del CTE
// always runs to completion, and :execrows reports the capture UPDATE's row count (1 when
// owned, 0 for a foreign/absent id). The capture row is retained (audit), only its bytes go.
func (q *Queries) DiscardCaptureForOwner(ctx context.Context, arg DiscardCaptureForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, discardCaptureForOwner, arg.ID, arg.RunID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const discardCustodyHoldForOwner = `-- name: DiscardCustodyHoldForOwner :execrows
UPDATE recovery_custody_holds
SET state = 'discarded', live_worker_id = NULL, live_run_id = NULL,
    release_evidence = $1, updated_at = now()
WHERE id = $2 AND run_id = $3 AND user_id = $4 AND state = 'open'
`

type DiscardCustodyHoldForOwnerParams struct {
	ReleaseEvidence pgtype.Text `json:"release_evidence"`
	HoldID          uuid.UUID   `json:"hold_id"`
	RunID           uuid.UUID   `json:"run_id"`
	UserID          uuid.UUID   `json:"user_id"`
}

// PRD #1349 M1 (D7): owner-initiated EXACT hold discard. Marks the ONE named open hold
// 'discarded' and nulls its live worker/run FKs (dropping the ON DELETE RESTRICT so ordinary
// teardown can proceed), leaving the immutable provenance columns intact for audit. OWNER
// SCOPE IS VERIFIED IN THE SQL (user_id = @user_id) in ADDITION to the handler's owner-or-404
// gate, and the run/hold identity (run_id + id) is matched, so a foreign owner or a wrong
// run/hold id settles zero rows. state='open' makes discard terminal + idempotent: a second
// call, or a hold already released/discarded, moves zero rows and can never revive it.
// Captures are settled separately (DiscardNonReadyCapturesForHold); an available archive is
// NEVER touched here (archive deletion is a distinct owner choice, D7). Sibling holds and
// generations are left untouched.
//
// PRD #1392 M1 (D3): release_evidence is stamped 'owner_discard' — the class recording that
// the owner explicitly discarded this hold's custody. The caller passes it as @release_evidence;
// CHECK-constrained to the five classes (migration 00232).
func (q *Queries) DiscardCustodyHoldForOwner(ctx context.Context, arg DiscardCustodyHoldForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, discardCustodyHoldForOwner,
		arg.ReleaseEvidence,
		arg.HoldID,
		arg.RunID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const discardNonReadyCapturesForHold = `-- name: DiscardNonReadyCapturesForHold :execrows
WITH targets AS (
    SELECT rc.id AS capture_id FROM recovery_captures rc
    WHERE rc.hold_id = $1
      AND rc.state IN ('preparing', 'uploading', 'needs_action')
),
del AS (
    DELETE FROM recovery_capture_chunks
    WHERE capture_id IN (SELECT targets.capture_id FROM targets)
)
UPDATE recovery_captures c
SET state = 'discarded', updated_at = now()
WHERE c.id IN (SELECT targets.capture_id FROM targets)
`

// PRD #1349 M1 (D7): the capture-settlement half of an owner hold discard. For ONE hold, marks
// its preparing/uploading/needs_action captures 'discarded' and deletes their partial byte
// chunks, NEVER touching an 'available' (ready) capture — a ready archive survives a hold
// discard so the owner can still export it (D7/D9). Ordered exactly like DiscardCaptureForOwner
// so the whole thing is ONE atomic statement: `targets` SELECTs the non-ready capture ids under
// one snapshot, `del` deletes their chunks, and the final UPDATE flips exactly those ids to
// 'discarded'. Because every CTE reads that same snapshot, a partially-settled capture can never
// leave orphan chunks or a chunk-less non-terminal row, and :execrows reports the capture
// UPDATE's row count (not the chunk deletes'). The caller runs this in the SAME transaction as
// DiscardCustodyHoldForOwner, locking hold then captures in upload order (D7).
func (q *Queries) DiscardNonReadyCapturesForHold(ctx context.Context, holdID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, discardNonReadyCapturesForHold, holdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireReadyCaptures = `-- name: ExpireReadyCaptures :execrows
WITH expiring AS (
    SELECT rc.id AS capture_id FROM recovery_captures rc
    WHERE rc.state = 'available' AND rc.expires_at IS NOT NULL AND rc.expires_at < $1
),
del AS (
    DELETE FROM recovery_capture_chunks
    WHERE capture_id IN (SELECT expiring.capture_id FROM expiring)
)
UPDATE recovery_captures c
SET state = 'expired', updated_at = now()
WHERE c.id IN (SELECT expiring.capture_id FROM expiring)
`

// D4: the retention-enforcement sweep. Moves 'available' captures past their expires_at to
// 'expired' AND reclaims their bytes — the encrypted chunk rows of the expired captures are
// deleted in the SAME statement, so a capture past its retention window no longer costs the
// instance/owner byte storage. Scoped to available+expired-at-past so it NEVER touches an open
// hold, a pending (preparing/uploading) capture, or a needs_action capture — a ready
// artifact's TTL must not expire uncaptured custody. The capture METADATA row is kept in state
// 'expired' (audit + an honest owner-visible state); only its bytes go.
//
// Ordered exactly like DiscardCaptureForOwner so the whole thing is ONE atomic statement:
// `expiring` SELECTs the target ids under one snapshot, `del` deletes their chunks, and the
// final UPDATE flips exactly those ids to 'expired'. Because every CTE reads that same
// snapshot, a partially-expired capture can never leave orphan chunks or a chunk-less
// 'available' row, and :execrows reports the capture UPDATE's row count (not the chunk
// deletes'). Custody is NEVER touched — expiry is a capture-artifact operation, never a custody
// release (an expired capture whose hold is still open stays retained per D3).
func (q *Queries) ExpireReadyCaptures(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, expireReadyCaptures, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireStalledUploads = `-- name: ExpireStalledUploads :execrows
UPDATE recovery_captures
SET state = 'needs_action', reason = 'upload_retry_window_exhausted', updated_at = now()
WHERE state IN ('preparing', 'uploading')
  AND created_at < now() - $1::interval
`

// PRD #1296 D3/D4: the upload-retry-window sweep — the LIVE consumer of
// UZI_RECOVERY_UPLOAD_RETRY_WINDOW. A healthy upload advances a reserved capture from
// 'preparing' to 'available' within seconds, so a capture still in a NON-TERMINAL upload
// state (preparing/uploading) whose reserve time is older than the operator's window has
// genuinely stalled. created_at is the reserve anchor (the upload never restamps it), so a
// capture unreserved-to-ready for longer than the window is the stall this surfaces. It flips
// the capture to 'needs_action' with a specific reason so the owner sees a retain-and-decide
// artifact, stamping updated_at.
//
// RETAINS THE SOURCE (D3): needs_action is a NON-RELEASING state and this query NEVER touches
// the custody hold, so the last copy is held until capture succeeds or the owner explicitly
// discards — ListReleasableCustodyHolds does not qualify a needs_action-only hold. Scoped to
// the two non-terminal upload states so it NEVER touches an available/expired/discarded/
// already-needs_action capture. The caller DISABLES this pass when the window is non-positive
// (the sweep's >0 guard); the query itself is always time-bounded by @retry_window.
func (q *Queries) ExpireStalledUploads(ctx context.Context, retryWindow pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, expireStalledUploads, retryWindow)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCaptureForOwner = `-- name: GetCaptureForOwner :one
SELECT id, hold_id, run_id, user_id, original_worker_id, original_worker_identity, source_sha, attempted_head_sha, idempotency_key, state, manifest_bound, byte_size, checksum, chunk_count, prerequisite_shas, reason, context, expires_at, created_at, updated_at FROM recovery_captures
WHERE id = $1 AND run_id = $2 AND user_id = $3
`

type GetCaptureForOwnerParams struct {
	ID     uuid.UUID `json:"id"`
	RunID  uuid.UUID `json:"run_id"`
	UserID uuid.UUID `json:"user_id"`
}

// D6: strict owner-scoped by-id read of one capture. The (id, run_id, user_id) triple is
// the owner-authorization seam every metadata/download path funnels through — an admin
// viewing a foreign run is refused because user_id will not match.
func (q *Queries) GetCaptureForOwner(ctx context.Context, arg GetCaptureForOwnerParams) (RecoveryCapture, error) {
	row := q.db.QueryRow(ctx, getCaptureForOwner, arg.ID, arg.RunID, arg.UserID)
	var i RecoveryCapture
	err := row.Scan(
		&i.ID,
		&i.HoldID,
		&i.RunID,
		&i.UserID,
		&i.OriginalWorkerID,
		&i.OriginalWorkerIdentity,
		&i.SourceSha,
		&i.AttemptedHeadSha,
		&i.IdempotencyKey,
		&i.State,
		&i.ManifestBound,
		&i.ByteSize,
		&i.Checksum,
		&i.ChunkCount,
		&i.PrerequisiteShas,
		&i.Reason,
		&i.Context,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustodyAggregateForOwner = `-- name: GetCustodyAggregateForOwner :one
SELECT
    (SELECT count(*) FROM recovery_custody_holds h
        WHERE h.user_id = $1::uuid AND h.state = 'open')::bigint AS open_holds,
    (CASE
        WHEN $2::int > 0
             AND (SELECT count(*) FROM recovery_custody_holds h2
                    WHERE h2.user_id = $1::uuid AND h2.state = 'open') >= $2::int
        THEN (SELECT count(*) FROM runs r
                WHERE r.user_id = $1::uuid
                  AND r.status = 'queued'
                  AND r.kind IN ('issue', 'ci_fix', 'self_improve', 'prompt', 'task', 'mr_rework'))
        ELSE 0
     END)::bigint AS blocked_runs
`

type GetCustodyAggregateForOwnerParams struct {
	UserID           uuid.UUID `json:"user_id"`
	CustodyHoldLimit int32     `json:"custody_hold_limit"`
}

type GetCustodyAggregateForOwnerRow struct {
	OpenHolds   int64 `json:"open_holds"`
	BlockedRuns int64 `json:"blocked_runs"`
}

// PRD #1349 M1 (D6/D10): the owner-level custody aggregate the board alert and one-per-episode
// Slack DM read (M6). open_holds is the owner's UNRESOLVED (state='open') hold count — the SAME
// admission signal ClaimRun blocks on. blocked_runs is the count of the owner's QUEUED
// code-publishing runs currently blocked by the custody-admission predicate: it mirrors the
// reasonCustodyLimit predicate in workersvc/health.go — a run stays queued for custody ONLY when
// the owner is AT/OVER the limit — so it is 0 unless open_holds >= @custody_hold_limit (and a
// non-positive @custody_hold_limit DISABLES the gate exactly like the claim path, yielding 0).
// The code-publishing kinds match ClaimRun's custody-hold CTE (issue/ci_fix/self_improve/prompt/
// task/mr_rework). Both columns are cast ::bigint so sqlc types them as int64, never interface{}.
// Every column is table-qualified and @user_id carries an explicit ::uuid cast: this is a
// top-level SELECT with no FROM, so sqlc's param-type inference cannot pick a single relation
// for an untyped @user_id when both recovery_custody_holds and runs expose a user_id column
// (it reports "column reference user_id is ambiguous"). The cast types the param directly.
func (q *Queries) GetCustodyAggregateForOwner(ctx context.Context, arg GetCustodyAggregateForOwnerParams) (GetCustodyAggregateForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getCustodyAggregateForOwner, arg.UserID, arg.CustodyHoldLimit)
	var i GetCustodyAggregateForOwnerRow
	err := row.Scan(&i.OpenHolds, &i.BlockedRuns)
	return i, err
}

const getRecoverySummaryForRun = `-- name: GetRecoverySummaryForRun :one
SELECT
    (EXISTS (SELECT 1 FROM recovery_custody_holds h
        WHERE h.run_id = $1 AND h.user_id = $2))::boolean AS supported,
    (EXISTS (SELECT 1 FROM recovery_custody_holds h
        WHERE h.run_id = $1 AND h.user_id = $2 AND h.state = 'open'))::boolean AS has_open_hold,
    count(c.id) AS capture_count,
    count(*) FILTER (WHERE c.state = 'preparing') AS preparing_count,
    count(*) FILTER (WHERE c.state = 'uploading') AS uploading_count,
    count(*) FILTER (WHERE c.state = 'available') AS available_count,
    count(*) FILTER (WHERE c.state = 'needs_action') AS needs_action_count,
    count(*) FILTER (WHERE c.state = 'expired') AS expired_count,
    count(*) FILTER (WHERE c.state = 'discarded') AS discarded_count
FROM recovery_captures c
WHERE c.run_id = $1 AND c.user_id = $2
`

type GetRecoverySummaryForRunParams struct {
	RunID  uuid.UUID `json:"run_id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetRecoverySummaryForRunRow struct {
	Supported        bool  `json:"supported"`
	HasOpenHold      bool  `json:"has_open_hold"`
	CaptureCount     int64 `json:"capture_count"`
	PreparingCount   int64 `json:"preparing_count"`
	UploadingCount   int64 `json:"uploading_count"`
	AvailableCount   int64 `json:"available_count"`
	NeedsActionCount int64 `json:"needs_action_count"`
	ExpiredCount     int64 `json:"expired_count"`
	DiscardedCount   int64 `json:"discarded_count"`
}

// D7: the per-run recovery aggregate, returning ONE row even when the run has zero
// captures (aggregate query over recovery_captures = single group). `supported` is true
// iff any custody hold ever existed for the run (a hold means a recovery-capable worker
// claimed it; its absence is the legacy/unsupported case M5 renders honestly).
// `has_open_hold` is the pending-custody signal. The per-state counts let M5 render the
// section without gating on captures.length>=1. The EXISTS results are cast to boolean so
// sqlc types them as usable bools (an uncast EXISTS types as interface{}).
func (q *Queries) GetRecoverySummaryForRun(ctx context.Context, arg GetRecoverySummaryForRunParams) (GetRecoverySummaryForRunRow, error) {
	row := q.db.QueryRow(ctx, getRecoverySummaryForRun, arg.RunID, arg.UserID)
	var i GetRecoverySummaryForRunRow
	err := row.Scan(
		&i.Supported,
		&i.HasOpenHold,
		&i.CaptureCount,
		&i.PreparingCount,
		&i.UploadingCount,
		&i.AvailableCount,
		&i.NeedsActionCount,
		&i.ExpiredCount,
		&i.DiscardedCount,
	)
	return i, err
}

const insertCaptureChunk = `-- name: InsertCaptureChunk :exec
INSERT INTO recovery_capture_chunks (capture_id, chunk_index, length, sealed)
VALUES ($1, $2, $3, $4)
`

type InsertCaptureChunkParams struct {
	CaptureID  uuid.UUID `json:"capture_id"`
	ChunkIndex int32     `json:"chunk_index"`
	Length     int32     `json:"length"`
	Sealed     []byte    `json:"sealed"`
}

// D4: one ordered, AAD-sealed byte chunk. Inserted inside the single bounded upload
// transaction M2 owns, alongside the ready transition, so chunks and ready become durable
// together. sealed is the ciphertext; length is the plaintext byte count for that chunk.
func (q *Queries) InsertCaptureChunk(ctx context.Context, arg InsertCaptureChunkParams) error {
	_, err := q.db.Exec(ctx, insertCaptureChunk,
		arg.CaptureID,
		arg.ChunkIndex,
		arg.Length,
		arg.Sealed,
	)
	return err
}

const listCaptureChunks = `-- name: ListCaptureChunks :many
SELECT capture_id, chunk_index, length, sealed
FROM recovery_capture_chunks
WHERE capture_id = $1
ORDER BY chunk_index
`

// D4: the ordered chunk inventory for a download stream. The caller reads chunks in
// chunk_index order, decrypts each with its AAD, and streams the plaintext without
// buffering the whole bundle. Owner authorization is enforced upstream by
// GetCaptureForOwner before this read.
func (q *Queries) ListCaptureChunks(ctx context.Context, captureID uuid.UUID) ([]RecoveryCaptureChunk, error) {
	rows, err := q.db.Query(ctx, listCaptureChunks, captureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryCaptureChunk{}
	for rows.Next() {
		var i RecoveryCaptureChunk
		if err := rows.Scan(
			&i.CaptureID,
			&i.ChunkIndex,
			&i.Length,
			&i.Sealed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapturesForRunOwner = `-- name: ListCapturesForRunOwner :many
SELECT id, hold_id, run_id, user_id, original_worker_id, original_worker_identity, source_sha, attempted_head_sha, idempotency_key, state, manifest_bound, byte_size, checksum, chunk_count, prerequisite_shas, reason, context, expires_at, created_at, updated_at FROM recovery_captures
WHERE run_id = $1 AND user_id = $2
ORDER BY created_at
`

type ListCapturesForRunOwnerParams struct {
	RunID  uuid.UUID `json:"run_id"`
	UserID uuid.UUID `json:"user_id"`
}

// D7: every retained capture for one run, owner-scoped, oldest-first. Feeds the run's
// Recovery archives section (all states shown, not gated on availability).
func (q *Queries) ListCapturesForRunOwner(ctx context.Context, arg ListCapturesForRunOwnerParams) ([]RecoveryCapture, error) {
	rows, err := q.db.Query(ctx, listCapturesForRunOwner, arg.RunID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryCapture{}
	for rows.Next() {
		var i RecoveryCapture
		if err := rows.Scan(
			&i.ID,
			&i.HoldID,
			&i.RunID,
			&i.UserID,
			&i.OriginalWorkerID,
			&i.OriginalWorkerIdentity,
			&i.SourceSha,
			&i.AttemptedHeadSha,
			&i.IdempotencyKey,
			&i.State,
			&i.ManifestBound,
			&i.ByteSize,
			&i.Checksum,
			&i.ChunkCount,
			&i.PrerequisiteShas,
			&i.Reason,
			&i.Context,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustodyHoldsForOwner = `-- name: ListCustodyHoldsForOwner :many
SELECT
    h.id,
    h.run_id,
    h.generation,
    h.state,
    h.created_at,
    h.updated_at,
    h.released_at,
    h.original_worker_id,
    COALESCE(w.name, '')::text AS worker_name,
    (EXISTS (SELECT 1 FROM recovery_captures c
        WHERE c.hold_id = h.id AND c.state = 'available'))::boolean AS has_available_capture,
    COALESCE((SELECT c.state FROM recovery_captures c
        WHERE c.hold_id = h.id
        ORDER BY c.created_at DESC, c.id DESC
        LIMIT 1), '')::text AS capture_state,
    COALESCE(r.status, '')::text AS run_status
FROM recovery_custody_holds h
LEFT JOIN workers w ON w.id = h.original_worker_id AND w.user_id = h.user_id
LEFT JOIN runs r ON r.id = h.run_id AND r.user_id = h.user_id
WHERE h.user_id = $1
  AND ($2::uuid IS NULL OR h.run_id = $2::uuid)
  AND ($3::uuid IS NULL OR h.original_worker_id = $3::uuid)
  AND ($4::text IS NULL OR h.state = $4::text)
ORDER BY h.created_at ASC
`

type ListCustodyHoldsForOwnerParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	RunID    pgtype.UUID `json:"run_id"`
	WorkerID pgtype.UUID `json:"worker_id"`
	State    pgtype.Text `json:"state"`
}

type ListCustodyHoldsForOwnerRow struct {
	ID                  uuid.UUID          `json:"id"`
	RunID               uuid.UUID          `json:"run_id"`
	Generation          int64              `json:"generation"`
	State               string             `json:"state"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ReleasedAt          pgtype.Timestamptz `json:"released_at"`
	OriginalWorkerID    uuid.UUID          `json:"original_worker_id"`
	WorkerName          string             `json:"worker_name"`
	HasAvailableCapture bool               `json:"has_available_capture"`
	CaptureState        string             `json:"capture_state"`
	RunStatus           string             `json:"run_status"`
}

// PRD #1349 M1 (D7): the owner-scoped, bounded hold list the web Workers surface and the
// `uzi run recovery` CLI render (M5/M6). OWNER-scoped by @user_id, with OPTIONAL run/worker/
// state narg filters (a NULL narg disables that filter). It returns the exact hold identity
// (id, run_id, generation), lifecycle state, timestamps, and the OPAQUE original_worker_id
// UUID, plus a BOUNDED owner-safe worker display name LEFT-JOINed from workers.name (NULL ->
// ” when the worker row is gone). It NEVER returns original_worker_identity (raw provenance,
// D7). The per-hold capture summary (has_available_capture, latest capture_state) lets the
// surface classify a hold (active protection / capture in progress / archive available /
// needs attention) without a second query.
//
// run_status is the hold's run's live status (M5, D6/D8), LEFT-JOINed from runs (NULL -> ”
// when the run row is gone). It is consumed ONLY by the Go attention derivation in
// ListHoldsForOwner to tell `active` (an OPEN hold whose run is still running/claimed —
// healthy protection, no owner decision) from `source_only` (an OPEN hold whose run is
// terminal and carries no capture — a source needing an owner decision). It is NOT added to
// the frozen RecoveryCustodyHoldDTO wire shape; it never reaches the SPA/CLI JSON. Ordered
// oldest-first for a stable list.
func (q *Queries) ListCustodyHoldsForOwner(ctx context.Context, arg ListCustodyHoldsForOwnerParams) ([]ListCustodyHoldsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listCustodyHoldsForOwner,
		arg.UserID,
		arg.RunID,
		arg.WorkerID,
		arg.State,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustodyHoldsForOwnerRow{}
	for rows.Next() {
		var i ListCustodyHoldsForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Generation,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleasedAt,
			&i.OriginalWorkerID,
			&i.WorkerName,
			&i.HasAvailableCapture,
			&i.CaptureState,
			&i.RunStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustodyHoldsForWorkerRun = `-- name: ListCustodyHoldsForWorkerRun :many
SELECT
    h.id,
    h.generation,
    (EXISTS (SELECT 1 FROM recovery_captures c
        WHERE c.hold_id = h.id AND c.state = 'available'))::boolean AS has_available_capture,
    COALESCE((SELECT c.state FROM recovery_captures c
        WHERE c.hold_id = h.id
        ORDER BY c.created_at DESC, c.id DESC
        LIMIT 1), '')::text AS capture_state
FROM recovery_custody_holds h
WHERE h.run_id = $1
  AND h.original_worker_id = $2::uuid
  AND h.state = 'open'
ORDER BY h.created_at ASC
`

type ListCustodyHoldsForWorkerRunParams struct {
	RunID    uuid.UUID `json:"run_id"`
	WorkerID uuid.UUID `json:"worker_id"`
}

type ListCustodyHoldsForWorkerRunRow struct {
	ID                  uuid.UUID `json:"id"`
	Generation          int64     `json:"generation"`
	HasAvailableCapture bool      `json:"has_available_capture"`
	CaptureState        string    `json:"capture_state"`
}

// PRD #1349 M1 (D3): the caller worker's OWN open holds on a run, for the worker-facing
// post-clone generation-exact inventory (M2). Scoped to holds this worker ORIGINALLY took
// (original_worker_id = @worker_id) so a cross-worker reclaim never sees the crashed worker's
// holds. Returns the hold id + generation plus a per-hold capture summary: has_available_capture
// (a ready archive already covers this hold's source) and capture_state (the latest capture's
// lifecycle state, ” when the hold has no capture yet). The worker uses this to decide, per
// generation, whether its source is already durable before it re-attempts capture/release.
func (q *Queries) ListCustodyHoldsForWorkerRun(ctx context.Context, arg ListCustodyHoldsForWorkerRunParams) ([]ListCustodyHoldsForWorkerRunRow, error) {
	rows, err := q.db.Query(ctx, listCustodyHoldsForWorkerRun, arg.RunID, arg.WorkerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustodyHoldsForWorkerRunRow{}
	for rows.Next() {
		var i ListCustodyHoldsForWorkerRunRow
		if err := rows.Scan(
			&i.ID,
			&i.Generation,
			&i.HasAvailableCapture,
			&i.CaptureState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnersOverCustodyLimit = `-- name: ListOwnersOverCustodyLimit :many

SELECT h.user_id
FROM recovery_custody_holds h
WHERE h.state = 'open'
GROUP BY h.user_id
HAVING count(*) >= $1::int
`

// ════════════════════════════════════════════════════════════════════════════════════════
// PRD #1349 M6: the owner custody-episode reconciler's find-owners reads. The one-per-episode
// owner Slack DM (slacksvc.CustodyEpisodeReconciler, D10) coalesces the blocked-custody crossing
// by owner, so it needs (a) the owners currently AT/OVER the admission limit to notify and
// (b) the already-notified owners who have dropped BELOW it, to re-arm (clear) their episode
// notice for a later crossing. Both key off the SAME open-hold admission signal ClaimRun and
// GetCustodyAggregateForOwner gate on. Added strictly ADDITIVELY (M1/M4/M5 queries UNTOUCHED).
// ════════════════════════════════════════════════════════════════════════════════════════
// PRD #1349 M6 (D10): the owners whose OPEN (unresolved) custody-hold count is AT/OVER the
// admission limit — the crossing set the episode reconciler considers for a one-per-episode DM.
// Grouped over the partial idx_recovery_custody_holds_owner_open index; HAVING count(*) >=
// @custody_hold_limit is the SAME predicate ClaimRun's custody-admission clause blocks on, so a
// notified owner is exactly one whose runs are (or can be) blocked. The reconciler then claims
// at-most-once and reads GetCustodyAggregateForOwner for the exact DM facts, so this returns only
// the user_id. The caller guards a non-positive @custody_hold_limit (the admission gate is then
// disabled), so this is never called with one — a non-positive limit here would match every owner.
func (q *Queries) ListOwnersOverCustodyLimit(ctx context.Context, custodyHoldLimit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOwnersOverCustodyLimit, custodyHoldLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnersWithClearedCustodyEpisode = `-- name: ListOwnersWithClearedCustodyEpisode :many
SELECT n.user_id
FROM custody_episode_notices n
WHERE (SELECT count(*) FROM recovery_custody_holds h
       WHERE h.user_id = n.user_id AND h.state = 'open') < $1::int
`

// PRD #1349 M6 (D10): the already-notified owners whose OPEN custody-hold count has dropped
// BELOW the admission limit — the episode has closed, so the reconciler clears their notice
// (ClearCustodyEpisodeNotice) to re-arm a later re-crossing. A row in custody_episode_notices
// means "already DM'd for this episode"; the correlated open-hold count mirrors the same
// admission signal, so this returns exactly the owners whose episode should re-arm. Returns only
// the user_id; the reconciler clears each.
func (q *Queries) ListOwnersWithClearedCustodyEpisode(ctx context.Context, custodyHoldLimit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOwnersWithClearedCustodyEpisode, custodyHoldLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasableCustodyHolds = `-- name: ListReleasableCustodyHolds :many
SELECT h.id, h.user_id, h.repo_id, h.run_id, h.generation, h.state, h.original_worker_id, h.original_worker_identity, h.live_worker_id, h.live_run_id, h.created_at, h.updated_at, h.released_at, h.release_evidence,
    CASE
        WHEN EXISTS (SELECT 1 FROM runs r
                       WHERE r.id = h.run_id
                         AND r.status = 'completed'
                         AND h.generation = r.claim_generation)
            THEN 'publication'
        ELSE 'archive'
    END::text AS reason
FROM recovery_custody_holds h
WHERE h.state = 'open'
  AND (
      EXISTS (SELECT 1 FROM runs r
                WHERE r.id = h.run_id
                  AND r.status = 'completed'
                  AND h.generation = r.claim_generation)
      OR EXISTS (SELECT 1 FROM recovery_captures c
                   WHERE c.hold_id = h.id AND c.state = 'available')
  )
ORDER BY h.created_at ASC
`

type ListReleasableCustodyHoldsRow struct {
	ID                     uuid.UUID          `json:"id"`
	UserID                 uuid.UUID          `json:"user_id"`
	RepoID                 pgtype.UUID        `json:"repo_id"`
	RunID                  uuid.UUID          `json:"run_id"`
	Generation             int64              `json:"generation"`
	State                  string             `json:"state"`
	OriginalWorkerID       uuid.UUID          `json:"original_worker_id"`
	OriginalWorkerIdentity string             `json:"original_worker_identity"`
	LiveWorkerID           pgtype.UUID        `json:"live_worker_id"`
	LiveRunID              pgtype.UUID        `json:"live_run_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ReleasedAt             pgtype.Timestamptz `json:"released_at"`
	ReleaseEvidence        pgtype.Text        `json:"release_evidence"`
	Reason                 string             `json:"reason"`
}

// PRD #1296 M4 (D3): the custody-release RECONCILER's candidate set — OPEN holds whose
// release is now WARRANTED but was never applied (e.g. the best-effort terminal release in
// SetState failed after a full publication, leaving the live FKs set and blocking teardown).
// Release is warranted ONLY when the recorded disposition proves THIS hold's work is durable.
//
// MULTI-HOLD HAZARD (why this is PER-HOLD and generation-aware): a run can carry MORE THAN
// ONE open hold. A cross-worker re-claim after a transient worker loss opens a second hold
// (generation 2, a different live_worker_id) while the crashed worker's generation-1 hold
// stays open and never released. Generation 2 typically reseeds from the default branch, so
// generation 1's committed work is NOT in generation 2's tree — the generation-1 hold
// protects the ONLY copy of that work. So a per-hold candidate set must never qualify an
// OLDER-generation orphan on the strength of a NEWER generation's disposition:
//
//	(a) the hold's run is 'completed' AND h.generation = r.claim_generation — only the
//	    generation that actually completed/published published its head (full publication,
//	    D3). runs.claim_generation is the LATEST generation; an older orphaned hold on the
//	    same completed run has h.generation < claim_generation and is NOT releasable via this
//	    path (its uncaptured committed work would otherwise be dropped); or
//	(b) a READY capture ('available') exists for THIS hold (c.hold_id = h.id) — the source
//	    covered by THIS hold is durably archived, which releases THIS hold's custody (D3).
//	    This is already a strict per-hold test, so a sibling hold's ready capture never
//	    qualifies it.
//
// It NEVER infers success from an arbitrary terminal status: a 'failed'/'cancelled'/future
// 'partial' run with no ready capture, and a 'running'/'queued' run, are excluded (a failed
// run retains custody for capture/discard). Returns oldest-first for stable reconcile order;
// the reconciler releases the SPECIFIC selected hold by id (ReleaseCustodyHold), so selection
// and release agree per-hold and a sibling hold is never collaterally released.
//
// PRD #1392 M1 (D3): `reason` is the per-hold RELEASE-EVIDENCE class the reconciler stamps
// when it releases this hold, so the stored evidence matches the qualifier that selected it:
// 'publication' when the completed-run backstop (a) qualifies it (the generation that
// published its head), else 'archive' (its source is durably captured). The CASE mirrors the
// WHERE's two disjuncts and prefers publication when both hold; a selected hold always
// satisfies at least one disjunct, so `reason` is never a spurious 'archive' on a hold that
// only the completed backstop qualified.
func (q *Queries) ListReleasableCustodyHolds(ctx context.Context) ([]ListReleasableCustodyHoldsRow, error) {
	rows, err := q.db.Query(ctx, listReleasableCustodyHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleasableCustodyHoldsRow{}
	for rows.Next() {
		var i ListReleasableCustodyHoldsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoID,
			&i.RunID,
			&i.Generation,
			&i.State,
			&i.OriginalWorkerID,
			&i.OriginalWorkerIdentity,
			&i.LiveWorkerID,
			&i.LiveRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleasedAt,
			&i.ReleaseEvidence,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCaptureReady = `-- name: MarkCaptureReady :one
UPDATE recovery_captures
SET state = 'available', expires_at = $1, updated_at = now()
WHERE id = $2 AND manifest_bound = true
RETURNING id, hold_id, run_id, user_id, original_worker_id, original_worker_identity, source_sha, attempted_head_sha, idempotency_key, state, manifest_bound, byte_size, checksum, chunk_count, prerequisite_shas, reason, context, expires_at, created_at, updated_at
`

type MarkCaptureReadyParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	ID        uuid.UUID          `json:"id"`
}

// D4: the atomic ready transition to 'available', stamping the expiry that begins at
// durable capture (never at the earlier reservation). Gated on a bound manifest so a
// capture can never be advertised ready without its verified byte identity (returns zero
// rows otherwise).
func (q *Queries) MarkCaptureReady(ctx context.Context, arg MarkCaptureReadyParams) (RecoveryCapture, error) {
	row := q.db.QueryRow(ctx, markCaptureReady, arg.ExpiresAt, arg.ID)
	var i RecoveryCapture
	err := row.Scan(
		&i.ID,
		&i.HoldID,
		&i.RunID,
		&i.UserID,
		&i.OriginalWorkerID,
		&i.OriginalWorkerIdentity,
		&i.SourceSha,
		&i.AttemptedHeadSha,
		&i.IdempotencyKey,
		&i.State,
		&i.ManifestBound,
		&i.ByteSize,
		&i.Checksum,
		&i.ChunkCount,
		&i.PrerequisiteShas,
		&i.Reason,
		&i.Context,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCaptureState = `-- name: MarkCaptureState :one
UPDATE recovery_captures
SET state = $1, reason = $2, updated_at = now()
WHERE id = $3
RETURNING id, hold_id, run_id, user_id, original_worker_id, original_worker_identity, source_sha, attempted_head_sha, idempotency_key, state, manifest_bound, byte_size, checksum, chunk_count, prerequisite_shas, reason, context, expires_at, created_at, updated_at
`

type MarkCaptureStateParams struct {
	State  string      `json:"state"`
	Reason pgtype.Text `json:"reason"`
	ID     uuid.UUID   `json:"id"`
}

// D4: move a capture to a non-ready lifecycle state (uploading / needs_action /
// discarded) with an optional bounded reason. Used to record a bounded, sanitized
// oversized/quota/transport/integrity reason on needs_action, or to mark an upload in
// progress. reason is nullable (sqlc.narg) so a state with no reason clears it.
func (q *Queries) MarkCaptureState(ctx context.Context, arg MarkCaptureStateParams) (RecoveryCapture, error) {
	row := q.db.QueryRow(ctx, markCaptureState, arg.State, arg.Reason, arg.ID)
	var i RecoveryCapture
	err := row.Scan(
		&i.ID,
		&i.HoldID,
		&i.RunID,
		&i.UserID,
		&i.OriginalWorkerID,
		&i.OriginalWorkerIdentity,
		&i.SourceSha,
		&i.AttemptedHeadSha,
		&i.IdempotencyKey,
		&i.State,
		&i.ManifestBound,
		&i.ByteSize,
		&i.Checksum,
		&i.ChunkCount,
		&i.PrerequisiteShas,
		&i.Reason,
		&i.Context,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseCustodyHold = `-- name: ReleaseCustodyHold :execrows
UPDATE recovery_custody_holds
SET live_worker_id = NULL, live_run_id = NULL, state = 'released',
    release_evidence = $1,
    released_at = now(), updated_at = now()
WHERE id = $2 AND state = 'open'
`

type ReleaseCustodyHoldParams struct {
	ReleaseEvidence pgtype.Text `json:"release_evidence"`
	ID              uuid.UUID   `json:"id"`
}

// D3: the PER-HOLD RELEASE mechanism. Nulls both live FKs (dropping the ON DELETE RESTRICT
// that blocks worker/run teardown), flips state to 'released' and stamps released_at, for the
// ONE hold named by @id. Idempotent: a second call moves zero rows (the hold is no longer
// open). Captures survive (hold_id -> capture is ON DELETE RESTRICT, and this never deletes
// the hold). The immutable provenance columns are untouched. This is the reconciler's release:
// it releases EXACTLY the hold ListReleasableCustodyHolds qualified, so a sibling
// older-generation orphan hold on the same run is never collaterally released (the multi-hold
// hazard documented on ListReleasableCustodyHolds).
//
// PRD #1392 M1 (D3): release_evidence records WHY this release was warranted — the
// reconciler passes the per-hold class ListReleasableCustodyHolds now computes ('publication'
// for a completed-run backstop, 'archive' for a ready capture). CHECK-constrained to the five
// classes (migration 00232).
func (q *Queries) ReleaseCustodyHold(ctx context.Context, arg ReleaseCustodyHoldParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseCustodyHold, arg.ReleaseEvidence, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseCustodyHoldExact = `-- name: ReleaseCustodyHoldExact :execrows
UPDATE recovery_custody_holds
SET live_worker_id = NULL, live_run_id = NULL, state = 'released',
    release_evidence = $1,
    released_at = now(), updated_at = now()
WHERE run_id = $2
  AND generation = $3
  AND live_worker_id = $4::uuid
  AND state = 'open'
`

type ReleaseCustodyHoldExactParams struct {
	ReleaseEvidence pgtype.Text `json:"release_evidence"`
	RunID           uuid.UUID   `json:"run_id"`
	Generation      int64       `json:"generation"`
	WorkerID        uuid.UUID   `json:"worker_id"`
}

// PRD #1349 M1 (D1/D2/D3): the GENERATION-EXACT worker release. Nulls both live FKs (dropping
// the ON DELETE RESTRICT that blocks worker/run teardown), flips state to 'released' and
// stamps released_at, for the ONE open hold on @run_id at @generation held live by
// @worker_id. Unlike ReleaseCustodyForRunWorker (which matches EVERY open hold on the run for
// the worker), this settles EXACTLY the named generation — so a newer same-worker generation
// can never release an older generation whose source it did not inherit (the D2 hazard). The
// caller must have already established this generation's durable evidence (published head,
// available archive, or verified no-output). Idempotent: a second call moves zero rows.
// Captures survive; the immutable provenance columns are untouched.
//
// PRD #1392 M1 (D3): release_evidence records WHY this release was warranted. The caller
// supplies the class: the terminal-completion release passes 'publication'; the worker
// Release endpoint passes an allowlisted request value ('publication' or 'forge_no_output');
// the forge pre-clone park passes 'no_adopted_source' (a generation that never adopted a
// source has nothing to prove against the forge). CHECK-constrained to the five classes
// (migration 00232).
func (q *Queries) ReleaseCustodyHoldExact(ctx context.Context, arg ReleaseCustodyHoldExactParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseCustodyHoldExact,
		arg.ReleaseEvidence,
		arg.RunID,
		arg.Generation,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveCaptureExact = `-- name: ReserveCaptureExact :one

INSERT INTO recovery_captures
    (hold_id, run_id, user_id, original_worker_id, original_worker_identity,
     source_sha, attempted_head_sha, idempotency_key, state)
SELECT h.id, $1, $2, $3, $4::text,
       $5, $6, $7, 'preparing'
FROM recovery_custody_holds h
WHERE h.run_id = $1
  AND h.user_id = $2
  AND h.original_worker_id = $3
  AND h.generation = $8
  AND h.state = 'open'
ORDER BY h.created_at DESC
LIMIT 1
ON CONFLICT (hold_id, idempotency_key) DO UPDATE SET updated_at = now()
RETURNING id, hold_id, run_id, user_id, original_worker_id, original_worker_identity, source_sha, attempted_head_sha, idempotency_key, state, manifest_bound, byte_size, checksum, chunk_count, prerequisite_shas, reason, context, expires_at, created_at, updated_at
`

type ReserveCaptureExactParams struct {
	RunID                  uuid.UUID   `json:"run_id"`
	UserID                 uuid.UUID   `json:"user_id"`
	OriginalWorkerID       pgtype.UUID `json:"original_worker_id"`
	OriginalWorkerIdentity string      `json:"original_worker_identity"`
	SourceSha              string      `json:"source_sha"`
	AttemptedHeadSha       pgtype.Text `json:"attempted_head_sha"`
	IdempotencyKey         string      `json:"idempotency_key"`
	Generation             int64       `json:"generation"`
}

// ════════════════════════════════════════════════════════════════════════════════════════
// PRD #1349 M1: the ADDITIVE exact-generation and owner-disposition store contract. These
// queries are the COMPLETE store-query layer M2 (park capture/post-clone evidence), M4
// (server generation-safe lifecycle), M5 (owner hold API/CLI disposition) and M6 (web
// surface + owner Slack episode alert) consume. They were introduced strictly ADDITIVELY by
// M1 (existing queries UNTOUCHED, so M1 compiled standalone). M4 has since flipped every
// capture-reserve/custody-release call site onto these exact-generation names and DELETED the
// superseded generation-blind ReserveCapture / ReleaseCustodyForRunWorker queries, so those no
// longer exist above (ReleaseCustodyHold, the reconciler's per-hold release, remains).
// ════════════════════════════════════════════════════════════════════════════════════════
// PRD #1349 M1 (D1/D2): the GENERATION-EXACT reserve. Identical to ReserveCapture except the
// hold-selection WHERE ALSO matches @generation, so a capture is bound to the ONE hold this
// worker took at that exact claim generation (never a newer same-worker hold on the run). No
// open hold owned by @original_worker_id AT @generation -> zero rows -> pgx.ErrNoRows -> not
// authorized (fail closed), enforcing the D1 exact-identity invariant in-SQL. The ON CONFLICT
// idempotency is unchanged: retrying the SAME (hold_id, idempotency_key) re-stamps updated_at
// and returns the existing row, so a lost ACK re-reserves the same capture and a changed
// source_sha under the same key never overwrites the frozen source. M2/M4 flip capture
// reservation onto this in place of the generation-blind newest-hold ReserveCapture.
func (q *Queries) ReserveCaptureExact(ctx context.Context, arg ReserveCaptureExactParams) (RecoveryCapture, error) {
	row := q.db.QueryRow(ctx, reserveCaptureExact,
		arg.RunID,
		arg.UserID,
		arg.OriginalWorkerID,
		arg.OriginalWorkerIdentity,
		arg.SourceSha,
		arg.AttemptedHeadSha,
		arg.IdempotencyKey,
		arg.Generation,
	)
	var i RecoveryCapture
	err := row.Scan(
		&i.ID,
		&i.HoldID,
		&i.RunID,
		&i.UserID,
		&i.OriginalWorkerID,
		&i.OriginalWorkerIdentity,
		&i.SourceSha,
		&i.AttemptedHeadSha,
		&i.IdempotencyKey,
		&i.State,
		&i.ManifestBound,
		&i.ByteSize,
		&i.Checksum,
		&i.ChunkCount,
		&i.PrerequisiteShas,
		&i.Reason,
		&i.Context,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
