// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_disk.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRunDisk = `-- name: GetRunDisk :one
SELECT d.worker_id, d.run_id, d.home_bytes, d.cache_bytes, d.truncated, d.sampled_at
FROM worker_run_disk d
WHERE d.run_id = $1
  AND d.sampled_at > now() - interval '15 minutes'
ORDER BY (d.worker_id = $2::uuid) DESC NULLS LAST, d.sampled_at DESC
LIMIT 1
`

type GetRunDiskParams struct {
	RunID           uuid.UUID   `json:"run_id"`
	CurrentWorkerID pgtype.UUID `json:"current_worker_id"`
}

// One run's latest fresh size row for the run DTO: the row its current worker reported when
// there is one, else the most recently sampled row from any worker (a parked run whose worker
// binding moved still shows the size its last worker saw). pgx.ErrNoRows when nothing fresh.
func (q *Queries) GetRunDisk(ctx context.Context, arg GetRunDiskParams) (WorkerRunDisk, error) {
	row := q.db.QueryRow(ctx, getRunDisk, arg.RunID, arg.CurrentWorkerID)
	var i WorkerRunDisk
	err := row.Scan(
		&i.WorkerID,
		&i.RunID,
		&i.HomeBytes,
		&i.CacheBytes,
		&i.Truncated,
		&i.SampledAt,
	)
	return i, err
}

const listLargestRunDiskForWorkers = `-- name: ListLargestRunDiskForWorkers :many
SELECT ranked.worker_id, ranked.run_id, ranked.home_bytes, ranked.cache_bytes, ranked.truncated, ranked.sampled_at
FROM (
    SELECT d.worker_id, d.run_id, d.home_bytes, d.cache_bytes, d.truncated, d.sampled_at,
           row_number() OVER (PARTITION BY d.worker_id ORDER BY d.home_bytes DESC, d.run_id) AS rn
    FROM worker_run_disk d
    WHERE d.worker_id = ANY($1::uuid[])
      AND d.sampled_at > now() - interval '15 minutes'
) ranked
WHERE ranked.rn <= $2::int
ORDER BY ranked.worker_id, ranked.home_bytes DESC, ranked.run_id
`

type ListLargestRunDiskForWorkersParams struct {
	WorkerIds []uuid.UUID `json:"worker_ids"`
	PerWorker int32       `json:"per_worker"`
}

// The largest (by HOME bytes) fresh per-run rows of each listed worker, at most @per_worker
// each: the worker DTO's run_disk overlay (top few) and the admin-health run-disk check (top
// one). Batched over a worker-id set so a list endpoint reads every worker in one round-trip.
func (q *Queries) ListLargestRunDiskForWorkers(ctx context.Context, arg ListLargestRunDiskForWorkersParams) ([]WorkerRunDisk, error) {
	rows, err := q.db.Query(ctx, listLargestRunDiskForWorkers, arg.WorkerIds, arg.PerWorker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkerRunDisk{}
	for rows.Next() {
		var i WorkerRunDisk
		if err := rows.Scan(
			&i.WorkerID,
			&i.RunID,
			&i.HomeBytes,
			&i.CacheBytes,
			&i.Truncated,
			&i.SampledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceWorkerRunDisk = `-- name: ReplaceWorkerRunDisk :exec

WITH incoming AS (
    -- Ordinality-joined single-array unnests (sqlc cannot type a multi-argument unnest), the
    -- judge_bulk_disposition.sql shape: the four arrays are parallel and equal-length.
    SELECT ids.val AS run_id, hb.val AS home_bytes, cb.val AS cache_bytes, tr.val AS truncated
    FROM unnest($2::uuid[]) WITH ORDINALITY AS ids(val, ord)
    JOIN unnest($3::bigint[]) WITH ORDINALITY AS hb(val, ord) ON hb.ord = ids.ord
    JOIN unnest($4::bigint[]) WITH ORDINALITY AS cb(val, ord) ON cb.ord = ids.ord
    JOIN unnest($5::boolean[]) WITH ORDINALITY AS tr(val, ord) ON tr.ord = ids.ord
    JOIN runs r ON r.id = ids.val AND r.user_id = $6::uuid
), deleted AS (
    DELETE FROM worker_run_disk d
    WHERE d.worker_id = $1::uuid
      AND NOT EXISTS (SELECT 1 FROM incoming WHERE incoming.run_id = d.run_id)
)
INSERT INTO worker_run_disk (worker_id, run_id, home_bytes, cache_bytes, truncated, sampled_at)
SELECT $1::uuid, incoming.run_id, incoming.home_bytes, incoming.cache_bytes, incoming.truncated, now()
FROM incoming
ON CONFLICT (worker_id, run_id) DO UPDATE SET
    home_bytes  = EXCLUDED.home_bytes,
    cache_bytes = EXCLUDED.cache_bytes,
    truncated   = EXCLUDED.truncated,
    sampled_at  = EXCLUDED.sampled_at
`

type ReplaceWorkerRunDiskParams struct {
	WorkerID   uuid.UUID   `json:"worker_id"`
	RunIds     []uuid.UUID `json:"run_ids"`
	HomeBytes  []int64     `json:"home_bytes"`
	CacheBytes []int64     `json:"cache_bytes"`
	Truncated  []bool      `json:"truncated"`
	UserID     uuid.UUID   `json:"user_id"`
}

// PRD #1809 M6 (D8): per-run disk size (worker_run_disk) and the park's checkpoint durability
// flag (runs.checkpoint_contains_latest). Everything here is DISPLAY-ONLY: no claim,
// scheduling, sweeper or custody query reads worker_run_disk or checkpoint_contains_latest.
//
// Freshness: every reader ignores a worker_run_disk row sampled more than 15 minutes ago. A
// heartbeat that omits run_disk (an older worker, a tick with no sample) leaves the worker's rows
// in place, so the window is what retires a downgraded worker's last report.
// Replace one worker's reported per-run sizes with the set its latest heartbeat carried, in ONE
// statement: rows for runs no longer listed are deleted and the listed ones are upserted with a
// fresh sampled_at. The parallel arrays are the handler's validated, de-duplicated, capped list
// (parseWorkerStats). Only run ids that exist AND belong to the worker's own owner are kept, so a
// garbled or hostile id is dropped here instead of violating the runs FK. The DELETE and the
// INSERT touch disjoint rows (listed vs not listed), so the two data-modifying parts never
// target the same row.
func (q *Queries) ReplaceWorkerRunDisk(ctx context.Context, arg ReplaceWorkerRunDiskParams) error {
	_, err := q.db.Exec(ctx, replaceWorkerRunDisk,
		arg.WorkerID,
		arg.RunIds,
		arg.HomeBytes,
		arg.CacheBytes,
		arg.Truncated,
		arg.UserID,
	)
	return err
}

const setRunCheckpointContainsLatest = `-- name: SetRunCheckpointContainsLatest :execrows
UPDATE runs SET
    checkpoint_contains_latest = $1
WHERE id = $2
  AND worker_id = $3
  AND status = $4
`

type SetRunCheckpointContainsLatestParams struct {
	CheckpointContainsLatest pgtype.Bool `json:"checkpoint_contains_latest"`
	ID                       uuid.UUID   `json:"id"`
	WorkerID                 pgtype.UUID `json:"worker_id"`
	Status                   string      `json:"status"`
}

// Record whether the checkpoint a park published contains the run's latest committed work
// (PRD #1809 M6, D8). Called after a park transition APPLIED, and guarded on the run still
// being owned by the reporting worker in the status that park wrote, so a run that already moved
// on (re-queued, resumed, cancelled) is left alone. NULL is "not reported": every park writes
// the report as carried, including NULL from a worker that omits it, so the flag always
// describes the latest park and never an older one. Display-only: custody ignores it.
func (q *Queries) SetRunCheckpointContainsLatest(ctx context.Context, arg SetRunCheckpointContainsLatestParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRunCheckpointContainsLatest,
		arg.CheckpointContainsLatest,
		arg.ID,
		arg.WorkerID,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
