// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRunServerSide = `-- name: CancelRunServerSide :execrows
UPDATE runs SET status = 'cancelled', stop_kind = 'cancelled', move_pending_since = now(), finished_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2
  AND status NOT IN ('completed', 'failed', 'cancelled')
`

type CancelRunServerSideParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Server-side cancel for a run with no live poller (still queued, or its worker
// went stale): the user input is not stranded waiting for a GET /inputs poll
// that will never come. cancelled restores the origin column → stamp. stop_kind is
// stamped 'cancelled' for uniformity (PRD #33 Decision 3), though isStoppedRun's
// status='cancelled' branch already treats this run as a deliberate stop.
func (q *Queries) CancelRunServerSide(ctx context.Context, arg CancelRunServerSideParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRunServerSide, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimAutopilotTerminalComment = `-- name: ClaimAutopilotTerminalComment :execrows
UPDATE runs SET autopilot_commented_at = now()
WHERE id = $1 AND auto_approve = true AND autopilot_commented_at IS NULL
`

// Atomically claim the single terminal issue comment for an autopilot run (PRD #19
// M5, Decision 6 record-then-comment). Records the marker FIRST; the caller posts
// the comment only when this returns 1. The auto_approve + IS NULL guard makes it
// both the autopilot gate and the concurrency claim: a manual run is never claimed,
// and of the possibly-racing lifecycle invocations (inline notify vs reconcile
// retry) exactly one gets the row — the rest read 0 and do not re-post. A crash
// after this commits but before the forge post loses that one comment, never
// double-posts.
func (q *Queries) ClaimAutopilotTerminalComment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimAutopilotTerminalComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimRun = `-- name: ClaimRun :one
UPDATE runs SET
    status     = 'claimed',
    worker_id  = $1,
    claimed_at = now(),
    updated_at = now()
WHERE id = (
    SELECT r.id FROM runs r
    WHERE r.user_id = $2
      AND r.kind <> 'chat'
      AND r.status = 'queued'
      AND (r.worker_id IS NULL
           OR r.worker_id = $1
           OR r.updated_at < $3)
    ORDER BY COALESCE(r.worker_id = $1, false) DESC, r.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, user_id, repo_id, issue_iid, issue_title, issue_description, status, requeue_count, worker_id, session_id, last_seq, branch, mr_iid, failure_reason, plan_md, iteration_count, claimed_at, started_at, finished_at, created_at, updated_at, origin_column, board_column, move_pending_since, mr_state, auto_approve, autopilot_commented_at, kind, pipeline_id, pipeline_ref, failure_snapshot, fix_verdict, stop_kind, agent_source, agent_exclusions, repo_agents, title, resume_of_run_id, target_run_id
`

type ClaimRunParams struct {
	WorkerID       pgtype.UUID        `json:"worker_id"`
	UserID         uuid.UUID          `json:"user_id"`
	AffinityCutoff pgtype.Timestamptz `json:"affinity_cutoff"`
}

// The RUN claim lane (Decision 4): atomic claim of the oldest claimable queued run
// for the worker's user, EXCLUDING chat runs (which the chat lane claims via
// ClaimChatRun). A re-queued run prefers its prior worker (own runs sort first, and
// are the only claimant until the affinity grace lapses — @affinity_cutoff is now
// minus WORKER_AFFINITY_GRACE); after that any of the user's workers may claim it.
// FOR UPDATE SKIP LOCKED lets concurrent workers claim disjoint runs without
// blocking (multica's queue semantics). The kind<>'chat' predicate is what keeps
// the run lane and the concurrent chat lane from stealing each other's work.
func (q *Queries) ClaimRun(ctx context.Context, arg ClaimRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, claimRun, arg.WorkerID, arg.UserID, arg.AffinityCutoff)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.IssueIid,
		&i.IssueTitle,
		&i.IssueDescription,
		&i.Status,
		&i.RequeueCount,
		&i.WorkerID,
		&i.SessionID,
		&i.LastSeq,
		&i.Branch,
		&i.MrIid,
		&i.FailureReason,
		&i.PlanMd,
		&i.IterationCount,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.MrState,
		&i.AutoApprove,
		&i.AutopilotCommentedAt,
		&i.Kind,
		&i.PipelineID,
		&i.PipelineRef,
		&i.FailureSnapshot,
		&i.FixVerdict,
		&i.StopKind,
		&i.AgentSource,
		&i.AgentExclusions,
		&i.RepoAgents,
		&i.Title,
		&i.ResumeOfRunID,
		&i.TargetRunID,
	)
	return i, err
}

const clearIssueRunsMovePending = `-- name: ClearIssueRunsMovePending :execrows
UPDATE runs SET move_pending_since = NULL, updated_at = now()
WHERE repo_id = $1::uuid AND issue_iid = $2 AND move_pending_since IS NOT NULL
`

type ClearIssueRunsMovePendingParams struct {
	RepoID   uuid.UUID   `json:"repo_id"`
	IssueIid pgtype.Int8 `json:"issue_iid"`
}

// A manual drag heals it: clear the pending marker for every run of this issue so
// the reconcile loop stops trying to move a card a human just placed.
func (q *Queries) ClearIssueRunsMovePending(ctx context.Context, arg ClearIssueRunsMovePendingParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearIssueRunsMovePending, arg.RepoID, arg.IssueIid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearRunMovePending = `-- name: ClearRunMovePending :execrows
UPDATE runs SET move_pending_since = NULL, updated_at = now()
WHERE id = $1
`

// Clear a run's pending marker without recording a column: used when the move is
// deliberately skipped (manual drag detected, closed issue, unknown baseline).
func (q *Queries) ClearRunMovePending(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearRunMovePending, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeRunInputs = `-- name: ConsumeRunInputs :many
WITH pending AS (
    SELECT p.id FROM run_user_inputs p
    WHERE p.run_id = $1 AND p.consumed_at IS NULL
    ORDER BY p.id ASC
    FOR UPDATE SKIP LOCKED
),
consumed AS (
    UPDATE run_user_inputs u SET consumed_at = now()
    FROM pending WHERE u.id = pending.id
    RETURNING u.id, u.kind, u.body, u.created_at
)
SELECT id, kind, body, created_at FROM consumed ORDER BY id ASC
`

type ConsumeRunInputsRow struct {
	ID        int64              `json:"id"`
	Kind      string             `json:"kind"`
	Body      pgtype.Text        `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// FIFO consume: mark and return every pending input for the run, oldest first.
// FOR UPDATE SKIP LOCKED keeps two concurrent polls from returning the same row.
func (q *Queries) ConsumeRunInputs(ctx context.Context, runID uuid.UUID) ([]ConsumeRunInputsRow, error) {
	rows, err := q.db.Query(ctx, consumeRunInputs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsumeRunInputsRow{}
	for rows.Next() {
		var i ConsumeRunInputsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWorkerNonTerminalRuns = `-- name: CountWorkerNonTerminalRuns :one
SELECT count(*) FROM runs
WHERE worker_id = $1
  AND user_id = $2
  AND status NOT IN ('completed', 'failed', 'cancelled')
`

type CountWorkerNonTerminalRunsParams struct {
	WorkerID pgtype.UUID `json:"worker_id"`
	UserID   uuid.UUID   `json:"user_id"`
}

// Deletion guard: a worker holding a non-terminal run may not be deleted. The FK
// is ON DELETE SET NULL, so deleting would orphan such a run — an awaiting_approval
// run matches no sweep once its worker_id is gone (the stale-worker sweeps key on
// worker_id), and the one-active-run index then blocks re-running the issue.
// Scoped by user_id so a cross-tenant delete attempt still 404s (never 409).
func (q *Queries) CountWorkerNonTerminalRuns(ctx context.Context, arg CountWorkerNonTerminalRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkerNonTerminalRuns, arg.WorkerID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovePlanInput = `-- name: CreateApprovePlanInput :one
WITH selected AS (
    UPDATE runs SET
        agent_source     = $3,
        agent_exclusions = $4,
        updated_at       = now()
    WHERE id = $1
    RETURNING id
)
INSERT INTO run_user_inputs (run_id, kind, body)
VALUES ($1, 'approve_plan', $2)
RETURNING id, run_id, kind, body, consumed_at, created_at
`

type CreateApprovePlanInputParams struct {
	RunID           uuid.UUID   `json:"run_id"`
	Body            pgtype.Text `json:"body"`
	AgentSource     pgtype.Text `json:"agent_source"`
	AgentExclusions []byte      `json:"agent_exclusions"`
}

// Enqueue an approve_plan verdict for the live worker AND record the agent
// selection it carries, in ONE statement (PRD #37, mirroring CreateStopVerdictInput
// and for the same reason: workersvc.Store exposes no transaction seam, so the
// combined statement IS the atomicity). A second, non-transactional UPDATE could
// leave a run whose worker was told to use the repo agents but whose row does not
// say so — the run view and the MR marker would then lie about what ran.
//
// The body carries the canonical JSON encoding of the same selection, because the
// worker reads it from the input, not from the row. Both are written from the
// server's re-validated value, never from the client's raw text. A resume that
// re-enters the gate overwrites both columns with the latest approval (Decision 8b).
func (q *Queries) CreateApprovePlanInput(ctx context.Context, arg CreateApprovePlanInputParams) (RunUserInput, error) {
	row := q.db.QueryRow(ctx, createApprovePlanInput,
		arg.RunID,
		arg.Body,
		arg.AgentSource,
		arg.AgentExclusions,
	)
	var i RunUserInput
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Body,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one

INSERT INTO runs (user_id, repo_id, issue_iid, issue_title, issue_description, origin_column, move_pending_since, auto_approve)
VALUES ($1, $2::uuid, $3, $4, $5, $6, now(), $7)
RETURNING id, user_id, repo_id, issue_iid, issue_title, issue_description, status, requeue_count, worker_id, session_id, last_seq, branch, mr_iid, failure_reason, plan_md, iteration_count, claimed_at, started_at, finished_at, created_at, updated_at, origin_column, board_column, move_pending_since, mr_state, auto_approve, autopilot_commented_at, kind, pipeline_id, pipeline_ref, failure_snapshot, fix_verdict, stop_kind, agent_source, agent_exclusions, repo_agents, title, resume_of_run_id, target_run_id
`

type CreateRunParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	RepoID           uuid.UUID   `json:"repo_id"`
	IssueIid         pgtype.Int8 `json:"issue_iid"`
	IssueTitle       string      `json:"issue_title"`
	IssueDescription string      `json:"issue_description"`
	OriginColumn     pgtype.Text `json:"origin_column"`
	AutoApprove      bool        `json:"auto_approve"`
}

// Runs ---------------------------------------------------------------------
// Queue a run from a card. The one-non-terminal-run-per-issue partial unique
// index rejects a second active run for the same issue (23505 → 409).
// origin_column snapshots the issue's column now, so a failed/cancelled run can
// be restored to where it started; it is passed even when "" (Open), and only
// NULL for a caller that cannot resolve it. move_pending_since is stamped in this
// same INSERT — queued is a status the column automation reacts to (→ In
// Progress), and the same-statement stamp closes the crash window before the
// forge move. auto_approve is true only for autopilot-created runs (PRD #19 M4):
// the worker reads it to resolve the plan gate without a human.
// repo_id is nullable since PRD #39 (chat runs carry none); the ::uuid cast keeps
// this INSERT param a non-null uuid.UUID — an issue run always targets a repo.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.UserID,
		arg.RepoID,
		arg.IssueIid,
		arg.IssueTitle,
		arg.IssueDescription,
		arg.OriginColumn,
		arg.AutoApprove,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.IssueIid,
		&i.IssueTitle,
		&i.IssueDescription,
		&i.Status,
		&i.RequeueCount,
		&i.WorkerID,
		&i.SessionID,
		&i.LastSeq,
		&i.Branch,
		&i.MrIid,
		&i.FailureReason,
		&i.PlanMd,
		&i.IterationCount,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.MrState,
		&i.AutoApprove,
		&i.AutopilotCommentedAt,
		&i.Kind,
		&i.PipelineID,
		&i.PipelineRef,
		&i.FailureSnapshot,
		&i.FixVerdict,
		&i.StopKind,
		&i.AgentSource,
		&i.AgentExclusions,
		&i.RepoAgents,
		&i.Title,
		&i.ResumeOfRunID,
		&i.TargetRunID,
	)
	return i, err
}

const createRunInput = `-- name: CreateRunInput :one

INSERT INTO run_user_inputs (run_id, kind, body)
VALUES ($1, $2, $3)
RETURNING id, run_id, kind, body, consumed_at, created_at
`

type CreateRunInputParams struct {
	RunID uuid.UUID   `json:"run_id"`
	Kind  string      `json:"kind"`
	Body  pgtype.Text `json:"body"`
}

// User inputs (steering) ---------------------------------------------------
// Enqueue a plain steering input (approve_plan / follow_up) for the live worker to
// consume. This path never touches the runs row — no stop signal, no lock — so a
// follow-up mid-run is a single cheap insert. Deliberate-stop verdicts go through
// CreateStopVerdictInput instead (they must stamp runs.stop_kind atomically).
func (q *Queries) CreateRunInput(ctx context.Context, arg CreateRunInputParams) (RunUserInput, error) {
	row := q.db.QueryRow(ctx, createRunInput, arg.RunID, arg.Kind, arg.Body)
	var i RunUserInput
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Body,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStopVerdictInput = `-- name: CreateStopVerdictInput :one
WITH stamped AS (
    UPDATE runs SET stop_kind = $4, updated_at = now()
    WHERE id = $1
    RETURNING id
)
INSERT INTO run_user_inputs (run_id, kind, body)
VALUES ($1, $2, $3)
RETURNING id, run_id, kind, body, consumed_at, created_at
`

type CreateStopVerdictInputParams struct {
	RunID    uuid.UUID   `json:"run_id"`
	Kind     string      `json:"kind"`
	Body     pgtype.Text `json:"body"`
	StopKind pgtype.Text `json:"stop_kind"`
}

// Enqueue a deliberate-stop verdict (cancel / reject_plan) for the live worker AND
// stamp runs.stop_kind in the SAME statement (PRD #33 Decision 3): a data-modifying
// CTE runs to completion exactly once, so the stop signal can never be lost
// independently of the input that requested it — which a second, non-transactional
// UPDATE would risk, reintroducing the failed-vs-stopped bug. workersvc.Store exposes
// no transaction seam, so this single combined statement IS the atomicity. It is used
// ONLY for the two stop verdicts, so the stamp is unconditional (no IS NOT NULL guard
// and thus no parameter-type-inference pitfall). The stamp lands while the run is
// still non-terminal (awaiting_approval/running); the client's terminal-guarded
// isStoppedRun ignores it until the run actually reaches failed/cancelled.
func (q *Queries) CreateStopVerdictInput(ctx context.Context, arg CreateStopVerdictInputParams) (RunUserInput, error) {
	row := q.db.QueryRow(ctx, createStopVerdictInput,
		arg.RunID,
		arg.Kind,
		arg.Body,
		arg.StopKind,
	)
	var i RunUserInput
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Body,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorker = `-- name: CreateWorker :one

INSERT INTO workers (user_id, name, token_hash, template_declared)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, token_hash, status, last_heartbeat_at, version, created_at, updated_at, template_declared, template_reported, max_concurrent_runs
`

type CreateWorkerParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	Name             string      `json:"name"`
	TokenHash        []byte      `json:"token_hash"`
	TemplateDeclared pgtype.Text `json:"template_declared"`
}

// Workers -----------------------------------------------------------------
// Issue a worker: the plaintext join token is shown once by the caller; only its
// sha256 (token_hash) is stored. template_declared is the UI-chosen template
// (PRD #18), NULL when the caller made no choice.
func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TemplateDeclared,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateDeclared,
		&i.TemplateReported,
		&i.MaxConcurrentRuns,
	)
	return i, err
}

const deleteWorkerForUser = `-- name: DeleteWorkerForUser :execrows
DELETE FROM workers WHERE id = $1 AND user_id = $2
`

type DeleteWorkerForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkerForUser(ctx context.Context, arg DeleteWorkerForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkerForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failRunsOfStaleWorkersOverCap = `-- name: FailRunsOfStaleWorkersOverCap :many
UPDATE runs SET status = 'failed', failure_reason = $1, move_pending_since = now(), finished_at = now(), updated_at = now()
WHERE status IN ('claimed', 'running', 'awaiting_approval')
  AND requeue_count >= $2
  AND worker_id IN (
      SELECT id FROM workers WHERE last_heartbeat_at IS NULL OR last_heartbeat_at < $3
  )
RETURNING id, user_id, status
`

type FailRunsOfStaleWorkersOverCapParams struct {
	FailureReason pgtype.Text        `json:"failure_reason"`
	MaxRequeues   int32              `json:"max_requeues"`
	Cutoff        pgtype.Timestamptz `json:"cutoff"`
}

type FailRunsOfStaleWorkersOverCapRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

// A stale worker's non-terminal run that has already used its re-queue budget →
// failed instead of re-queued. Stamps move_pending_since (reconcile restores the
// origin column; the sweep itself never touches the forge — worker-loss recovery
// must not wait on a down forge).
func (q *Queries) FailRunsOfStaleWorkersOverCap(ctx context.Context, arg FailRunsOfStaleWorkersOverCapParams) ([]FailRunsOfStaleWorkersOverCapRow, error) {
	rows, err := q.db.Query(ctx, failRunsOfStaleWorkersOverCap, arg.FailureReason, arg.MaxRequeues, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailRunsOfStaleWorkersOverCapRow{}
	for rows.Next() {
		var i FailRunsOfStaleWorkersOverCapRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failWorkerRunsOverCap = `-- name: FailWorkerRunsOverCap :execrows

UPDATE runs SET status = 'failed', failure_reason = $1, move_pending_since = now(), finished_at = now(), updated_at = now()
WHERE worker_id = $2
  AND status IN ('claimed', 'running', 'awaiting_approval')
  AND requeue_count >= $3
`

type FailWorkerRunsOverCapParams struct {
	FailureReason pgtype.Text `json:"failure_reason"`
	WorkerID      pgtype.UUID `json:"worker_id"`
	MaxRequeues   int32       `json:"max_requeues"`
}

// Register-time orphan recovery (worker-scoped) ------------------------------
// On register a worker declares a fresh start, so any run it still holds is
// orphaned (its execution is gone). Over its re-queue budget → failed. failed →
// origin restore, applied by the reconcile loop (register does no forge I/O), so
// it stamps move_pending_since.
func (q *Queries) FailWorkerRunsOverCap(ctx context.Context, arg FailWorkerRunsOverCapParams) (int64, error) {
	result, err := q.db.Exec(ctx, failWorkerRunsOverCap, arg.FailureReason, arg.WorkerID, arg.MaxRequeues)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, user_id, repo_id, issue_iid, issue_title, issue_description, status, requeue_count, worker_id, session_id, last_seq, branch, mr_iid, failure_reason, plan_md, iteration_count, claimed_at, started_at, finished_at, created_at, updated_at, origin_column, board_column, move_pending_since, mr_state, auto_approve, autopilot_commented_at, kind, pipeline_id, pipeline_ref, failure_snapshot, fix_verdict, stop_kind, agent_source, agent_exclusions, repo_agents, title, resume_of_run_id, target_run_id FROM runs WHERE id = $1
`

// Admin viewer path: fetch any run regardless of owner. The per-run authz check
// lives in the service, which only reaches this after confirming the viewer is an
// admin (owners go through GetRunByIDForUser).
func (q *Queries) GetRunByID(ctx context.Context, id uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.IssueIid,
		&i.IssueTitle,
		&i.IssueDescription,
		&i.Status,
		&i.RequeueCount,
		&i.WorkerID,
		&i.SessionID,
		&i.LastSeq,
		&i.Branch,
		&i.MrIid,
		&i.FailureReason,
		&i.PlanMd,
		&i.IterationCount,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.MrState,
		&i.AutoApprove,
		&i.AutopilotCommentedAt,
		&i.Kind,
		&i.PipelineID,
		&i.PipelineRef,
		&i.FailureSnapshot,
		&i.FixVerdict,
		&i.StopKind,
		&i.AgentSource,
		&i.AgentExclusions,
		&i.RepoAgents,
		&i.Title,
		&i.ResumeOfRunID,
		&i.TargetRunID,
	)
	return i, err
}

const getRunByIDForUser = `-- name: GetRunByIDForUser :one
SELECT id, user_id, repo_id, issue_iid, issue_title, issue_description, status, requeue_count, worker_id, session_id, last_seq, branch, mr_iid, failure_reason, plan_md, iteration_count, claimed_at, started_at, finished_at, created_at, updated_at, origin_column, board_column, move_pending_since, mr_state, auto_approve, autopilot_commented_at, kind, pipeline_id, pipeline_ref, failure_snapshot, fix_verdict, stop_kind, agent_source, agent_exclusions, repo_agents, title, resume_of_run_id, target_run_id FROM runs WHERE id = $1 AND user_id = $2
`

type GetRunByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetRunByIDForUser(ctx context.Context, arg GetRunByIDForUserParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByIDForUser, arg.ID, arg.UserID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.IssueIid,
		&i.IssueTitle,
		&i.IssueDescription,
		&i.Status,
		&i.RequeueCount,
		&i.WorkerID,
		&i.SessionID,
		&i.LastSeq,
		&i.Branch,
		&i.MrIid,
		&i.FailureReason,
		&i.PlanMd,
		&i.IterationCount,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.MrState,
		&i.AutoApprove,
		&i.AutopilotCommentedAt,
		&i.Kind,
		&i.PipelineID,
		&i.PipelineRef,
		&i.FailureSnapshot,
		&i.FixVerdict,
		&i.StopKind,
		&i.AgentSource,
		&i.AgentExclusions,
		&i.RepoAgents,
		&i.Title,
		&i.ResumeOfRunID,
		&i.TargetRunID,
	)
	return i, err
}

const getRunClaimContext = `-- name: GetRunClaimContext :one
SELECT rp.web_url             AS repo_web_url,
       rp.path_with_namespace AS repo_path,
       rp.default_branch,
       rp.repo_skills_enabled,
       rp.repo_devbox_opt_in,
       c.forge_type,
       c.base_url,
       c.bot_username,
       c.token_ciphertext
FROM runs r
JOIN repos rp ON rp.id = r.repo_id
JOIN forge_connections c ON c.id = rp.connection_id
WHERE r.id = $1
`

type GetRunClaimContextRow struct {
	RepoWebUrl        string      `json:"repo_web_url"`
	RepoPath          string      `json:"repo_path"`
	DefaultBranch     pgtype.Text `json:"default_branch"`
	RepoSkillsEnabled bool        `json:"repo_skills_enabled"`
	RepoDevboxOptIn   bool        `json:"repo_devbox_opt_in"`
	ForgeType         string      `json:"forge_type"`
	BaseUrl           string      `json:"base_url"`
	BotUsername       string      `json:"bot_username"`
	TokenCiphertext   []byte      `json:"token_ciphertext"`
}

// The repo + connection facts the claim payload needs, alongside the run. The
// bot PAT (token_ciphertext) is decrypted by the service, never selected in the
// clear from the DB.
func (q *Queries) GetRunClaimContext(ctx context.Context, runID uuid.UUID) (GetRunClaimContextRow, error) {
	row := q.db.QueryRow(ctx, getRunClaimContext, runID)
	var i GetRunClaimContextRow
	err := row.Scan(
		&i.RepoWebUrl,
		&i.RepoPath,
		&i.DefaultBranch,
		&i.RepoSkillsEnabled,
		&i.RepoDevboxOptIn,
		&i.ForgeType,
		&i.BaseUrl,
		&i.BotUsername,
		&i.TokenCiphertext,
	)
	return i, err
}

const getRunForWorkerUser = `-- name: GetRunForWorkerUser :one
SELECT r.id, r.kind, r.status, r.issue_iid, r.issue_title, r.branch, r.mr_iid, r.mr_state,
       r.failure_reason, r.stop_kind, r.fix_verdict, r.iteration_count, r.plan_md,
       r.created_at, r.updated_at,
       rp.path_with_namespace AS repo_path, rp.web_url AS repo_web_url
FROM runs r
LEFT JOIN repos rp ON rp.id = r.repo_id
WHERE r.id = $1 AND r.user_id = $2
`

type GetRunForWorkerUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetRunForWorkerUserRow struct {
	ID             uuid.UUID          `json:"id"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	IssueIid       pgtype.Int8        `json:"issue_iid"`
	IssueTitle     string             `json:"issue_title"`
	Branch         pgtype.Text        `json:"branch"`
	MrIid          pgtype.Int8        `json:"mr_iid"`
	MrState        pgtype.Text        `json:"mr_state"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	StopKind       pgtype.Text        `json:"stop_kind"`
	FixVerdict     pgtype.Text        `json:"fix_verdict"`
	IterationCount int32              `json:"iteration_count"`
	PlanMd         pgtype.Text        `json:"plan_md"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	RepoPath       pgtype.Text        `json:"repo_path"`
	RepoWebUrl     pgtype.Text        `json:"repo_web_url"`
}

// One run's detail, scoped to the worker's user (foreign/unknown id -> no row -> 404).
func (q *Queries) GetRunForWorkerUser(ctx context.Context, arg GetRunForWorkerUserParams) (GetRunForWorkerUserRow, error) {
	row := q.db.QueryRow(ctx, getRunForWorkerUser, arg.ID, arg.UserID)
	var i GetRunForWorkerUserRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.IssueIid,
		&i.IssueTitle,
		&i.Branch,
		&i.MrIid,
		&i.MrState,
		&i.FailureReason,
		&i.StopKind,
		&i.FixVerdict,
		&i.IterationCount,
		&i.PlanMd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoPath,
		&i.RepoWebUrl,
	)
	return i, err
}

const getRunMoveContext = `-- name: GetRunMoveContext :one

SELECT r.status, r.issue_iid, r.repo_id, r.origin_column, r.board_column, r.move_pending_since,
       r.auto_approve, r.mr_iid,
       rp.forge_project_id, rp.web_url AS repo_web_url,
       c.forge_type, c.base_url, c.token_ciphertext
FROM runs r
JOIN repos rp ON rp.id = r.repo_id
JOIN forge_connections c ON c.id = rp.connection_id
WHERE r.id = $1
`

type GetRunMoveContextRow struct {
	Status           string             `json:"status"`
	IssueIid         pgtype.Int8        `json:"issue_iid"`
	RepoID           pgtype.UUID        `json:"repo_id"`
	OriginColumn     pgtype.Text        `json:"origin_column"`
	BoardColumn      pgtype.Text        `json:"board_column"`
	MovePendingSince pgtype.Timestamptz `json:"move_pending_since"`
	AutoApprove      bool               `json:"auto_approve"`
	MrIid            pgtype.Int8        `json:"mr_iid"`
	ForgeProjectID   int64              `json:"forge_project_id"`
	RepoWebUrl       string             `json:"repo_web_url"`
	ForgeType        string             `json:"forge_type"`
	BaseUrl          string             `json:"base_url"`
	TokenCiphertext  []byte             `json:"token_ciphertext"`
}

// Column automation (PRD #12 M1) ------------------------------------------
// The run + connection facts the column automation needs to perform a forge-first
// label move: the run's status/issue/columns, plus the connection to build a
// client and the numeric project id UpdateIssueLabels requires. GetRunClaimContext
// (the sibling) deliberately lacks forge_project_id and the column snapshot, so
// this is its own query. token_ciphertext is decrypted by the service, never
// selected in the clear.
//
// It also carries the facts the M5 terminal-comment hook needs from the same read:
// auto_approve gates the comment to autopilot runs, mr_iid links the success
// comment, and rp.web_url builds that merge-request link. Both lifecycle observers
// (the inline notify and the reconcile loop) already load this row, so the terminal
// comment rides along without a second query.
func (q *Queries) GetRunMoveContext(ctx context.Context, runID uuid.UUID) (GetRunMoveContextRow, error) {
	row := q.db.QueryRow(ctx, getRunMoveContext, runID)
	var i GetRunMoveContextRow
	err := row.Scan(
		&i.Status,
		&i.IssueIid,
		&i.RepoID,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.AutoApprove,
		&i.MrIid,
		&i.ForgeProjectID,
		&i.RepoWebUrl,
		&i.ForgeType,
		&i.BaseUrl,
		&i.TokenCiphertext,
	)
	return i, err
}

const getRunOwnedByWorker = `-- name: GetRunOwnedByWorker :one
SELECT id, user_id, repo_id, issue_iid, issue_title, issue_description, status, requeue_count, worker_id, session_id, last_seq, branch, mr_iid, failure_reason, plan_md, iteration_count, claimed_at, started_at, finished_at, created_at, updated_at, origin_column, board_column, move_pending_since, mr_state, auto_approve, autopilot_commented_at, kind, pipeline_id, pipeline_ref, failure_snapshot, fix_verdict, stop_kind, agent_source, agent_exclusions, repo_agents, title, resume_of_run_id, target_run_id FROM runs WHERE id = $1 AND worker_id = $2
`

type GetRunOwnedByWorkerParams struct {
	ID       uuid.UUID   `json:"id"`
	WorkerID pgtype.UUID `json:"worker_id"`
}

// Worker-endpoint authz: a worker may only touch a run it currently holds.
func (q *Queries) GetRunOwnedByWorker(ctx context.Context, arg GetRunOwnedByWorkerParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunOwnedByWorker, arg.ID, arg.WorkerID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.IssueIid,
		&i.IssueTitle,
		&i.IssueDescription,
		&i.Status,
		&i.RequeueCount,
		&i.WorkerID,
		&i.SessionID,
		&i.LastSeq,
		&i.Branch,
		&i.MrIid,
		&i.FailureReason,
		&i.PlanMd,
		&i.IterationCount,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.MrState,
		&i.AutoApprove,
		&i.AutopilotCommentedAt,
		&i.Kind,
		&i.PipelineID,
		&i.PipelineRef,
		&i.FailureSnapshot,
		&i.FixVerdict,
		&i.StopKind,
		&i.AgentSource,
		&i.AgentExclusions,
		&i.RepoAgents,
		&i.Title,
		&i.ResumeOfRunID,
		&i.TargetRunID,
	)
	return i, err
}

const getWorkerByID = `-- name: GetWorkerByID :one
SELECT id, user_id, name, token_hash, status, last_heartbeat_at, version, created_at, updated_at, template_declared, template_reported, max_concurrent_runs FROM workers WHERE id = $1
`

func (q *Queries) GetWorkerByID(ctx context.Context, id uuid.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateDeclared,
		&i.TemplateReported,
		&i.MaxConcurrentRuns,
	)
	return i, err
}

const getWorkerByIDForUser = `-- name: GetWorkerByIDForUser :one
SELECT id, user_id, name, token_hash, status, last_heartbeat_at, version, created_at, updated_at, template_declared, template_reported, max_concurrent_runs FROM workers WHERE id = $1 AND user_id = $2
`

type GetWorkerByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkerByIDForUser(ctx context.Context, arg GetWorkerByIDForUserParams) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByIDForUser, arg.ID, arg.UserID)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateDeclared,
		&i.TemplateReported,
		&i.MaxConcurrentRuns,
	)
	return i, err
}

const getWorkerByTokenHash = `-- name: GetWorkerByTokenHash :one
SELECT id, user_id, name, token_hash, status, last_heartbeat_at, version, created_at, updated_at, template_declared, template_reported, max_concurrent_runs FROM workers WHERE token_hash = $1
`

// Worker auth: Bearer join token → sha256 → this lookup.
func (q *Queries) GetWorkerByTokenHash(ctx context.Context, tokenHash []byte) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByTokenHash, tokenHash)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateDeclared,
		&i.TemplateReported,
		&i.MaxConcurrentRuns,
	)
	return i, err
}

const heartbeatWorker = `-- name: HeartbeatWorker :one
UPDATE workers SET
    status            = 'online',
    last_heartbeat_at = now(),
    updated_at        = now()
WHERE id = $1
RETURNING id, user_id, name, token_hash, status, last_heartbeat_at, version, created_at, updated_at, template_declared, template_reported, max_concurrent_runs
`

func (q *Queries) HeartbeatWorker(ctx context.Context, id uuid.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, heartbeatWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateDeclared,
		&i.TemplateReported,
		&i.MaxConcurrentRuns,
	)
	return i, err
}

const insertRunMessage = `-- name: InsertRunMessage :execrows

INSERT INTO run_messages (run_id, seq, kind, agent, payload)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (run_id, seq) DO NOTHING
`

type InsertRunMessageParams struct {
	RunID   uuid.UUID   `json:"run_id"`
	Seq     int32       `json:"seq"`
	Kind    string      `json:"kind"`
	Agent   pgtype.Text `json:"agent"`
	Payload []byte      `json:"payload"`
}

// Messages -----------------------------------------------------------------
// Idempotent seq-numbered append: a re-delivered batch (worker retry) is a
// no-op on the duplicate (run_id, seq).
func (q *Queries) InsertRunMessage(ctx context.Context, arg InsertRunMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRunMessage,
		arg.RunID,
		arg.Seq,
		arg.Kind,
		arg.Agent,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveRunsAll = `-- name: ListActiveRunsAll :many
SELECT r.id, r.user_id, r.repo_id, r.issue_iid, r.issue_title, r.issue_description, r.status, r.requeue_count, r.worker_id, r.session_id, r.last_seq, r.branch, r.mr_iid, r.failure_reason, r.plan_md, r.iteration_count, r.claimed_at, r.started_at, r.finished_at, r.created_at, r.updated_at, r.origin_column, r.board_column, r.move_pending_since, r.mr_state, r.auto_approve, r.autopilot_commented_at, r.kind, r.pipeline_id, r.pipeline_ref, r.failure_snapshot, r.fix_verdict, r.stop_kind, r.agent_source, r.agent_exclusions, r.repo_agents, r.title, r.resume_of_run_id, r.target_run_id, rp.path_with_namespace AS repo_path, w.name AS worker_name, u.email AS owner_email
FROM runs r
JOIN repos rp ON rp.id = r.repo_id
LEFT JOIN workers w ON w.id = r.worker_id
JOIN users u ON u.id = r.user_id
WHERE r.status NOT IN ('completed', 'failed', 'cancelled')
  AND r.kind <> 'chat'
ORDER BY r.created_at DESC
LIMIT 500
`

type ListActiveRunsAllRow struct {
	Run        Run         `json:"run"`
	RepoPath   string      `json:"repo_path"`
	WorkerName pgtype.Text `json:"worker_name"`
	OwnerEmail string      `json:"owner_email"`
}

// Admin Agents-status: every non-terminal run across all users, with repo path,
// worker name, and owner email for the admin overview.
func (q *Queries) ListActiveRunsAll(ctx context.Context) ([]ListActiveRunsAllRow, error) {
	rows, err := q.db.Query(ctx, listActiveRunsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRunsAllRow{}
	for rows.Next() {
		var i ListActiveRunsAllRow
		if err := rows.Scan(
			&i.Run.ID,
			&i.Run.UserID,
			&i.Run.RepoID,
			&i.Run.IssueIid,
			&i.Run.IssueTitle,
			&i.Run.IssueDescription,
			&i.Run.Status,
			&i.Run.RequeueCount,
			&i.Run.WorkerID,
			&i.Run.SessionID,
			&i.Run.LastSeq,
			&i.Run.Branch,
			&i.Run.MrIid,
			&i.Run.FailureReason,
			&i.Run.PlanMd,
			&i.Run.IterationCount,
			&i.Run.ClaimedAt,
			&i.Run.StartedAt,
			&i.Run.FinishedAt,
			&i.Run.CreatedAt,
			&i.Run.UpdatedAt,
			&i.Run.OriginColumn,
			&i.Run.BoardColumn,
			&i.Run.MovePendingSince,
			&i.Run.MrState,
			&i.Run.AutoApprove,
			&i.Run.AutopilotCommentedAt,
			&i.Run.Kind,
			&i.Run.PipelineID,
			&i.Run.PipelineRef,
			&i.Run.FailureSnapshot,
			&i.Run.FixVerdict,
			&i.Run.StopKind,
			&i.Run.AgentSource,
			&i.Run.AgentExclusions,
			&i.Run.RepoAgents,
			&i.Run.Title,
			&i.Run.ResumeOfRunID,
			&i.Run.TargetRunID,
			&i.RepoPath,
			&i.WorkerName,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWorkers = `-- name: ListAllWorkers :many
SELECT w.id, w.user_id, w.name, w.token_hash, w.status, w.last_heartbeat_at, w.version, w.created_at, w.updated_at, w.template_declared, w.template_reported, w.max_concurrent_runs,
       EXISTS (
           SELECT 1 FROM runs r
           WHERE r.worker_id = w.id
             AND r.status IN ('claimed', 'running', 'awaiting_approval')
       ) AS busy,
       (
           SELECT count(*) FROM runs r
           WHERE r.worker_id = w.id
             AND r.status IN ('claimed', 'running', 'awaiting_approval')
             AND r.kind <> 'chat'
       ) AS active_runs,
       u.email AS owner_email
FROM workers w
JOIN users u ON u.id = w.user_id
ORDER BY w.created_at DESC
`

type ListAllWorkersRow struct {
	Worker     Worker `json:"worker"`
	Busy       bool   `json:"busy"`
	ActiveRuns int64  `json:"active_runs"`
	OwnerEmail string `json:"owner_email"`
}

// Admin Agents-status: every worker with owner email plus the same two derived
// signals as ListWorkersByUser (PRD #42 Decision 10): busy is the ANY-kind
// non-terminal EXISTS, active_runs is the NON-CHAT active count (chat runs are
// excluded so a live chat never inflates "N/M runs" past the run-lane cap). The
// embedded worker carries max_concurrent_runs (the advertised cap, NULL when
// unadvertised).
func (q *Queries) ListAllWorkers(ctx context.Context) ([]ListAllWorkersRow, error) {
	rows, err := q.db.Query(ctx, listAllWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllWorkersRow{}
	for rows.Next() {
		var i ListAllWorkersRow
		if err := rows.Scan(
			&i.Worker.ID,
			&i.Worker.UserID,
			&i.Worker.Name,
			&i.Worker.TokenHash,
			&i.Worker.Status,
			&i.Worker.LastHeartbeatAt,
			&i.Worker.Version,
			&i.Worker.CreatedAt,
			&i.Worker.UpdatedAt,
			&i.Worker.TemplateDeclared,
			&i.Worker.TemplateReported,
			&i.Worker.MaxConcurrentRuns,
			&i.Busy,
			&i.ActiveRuns,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGaveUpColumnMoves = `-- name: ListGaveUpColumnMoves :many
SELECT r.id, r.repo_id, r.issue_iid, r.status, r.move_pending_since
FROM runs r
WHERE r.move_pending_since IS NOT NULL
  AND r.move_pending_since <= $1
  AND r.move_pending_since > $2
ORDER BY r.move_pending_since ASC
LIMIT 100
`

type ListGaveUpColumnMovesParams struct {
	GiveupCutoff pgtype.Timestamptz `json:"giveup_cutoff"`
	PriorCutoff  pgtype.Timestamptz `json:"prior_cutoff"`
}

type ListGaveUpColumnMovesRow struct {
	ID               uuid.UUID          `json:"id"`
	RepoID           pgtype.UUID        `json:"repo_id"`
	IssueIid         pgtype.Int8        `json:"issue_iid"`
	Status           string             `json:"status"`
	MovePendingSince pgtype.Timestamptz `json:"move_pending_since"`
}

// Runs whose pending marker crossed the 30-minute give-up boundary during the
// last reconcile interval, for a one-shot warn log. The marker is deliberately
// NOT cleared (a silent clear would hide the drift behind a correct-looking
// badge); the next transition or manual drag clears it.
func (q *Queries) ListGaveUpColumnMoves(ctx context.Context, arg ListGaveUpColumnMovesParams) ([]ListGaveUpColumnMovesRow, error) {
	rows, err := q.db.Query(ctx, listGaveUpColumnMoves, arg.GiveupCutoff, arg.PriorCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGaveUpColumnMovesRow{}
	for rows.Next() {
		var i ListGaveUpColumnMovesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.IssueIid,
			&i.Status,
			&i.MovePendingSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingColumnMoves = `-- name: ListPendingColumnMoves :many
SELECT id FROM runs
WHERE move_pending_since IS NOT NULL
  AND move_pending_since <= $1
  AND move_pending_since > $2
ORDER BY move_pending_since ASC
LIMIT $3
`

type ListPendingColumnMovesParams struct {
	GraceCutoff  pgtype.Timestamptz `json:"grace_cutoff"`
	GiveupCutoff pgtype.Timestamptz `json:"giveup_cutoff"`
	MaxBatch     int32              `json:"max_batch"`
}

// Reconcile-loop candidates: runs with a pending column move that is older than a
// short grace (so the inline move is not raced) and still inside the 30-minute
// retry window (older markers have been given up on and are deliberately left
// set). Only the id is returned — the loop re-reads each run's full context
// (GetRunMoveContext) immediately before the write to narrow the clobber window
// against a concurrent manual drag.
func (q *Queries) ListPendingColumnMoves(ctx context.Context, arg ListPendingColumnMovesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPendingColumnMoves, arg.GraceCutoff, arg.GiveupCutoff, arg.MaxBatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunMessagesAfter = `-- name: ListRunMessagesAfter :many
SELECT id, run_id, seq, kind, agent, payload, created_at
FROM run_messages
WHERE run_id = $1 AND seq > $2
ORDER BY seq ASC
`

type ListRunMessagesAfterParams struct {
	RunID    uuid.UUID `json:"run_id"`
	AfterSeq int32     `json:"after_seq"`
}

// Replay for a (re)connecting browser: everything after its last-seen seq, in
// order. The persisted log is authoritative; the WS layer (M5) is only a live
// cache on top of this.
func (q *Queries) ListRunMessagesAfter(ctx context.Context, arg ListRunMessagesAfterParams) ([]RunMessage, error) {
	rows, err := q.db.Query(ctx, listRunMessagesAfter, arg.RunID, arg.AfterSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunMessage{}
	for rows.Next() {
		var i RunMessage
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.Kind,
			&i.Agent,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunMessagesForWorkerPage = `-- name: ListRunMessagesForWorkerPage :many
SELECT id, run_id, seq, kind, agent, payload, created_at
FROM run_messages
WHERE run_id = $1 AND seq > $2
ORDER BY seq ASC
LIMIT $3
`

type ListRunMessagesForWorkerPageParams struct {
	RunID    uuid.UUID `json:"run_id"`
	AfterSeq int32     `json:"after_seq"`
	Lim      int32     `json:"lim"`
}

// A bounded page of a run's messages after a seq (the worker read tool's paging).
// Authorization (the run is the worker's user's) is checked by the caller before
// this; here @lim caps the page so a single response can't be unbounded.
func (q *Queries) ListRunMessagesForWorkerPage(ctx context.Context, arg ListRunMessagesForWorkerPageParams) ([]RunMessage, error) {
	rows, err := q.db.Query(ctx, listRunMessagesForWorkerPage, arg.RunID, arg.AfterSeq, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunMessage{}
	for rows.Next() {
		var i RunMessage
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.Kind,
			&i.Agent,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForUser = `-- name: ListRunsForUser :many
SELECT r.id, r.user_id, r.repo_id, r.issue_iid, r.issue_title, r.issue_description, r.status, r.requeue_count, r.worker_id, r.session_id, r.last_seq, r.branch, r.mr_iid, r.failure_reason, r.plan_md, r.iteration_count, r.claimed_at, r.started_at, r.finished_at, r.created_at, r.updated_at, r.origin_column, r.board_column, r.move_pending_since, r.mr_state, r.auto_approve, r.autopilot_commented_at, r.kind, r.pipeline_id, r.pipeline_ref, r.failure_snapshot, r.fix_verdict, r.stop_kind, r.agent_source, r.agent_exclusions, r.repo_agents, r.title, r.resume_of_run_id, r.target_run_id, rp.path_with_namespace AS repo_path, w.name AS worker_name
FROM runs r
JOIN repos rp ON rp.id = r.repo_id
LEFT JOIN workers w ON w.id = r.worker_id
WHERE r.user_id = $1
  AND r.kind <> 'chat'
  AND ($2::uuid IS NULL OR r.repo_id = $2)
  AND ($3::bigint IS NULL OR r.issue_iid = $3)
ORDER BY r.created_at DESC
LIMIT 200
`

type ListRunsForUserParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	RepoID   pgtype.UUID `json:"repo_id"`
	IssueIid pgtype.Int8 `json:"issue_iid"`
}

type ListRunsForUserRow struct {
	Run        Run         `json:"run"`
	RepoPath   string      `json:"repo_path"`
	WorkerName pgtype.Text `json:"worker_name"`
}

// The user's runs, newest first (Runs index + Agents-status "your runs"), joined
// to the repo path and the nullable worker name for display. The optional
// repo_id / issue_iid narrowings (PRD #12 M2) serve the board attention strip
// (repo scope) and the in-app issue history (repo + issue); when both are NULL
// this is the unchanged full list. The per-issue narrowing rides the composite
// index runs (repo_id, issue_iid, created_at DESC).
func (q *Queries) ListRunsForUser(ctx context.Context, arg ListRunsForUserParams) ([]ListRunsForUserRow, error) {
	rows, err := q.db.Query(ctx, listRunsForUser, arg.UserID, arg.RepoID, arg.IssueIid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsForUserRow{}
	for rows.Next() {
		var i ListRunsForUserRow
		if err := rows.Scan(
			&i.Run.ID,
			&i.Run.UserID,
			&i.Run.RepoID,
			&i.Run.IssueIid,
			&i.Run.IssueTitle,
			&i.Run.IssueDescription,
			&i.Run.Status,
			&i.Run.RequeueCount,
			&i.Run.WorkerID,
			&i.Run.SessionID,
			&i.Run.LastSeq,
			&i.Run.Branch,
			&i.Run.MrIid,
			&i.Run.FailureReason,
			&i.Run.PlanMd,
			&i.Run.IterationCount,
			&i.Run.ClaimedAt,
			&i.Run.StartedAt,
			&i.Run.FinishedAt,
			&i.Run.CreatedAt,
			&i.Run.UpdatedAt,
			&i.Run.OriginColumn,
			&i.Run.BoardColumn,
			&i.Run.MovePendingSince,
			&i.Run.MrState,
			&i.Run.AutoApprove,
			&i.Run.AutopilotCommentedAt,
			&i.Run.Kind,
			&i.Run.PipelineID,
			&i.Run.PipelineRef,
			&i.Run.FailureSnapshot,
			&i.Run.FixVerdict,
			&i.Run.StopKind,
			&i.Run.AgentSource,
			&i.Run.AgentExclusions,
			&i.Run.RepoAgents,
			&i.Run.Title,
			&i.Run.ResumeOfRunID,
			&i.Run.TargetRunID,
			&i.RepoPath,
			&i.WorkerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForWorkerUser = `-- name: ListRunsForWorkerUser :many

SELECT r.id, r.kind, r.status, r.issue_iid, r.issue_title, r.branch, r.mr_iid,
       r.failure_reason, r.created_at, r.updated_at,
       rp.path_with_namespace AS repo_path, rp.web_url AS repo_web_url
FROM runs r
LEFT JOIN repos rp ON rp.id = r.repo_id
WHERE r.user_id = $1
ORDER BY r.created_at DESC
LIMIT $2
`

type ListRunsForWorkerUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Lim    int32     `json:"lim"`
}

type ListRunsForWorkerUserRow struct {
	ID            uuid.UUID          `json:"id"`
	Kind          string             `json:"kind"`
	Status        string             `json:"status"`
	IssueIid      pgtype.Int8        `json:"issue_iid"`
	IssueTitle    string             `json:"issue_title"`
	Branch        pgtype.Text        `json:"branch"`
	MrIid         pgtype.Int8        `json:"mr_iid"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	RepoPath      pgtype.Text        `json:"repo_path"`
	RepoWebUrl    pgtype.Text        `json:"repo_web_url"`
}

// Worker chat read surface (PRD #39 M3, Decision 7) --------------------------
// The chat agent investigates its OWNER'S runs (both kinds) via the worker. These
// queries are USER_ID-scoped (from the authenticated worker), NEVER a bare run_id
// lookup — a compromised worker still reads only its own user's runs, and a foreign
// run id simply returns no row (404). repo_web_url rides along so the handler can
// build the MR URL; a chat run has no repo, so repo fields are NULL (LEFT JOIN).
// Compact list of the worker's user's runs, newest first, bounded by @lim.
func (q *Queries) ListRunsForWorkerUser(ctx context.Context, arg ListRunsForWorkerUserParams) ([]ListRunsForWorkerUserRow, error) {
	rows, err := q.db.Query(ctx, listRunsForWorkerUser, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsForWorkerUserRow{}
	for rows.Next() {
		var i ListRunsForWorkerUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.IssueIid,
			&i.IssueTitle,
			&i.Branch,
			&i.MrIid,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepoPath,
			&i.RepoWebUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersByUser = `-- name: ListWorkersByUser :many
SELECT w.id, w.user_id, w.name, w.token_hash, w.status, w.last_heartbeat_at, w.version, w.created_at, w.updated_at, w.template_declared, w.template_reported, w.max_concurrent_runs,
       EXISTS (
           SELECT 1 FROM runs r
           WHERE r.worker_id = w.id
             AND r.status IN ('claimed', 'running', 'awaiting_approval')
       ) AS busy,
       (
           SELECT count(*) FROM runs r
           WHERE r.worker_id = w.id
             AND r.status IN ('claimed', 'running', 'awaiting_approval')
             AND r.kind <> 'chat'
       ) AS active_runs
FROM workers w
WHERE w.user_id = $1
ORDER BY w.created_at ASC
`

type ListWorkersByUserRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Name              string             `json:"name"`
	TokenHash         []byte             `json:"token_hash"`
	Status            string             `json:"status"`
	LastHeartbeatAt   pgtype.Timestamptz `json:"last_heartbeat_at"`
	Version           pgtype.Text        `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TemplateDeclared  pgtype.Text        `json:"template_declared"`
	TemplateReported  pgtype.Text        `json:"template_reported"`
	MaxConcurrentRuns pgtype.Int4        `json:"max_concurrent_runs"`
	Busy              bool               `json:"busy"`
	ActiveRuns        int64              `json:"active_runs"`
}

// Worker list for the owning user. Two derived signals (PRD #42 Decision 10):
//   - active_runs counts the worker's NON-CHAT active runs (claimed/running/
//     awaiting_approval) — the RUN lane that max_concurrent_runs bounds. Chat runs
//     have their own session budget (WORKER_CHAT_SESSIONS) and ClaimRun excludes
//     them, so counting a live chat here would render a false "3/2 runs" over-cap.
//   - busy is the ANY-kind non-terminal signal (a lone active chat still shows the
//     worker as busy), so it is its own EXISTS over every kind — NOT derived from
//     active_runs, which now omits chat.
//
// max_concurrent_runs (the advertised cap, NULL when unadvertised) rides on w.*; it
// is observability only and never enforced.
func (q *Queries) ListWorkersByUser(ctx context.Context, userID uuid.UUID) ([]ListWorkersByUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkersByUserRow{}
	for rows.Next() {
		var i ListWorkersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Status,
			&i.LastHeartbeatAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateDeclared,
			&i.TemplateReported,
			&i.MaxConcurrentRuns,
			&i.Busy,
			&i.ActiveRuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunFailedByID = `-- name: MarkRunFailedByID :execrows
UPDATE runs SET
    status             = 'failed',
    failure_reason     = $1,
    move_pending_since = now(),
    finished_at        = now(),
    updated_at         = now()
WHERE id = $2
  AND status NOT IN ('completed', 'failed', 'cancelled')
`

type MarkRunFailedByIDParams struct {
	FailureReason pgtype.Text `json:"failure_reason"`
	ID            uuid.UUID   `json:"id"`
}

// Service-internal fail (e.g. a claim whose secrets are missing/undecryptable):
// the run was just claimed by this worker but cannot run. failed → origin
// restore, so it stamps move_pending_since like the other failed paths.
func (q *Queries) MarkRunFailedByID(ctx context.Context, arg MarkRunFailedByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRunFailedByID, arg.FailureReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markStaleWorkersOffline = `-- name: MarkStaleWorkersOffline :execrows
UPDATE workers SET status = 'offline', updated_at = now()
WHERE status = 'online'
  AND (last_heartbeat_at IS NULL OR last_heartbeat_at < $1)
`

// Sweeper: workers past the heartbeat-stale window go offline.
func (q *Queries) MarkStaleWorkersOffline(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, markStaleWorkersOffline, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordRunColumnMove = `-- name: RecordRunColumnMove :execrows
UPDATE runs SET board_column = $1, move_pending_since = NULL, updated_at = now()
WHERE id = $2
`

type RecordRunColumnMoveParams struct {
	BoardColumn pgtype.Text `json:"board_column"`
	ID          uuid.UUID   `json:"id"`
}

// A successful automation move: record the column just applied (board_column) and
// clear the pending marker in one statement.
func (q *Queries) RecordRunColumnMove(ctx context.Context, arg RecordRunColumnMoveParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordRunColumnMove, arg.BoardColumn, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registerWorker = `-- name: RegisterWorker :one
UPDATE workers SET
    status              = 'online',
    version             = $1,
    template_reported   = $2,
    max_concurrent_runs = $3,
    last_heartbeat_at   = now(),
    updated_at          = now()
WHERE id = $4
RETURNING id, user_id, name, token_hash, status, last_heartbeat_at, version, created_at, updated_at, template_declared, template_reported, max_concurrent_runs
`

type RegisterWorkerParams struct {
	Version           pgtype.Text `json:"version"`
	TemplateReported  pgtype.Text `json:"template_reported"`
	MaxConcurrentRuns pgtype.Int4 `json:"max_concurrent_runs"`
	ID                uuid.UUID   `json:"id"`
}

// Worker announces version + its self-reported template and comes online;
// heartbeat is stamped now. template_reported is what the image bakes in (PRD
// #18), NULL when the worker sends none (older image) — stored as-is; drift vs
// template_declared is surfaced, never rejected. max_concurrent_runs is the worker's
// advertised slot cap (PRD #42 Decisions 3 & 10), likewise self-reported: NULL when
// the worker advertises none (an older image, or before the M2 agent sends it), and
// overwritten to the current report on every register (the fresh-start signal). It is
// observability only — the server never enforces it.
func (q *Queries) RegisterWorker(ctx context.Context, arg RegisterWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, registerWorker,
		arg.Version,
		arg.TemplateReported,
		arg.MaxConcurrentRuns,
		arg.ID,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateDeclared,
		&i.TemplateReported,
		&i.MaxConcurrentRuns,
	)
	return i, err
}

const rejectRunServerSide = `-- name: RejectRunServerSide :execrows
UPDATE runs SET status = 'failed', stop_kind = 'plan_rejected', failure_reason = $1, move_pending_since = now(), finished_at = now(), updated_at = now()
WHERE id = $2 AND user_id = $3
  AND status NOT IN ('completed', 'failed', 'cancelled')
`

type RejectRunServerSideParams struct {
	FailureReason pgtype.Text `json:"failure_reason"`
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
}

// Server-side plan rejection → failed → origin restore → stamp. stop_kind is
// stamped 'plan_rejected' in the same statement as the status/failure_reason write
// (PRD #33 Decision 3), so this failed run is recognised as a deliberate stop
// regardless of the failure_reason text.
func (q *Queries) RejectRunServerSide(ctx context.Context, arg RejectRunServerSideParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectRunServerSide, arg.FailureReason, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueClaimedRunToQueued = `-- name: RequeueClaimedRunToQueued :execrows
UPDATE runs SET status = 'queued', updated_at = now()
WHERE id = $1 AND status = 'claimed'
`

// Vault lock race (PRD #32 M3): a run claimed while the owner's vault was
// unlocked, then locked before assembleClaim could open the Anthropic token.
// Reset it to queued — NOT failed, which is terminal (MarkRunFailedByID) and
// would violate "a locked owner's run waits, never fails". worker_id is left
// intact for resume affinity. Guarded on status='claimed' so a run that a
// concurrent path already advanced is untouched. Mirrors
// SweepClaimedNeverStarted but targets exactly one run by id. Stays :execrows
// (not :many like the sweeps): this runs on the claim path, not the sweeper, and
// deliberately does not broadcast the claimed→queued transition (matching the
// reviewed PRD #32 M3 behavior — it is a rare lock-race requeue, not a sweep).
func (q *Queries) RequeueClaimedRunToQueued(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, requeueClaimedRunToQueued, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueRunsOfStaleWorkers = `-- name: RequeueRunsOfStaleWorkers :many
UPDATE runs SET status = 'queued', requeue_count = requeue_count + 1, updated_at = now()
WHERE status IN ('claimed', 'running', 'awaiting_approval')
  AND requeue_count < $1
  AND worker_id IN (
      SELECT id FROM workers WHERE last_heartbeat_at IS NULL OR last_heartbeat_at < $2
  )
RETURNING id, user_id, status
`

type RequeueRunsOfStaleWorkersParams struct {
	MaxRequeues int32              `json:"max_requeues"`
	Cutoff      pgtype.Timestamptz `json:"cutoff"`
}

type RequeueRunsOfStaleWorkersRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

// A stale worker's non-terminal run within its re-queue budget → back to queued
// (worker_id kept for affinity, requeue_count incremented).
func (q *Queries) RequeueRunsOfStaleWorkers(ctx context.Context, arg RequeueRunsOfStaleWorkersParams) ([]RequeueRunsOfStaleWorkersRow, error) {
	rows, err := q.db.Query(ctx, requeueRunsOfStaleWorkers, arg.MaxRequeues, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequeueRunsOfStaleWorkersRow{}
	for rows.Next() {
		var i RequeueRunsOfStaleWorkersRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueWorkerRuns = `-- name: RequeueWorkerRuns :execrows
UPDATE runs SET status = 'queued', requeue_count = requeue_count + 1, updated_at = now()
WHERE worker_id = $1
  AND status IN ('claimed', 'running', 'awaiting_approval')
  AND requeue_count < $2
`

type RequeueWorkerRunsParams struct {
	WorkerID    pgtype.UUID `json:"worker_id"`
	MaxRequeues int32       `json:"max_requeues"`
}

// Within budget → re-queued to this same worker (affinity), which then re-claims
// and resumes from the persisted session (handles docker compose down && up).
func (q *Queries) RequeueWorkerRuns(ctx context.Context, arg RequeueWorkerRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueWorkerRuns, arg.WorkerID, arg.MaxRequeues)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRunAwaitingApproval = `-- name: SetRunAwaitingApproval :execrows
UPDATE runs SET
    status     = 'awaiting_approval',
    plan_md    = $1,
    session_id = COALESCE($2, session_id),
    updated_at = now()
WHERE id = $3 AND worker_id = $4
  AND status NOT IN ('completed', 'failed', 'cancelled')
`

type SetRunAwaitingApprovalParams struct {
	PlanMd    pgtype.Text `json:"plan_md"`
	SessionID pgtype.Text `json:"session_id"`
	ID        uuid.UUID   `json:"id"`
	WorkerID  pgtype.UUID `json:"worker_id"`
}

func (q *Queries) SetRunAwaitingApproval(ctx context.Context, arg SetRunAwaitingApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRunAwaitingApproval,
		arg.PlanMd,
		arg.SessionID,
		arg.ID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRunCompleted = `-- name: SetRunCompleted :execrows
UPDATE runs SET
    status             = 'completed',
    branch             = $1,
    mr_iid             = $2,
    session_id         = COALESCE($3, session_id),
    -- fix_verdict carries a ci_fix run's outbound 'not_code' verdict on completion
    -- (PRD #6); NULL for every issue run and for a ci_fix that produced a fix (its
    -- verdict is stamped verified/fix_failed later by the pipeline sync).
    fix_verdict        = COALESCE($4, fix_verdict),
    move_pending_since = now(),
    finished_at        = now(),
    updated_at         = now()
WHERE id = $5 AND worker_id = $6
  AND status NOT IN ('completed', 'failed', 'cancelled')
`

type SetRunCompletedParams struct {
	Branch     pgtype.Text `json:"branch"`
	MrIid      pgtype.Int8 `json:"mr_iid"`
	SessionID  pgtype.Text `json:"session_id"`
	FixVerdict pgtype.Text `json:"fix_verdict"`
	ID         uuid.UUID   `json:"id"`
	WorkerID   pgtype.UUID `json:"worker_id"`
}

// completed is the terminal MR-opened event → Human Review. move_pending_since is
// stamped here (same statement as the status write) so a crash before the forge
// move still leaves the reconcile loop a marker to heal from.
func (q *Queries) SetRunCompleted(ctx context.Context, arg SetRunCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRunCompleted,
		arg.Branch,
		arg.MrIid,
		arg.SessionID,
		arg.FixVerdict,
		arg.ID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRunFailed = `-- name: SetRunFailed :execrows
UPDATE runs SET
    status             = 'failed',
    failure_reason     = $1,
    session_id         = COALESCE($2, session_id),
    move_pending_since = now(),
    finished_at        = now(),
    updated_at         = now()
WHERE id = $3 AND worker_id = $4
  AND status NOT IN ('completed', 'failed', 'cancelled')
`

type SetRunFailedParams struct {
	FailureReason pgtype.Text `json:"failure_reason"`
	SessionID     pgtype.Text `json:"session_id"`
	ID            uuid.UUID   `json:"id"`
	WorkerID      pgtype.UUID `json:"worker_id"`
}

// failed restores the origin column → move_pending_since stamped in the same
// statement (same-tx crash-window closure, as for completed).
func (q *Queries) SetRunFailed(ctx context.Context, arg SetRunFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRunFailed,
		arg.FailureReason,
		arg.SessionID,
		arg.ID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRunMRState = `-- name: SetRunMRState :execrows

UPDATE runs SET mr_state = $1, updated_at = now()
WHERE id = $2
`

type SetRunMRStateParams struct {
	MrState pgtype.Text `json:"mr_state"`
	ID      uuid.UUID   `json:"id"`
}

// MR-close watcher (PRD #24) --------------------------------------------------
// Record the merge-request state the watcher just observed for this run. This is
// the ONLY writer of runs.mr_state (the watcher-owned invariant, review finding
// 11): no run-status path writes it. The run itself stays terminal — closing an
// MR is review feedback, not a run-status event — so this touches mr_state (and
// updated_at) only.
func (q *Queries) SetRunMRState(ctx context.Context, arg SetRunMRStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRunMRState, arg.MrState, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRunRunning = `-- name: SetRunRunning :execrows
UPDATE runs SET
    status           = 'running',
    started_at       = COALESCE(started_at, now()),
    iteration_count  = GREATEST(iteration_count, $1),
    session_id       = COALESCE($2, session_id),
    repo_agents      = COALESCE($3::jsonb, repo_agents),
    agent_source     = COALESCE($4, agent_source),
    agent_exclusions = COALESCE($5::jsonb, agent_exclusions),
    updated_at       = now()
WHERE id = $6 AND worker_id = $7
  AND status NOT IN ('completed', 'failed', 'cancelled')
`

type SetRunRunningParams struct {
	IterationCount  int32       `json:"iteration_count"`
	SessionID       pgtype.Text `json:"session_id"`
	RepoAgents      []byte      `json:"repo_agents"`
	AgentSource     pgtype.Text `json:"agent_source"`
	AgentExclusions []byte      `json:"agent_exclusions"`
	ID              uuid.UUID   `json:"id"`
	WorkerID        pgtype.UUID `json:"worker_id"`
}

// claimed/awaiting_approval → running, AND running → running: the worker reports
// this state more than once per run (once on claim, again after checkout with the
// repo agent roster, again on every session-id/iteration heartbeat), so the
// statement is idempotent by construction. started_at is stamped once;
// iteration_count only advances (GREATEST) so a resume never regresses the loop
// counter. A terminal run (e.g. cancelled) is left untouched → 0 rows → "already
// terminal".
//
// The three PRD #37 columns are COALESCE'd against their own value, so a report
// that omits them (the common case) preserves what a previous report wrote and no
// caller has to read-modify-write. repo_agents is set once, by the post-checkout
// report; agent_source/agent_exclusions only by an AUTOPILOT run's report (a
// human-gated run persists its selection through CreateApprovePlanInput instead).
// Consequence, deliberate: a worker can never NULL these back out — an empty
// roster is reported as '[]', which is a distinct, meaningful value.
func (q *Queries) SetRunRunning(ctx context.Context, arg SetRunRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRunRunning,
		arg.IterationCount,
		arg.SessionID,
		arg.RepoAgents,
		arg.AgentSource,
		arg.AgentExclusions,
		arg.ID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepClaimedNeverStarted = `-- name: SweepClaimedNeverStarted :many

UPDATE runs SET status = 'queued', updated_at = now()
WHERE status = 'claimed' AND claimed_at < $1
RETURNING id, user_id, status
`

type SweepClaimedNeverStartedRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

// Sweeper: run-level timeouts and worker-loss recovery -----------------------
// claimed but never started past the grace window → back to queued (worker_id
// kept for affinity so the same disk reclaims it). RETURNING id, user_id, status
// so the sweeper can publish each transition through the broadcaster/notifier
// fan-out (PRD #25 M3: sweeper-driven transitions were previously silent).
func (q *Queries) SweepClaimedNeverStarted(ctx context.Context, cutoff pgtype.Timestamptz) ([]SweepClaimedNeverStartedRow, error) {
	rows, err := q.db.Query(ctx, sweepClaimedNeverStarted, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SweepClaimedNeverStartedRow{}
	for rows.Next() {
		var i SweepClaimedNeverStartedRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweepRunningTimeout = `-- name: SweepRunningTimeout :many
UPDATE runs SET status = 'failed', failure_reason = $1, move_pending_since = now(), finished_at = now(), updated_at = now()
WHERE status = 'running' AND started_at < $2 AND kind <> 'chat'
RETURNING id, user_id, status
`

type SweepRunningTimeoutParams struct {
	FailureReason pgtype.Text        `json:"failure_reason"`
	Cutoff        pgtype.Timestamptz `json:"cutoff"`
}

type SweepRunningTimeoutRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

// running past RUN_TIMEOUT → failed (a hung agent is failed without a human).
// Stamps move_pending_since so the (forge-free) sweep leaves the isolated
// reconcile loop a marker to restore the origin column later. Chat runs are exempt
// (Decision 3): a chat legitimately parks for a long time between turns, so its own
// idle/turn clocks (SweepIdleChatRuns + the worker-side timers) bound it instead.
func (q *Queries) SweepRunningTimeout(ctx context.Context, arg SweepRunningTimeoutParams) ([]SweepRunningTimeoutRow, error) {
	rows, err := q.db.Query(ctx, sweepRunningTimeout, arg.FailureReason, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SweepRunningTimeoutRow{}
	for rows.Next() {
		var i SweepRunningTimeoutRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunLastSeq = `-- name: UpdateRunLastSeq :execrows
UPDATE runs SET last_seq = GREATEST(last_seq, $1)
WHERE id = $2
`

type UpdateRunLastSeqParams struct {
	Seq int32     `json:"seq"`
	ID  uuid.UUID `json:"id"`
}

// Advance the message high-water mark (never regresses).
func (q *Queries) UpdateRunLastSeq(ctx context.Context, arg UpdateRunLastSeqParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRunLastSeq, arg.Seq, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
