// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskReviewRun = `-- name: CreateTaskReviewRun :one
INSERT INTO runs (
    id, user_id, repo_id, kind, branch, base_branch,
    review_target_run_id, dispatched_at, auto_approve, open_mr, review_requested,
    issue_title, issue_description
)
VALUES (
    $1, $2, $3::uuid, 'task', $4, $5,
    $6, now(), true, false, false,
    $7, ''
)
RETURNING id, user_id, repo_id, issue_iid, issue_title, issue_description, status, requeue_count, worker_id, session_id, last_seq, branch, mr_iid, failure_reason, plan_md, iteration_count, claimed_at, started_at, finished_at, created_at, updated_at, origin_column, board_column, move_pending_since, mr_state, auto_approve, autopilot_commented_at, kind, pipeline_id, pipeline_ref, failure_snapshot, fix_verdict, stop_kind, agent_source, agent_exclusions, repo_agents, title, resume_of_run_id, last_activity_at, health, health_reason, health_since, health_notified_at, target_run_id, mr_web_url, prd_done_path, prd_patch_settled_at, anthropic_secret_id, anthropic_secret_label, anthropic_select_reason, anthropic_headroom_pct, wait_on_limit, limit_resets_at, retry_not_before, limit_wait_count, rate_limit_type, open_question_id, revise_count, plan_source, planned_base_commit, require_base_match, milestones_candidate, milestones_frozen, milestones_completed, milestones_in_progress, budget_max_iterations, budget_wall_seconds, schedule_id, limit_dead_secret_id, report_only, report_md, ci_config_paths, model, override_subagent_model, fail_origin, priority, summary_intent, summary_plan, summary_deltas, issue_comments, base_branch, open_mr, dispatched_at, review_target_run_id, review_requested, then_fix_requested, then_fix_of_run_id, preserved_patch, required_capabilities, stop_reason, required_tools, size_class
`

type CreateTaskReviewRunParams struct {
	RunID       uuid.UUID   `json:"run_id"`
	UserID      uuid.UUID   `json:"user_id"`
	RepoID      uuid.UUID   `json:"repo_id"`
	Branch      pgtype.Text `json:"branch"`
	BaseBranch  pgtype.Text `json:"base_branch"`
	TargetRunID pgtype.UUID `json:"target_run_id"`
	IssueTitle  string      `json:"issue_title"`
}

// The dedicated insert for a REVIEW run (PRD #400 M4a): a task run that IS a review of
// another task. It carries the SAME task shape (repo-ful, issue-less, branch set at
// create) but is distinguished by a non-null review_target_run_id — the worker (M4b)
// routes such a claim to a diff-review executor. The branch is the REVIEWED TARGET's
// branch (the review clones it and diffs against base_branch); dispatched_at is stamped
// now() so it is immediately claimable — unlike a plain handoff a review needs no CLI seed
// push (the target branch is already pushed). auto_approve is baked true (no plan gate);
// open_mr false (a review only reports); review_requested false (a review NEVER spawns a
// review — no recursion). id is caller-supplied so Go derives the uzi/task/<id> namespace
// invariant the same way CreateTaskRun does. The uq_one_active_task_review_per_target
// partial unique index makes a duplicate active review raise 23505.
func (q *Queries) CreateTaskReviewRun(ctx context.Context, arg CreateTaskReviewRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createTaskReviewRun,
		arg.RunID,
		arg.UserID,
		arg.RepoID,
		arg.Branch,
		arg.BaseBranch,
		arg.TargetRunID,
		arg.IssueTitle,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.IssueIid,
		&i.IssueTitle,
		&i.IssueDescription,
		&i.Status,
		&i.RequeueCount,
		&i.WorkerID,
		&i.SessionID,
		&i.LastSeq,
		&i.Branch,
		&i.MrIid,
		&i.FailureReason,
		&i.PlanMd,
		&i.IterationCount,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.MrState,
		&i.AutoApprove,
		&i.AutopilotCommentedAt,
		&i.Kind,
		&i.PipelineID,
		&i.PipelineRef,
		&i.FailureSnapshot,
		&i.FixVerdict,
		&i.StopKind,
		&i.AgentSource,
		&i.AgentExclusions,
		&i.RepoAgents,
		&i.Title,
		&i.ResumeOfRunID,
		&i.LastActivityAt,
		&i.Health,
		&i.HealthReason,
		&i.HealthSince,
		&i.HealthNotifiedAt,
		&i.TargetRunID,
		&i.MrWebUrl,
		&i.PrdDonePath,
		&i.PrdPatchSettledAt,
		&i.AnthropicSecretID,
		&i.AnthropicSecretLabel,
		&i.AnthropicSelectReason,
		&i.AnthropicHeadroomPct,
		&i.WaitOnLimit,
		&i.LimitResetsAt,
		&i.RetryNotBefore,
		&i.LimitWaitCount,
		&i.RateLimitType,
		&i.OpenQuestionID,
		&i.ReviseCount,
		&i.PlanSource,
		&i.PlannedBaseCommit,
		&i.RequireBaseMatch,
		&i.MilestonesCandidate,
		&i.MilestonesFrozen,
		&i.MilestonesCompleted,
		&i.MilestonesInProgress,
		&i.BudgetMaxIterations,
		&i.BudgetWallSeconds,
		&i.ScheduleID,
		&i.LimitDeadSecretID,
		&i.ReportOnly,
		&i.ReportMd,
		&i.CiConfigPaths,
		&i.Model,
		&i.OverrideSubagentModel,
		&i.FailOrigin,
		&i.Priority,
		&i.SummaryIntent,
		&i.SummaryPlan,
		&i.SummaryDeltas,
		&i.IssueComments,
		&i.BaseBranch,
		&i.OpenMr,
		&i.DispatchedAt,
		&i.ReviewTargetRunID,
		&i.ReviewRequested,
		&i.ThenFixRequested,
		&i.ThenFixOfRunID,
		&i.PreservedPatch,
		&i.RequiredCapabilities,
		&i.StopReason,
		&i.RequiredTools,
		&i.SizeClass,
	)
	return i, err
}

const createTaskRun = `-- name: CreateTaskRun :one

INSERT INTO runs (id, user_id, repo_id, kind, branch, base_branch, open_mr, review_requested, then_fix_requested, issue_title, issue_description, auto_approve)
VALUES ($1, $2, $3::uuid, 'task', $4, $5, $6, $7, $8, $9, $10, true)
RETURNING id, user_id, repo_id, issue_iid, issue_title, issue_description, status, requeue_count, worker_id, session_id, last_seq, branch, mr_iid, failure_reason, plan_md, iteration_count, claimed_at, started_at, finished_at, created_at, updated_at, origin_column, board_column, move_pending_since, mr_state, auto_approve, autopilot_commented_at, kind, pipeline_id, pipeline_ref, failure_snapshot, fix_verdict, stop_kind, agent_source, agent_exclusions, repo_agents, title, resume_of_run_id, last_activity_at, health, health_reason, health_since, health_notified_at, target_run_id, mr_web_url, prd_done_path, prd_patch_settled_at, anthropic_secret_id, anthropic_secret_label, anthropic_select_reason, anthropic_headroom_pct, wait_on_limit, limit_resets_at, retry_not_before, limit_wait_count, rate_limit_type, open_question_id, revise_count, plan_source, planned_base_commit, require_base_match, milestones_candidate, milestones_frozen, milestones_completed, milestones_in_progress, budget_max_iterations, budget_wall_seconds, schedule_id, limit_dead_secret_id, report_only, report_md, ci_config_paths, model, override_subagent_model, fail_origin, priority, summary_intent, summary_plan, summary_deltas, issue_comments, base_branch, open_mr, dispatched_at, review_target_run_id, review_requested, then_fix_requested, then_fix_of_run_id, preserved_patch, required_capabilities, stop_reason, required_tools, size_class
`

type CreateTaskRunParams struct {
	RunID            uuid.UUID   `json:"run_id"`
	UserID           uuid.UUID   `json:"user_id"`
	RepoID           uuid.UUID   `json:"repo_id"`
	Branch           pgtype.Text `json:"branch"`
	BaseBranch       pgtype.Text `json:"base_branch"`
	OpenMr           bool        `json:"open_mr"`
	ReviewRequested  bool        `json:"review_requested"`
	ThenFixRequested bool        `json:"then_fix_requested"`
	IssueTitle       string      `json:"issue_title"`
	IssueDescription string      `json:"issue_description"`
}

// Task runs (PRD #400: uzi handoff) ------------------------------------------
// The dedicated insert for a kind='task' run (PRD #400): repo-ful, issue-less, and
// — uniquely — with its branch set AT CREATE. Modeled on CreatePromptRun
// (schedules.sql): a direct INSERT, not createRun, because a task run has no forge
// issue and no PRD link. Both id and branch are CALLER-SUPPLIED: the branch is the
// server-named uzi/task/<run-id>, so Go mints the UUID first and derives the branch
// from it, then hands both in (the caller-supplied-@run_id pattern CreateChatRun
// uses). auto_approve is baked true — handoff is the no-plan-gate "just do it" mode
// (like self_improve bakes it in), so it is deliberately NOT a parameter. base_branch
// is the optional source ref (sqlc.narg → NULL when absent); open_mr rides straight
// from the caller (--mr).
// review_requested rides from the caller (--review, PRD #400 M4a): set on this PLAIN task
// so that its terminal 'completed' transition auto-creates a diff-review run
// (maybeEnqueueTaskReview); false for an ordinary handoff.
// then_fix_requested rides from the caller (--then-fix, PRD #400 M5): set on this ORIGINAL
// task so that when its auto-spawned review run completes, maybeEnqueueThenFix composes the
// review findings into a fix run on the same branch; false for an ordinary handoff.
func (q *Queries) CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createTaskRun,
		arg.RunID,
		arg.UserID,
		arg.RepoID,
		arg.Branch,
		arg.BaseBranch,
		arg.OpenMr,
		arg.ReviewRequested,
		arg.ThenFixRequested,
		arg.IssueTitle,
		arg.IssueDescription,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.IssueIid,
		&i.IssueTitle,
		&i.IssueDescription,
		&i.Status,
		&i.RequeueCount,
		&i.WorkerID,
		&i.SessionID,
		&i.LastSeq,
		&i.Branch,
		&i.MrIid,
		&i.FailureReason,
		&i.PlanMd,
		&i.IterationCount,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.MrState,
		&i.AutoApprove,
		&i.AutopilotCommentedAt,
		&i.Kind,
		&i.PipelineID,
		&i.PipelineRef,
		&i.FailureSnapshot,
		&i.FixVerdict,
		&i.StopKind,
		&i.AgentSource,
		&i.AgentExclusions,
		&i.RepoAgents,
		&i.Title,
		&i.ResumeOfRunID,
		&i.LastActivityAt,
		&i.Health,
		&i.HealthReason,
		&i.HealthSince,
		&i.HealthNotifiedAt,
		&i.TargetRunID,
		&i.MrWebUrl,
		&i.PrdDonePath,
		&i.PrdPatchSettledAt,
		&i.AnthropicSecretID,
		&i.AnthropicSecretLabel,
		&i.AnthropicSelectReason,
		&i.AnthropicHeadroomPct,
		&i.WaitOnLimit,
		&i.LimitResetsAt,
		&i.RetryNotBefore,
		&i.LimitWaitCount,
		&i.RateLimitType,
		&i.OpenQuestionID,
		&i.ReviseCount,
		&i.PlanSource,
		&i.PlannedBaseCommit,
		&i.RequireBaseMatch,
		&i.MilestonesCandidate,
		&i.MilestonesFrozen,
		&i.MilestonesCompleted,
		&i.MilestonesInProgress,
		&i.BudgetMaxIterations,
		&i.BudgetWallSeconds,
		&i.ScheduleID,
		&i.LimitDeadSecretID,
		&i.ReportOnly,
		&i.ReportMd,
		&i.CiConfigPaths,
		&i.Model,
		&i.OverrideSubagentModel,
		&i.FailOrigin,
		&i.Priority,
		&i.SummaryIntent,
		&i.SummaryPlan,
		&i.SummaryDeltas,
		&i.IssueComments,
		&i.BaseBranch,
		&i.OpenMr,
		&i.DispatchedAt,
		&i.ReviewTargetRunID,
		&i.ReviewRequested,
		&i.ThenFixRequested,
		&i.ThenFixOfRunID,
		&i.PreservedPatch,
		&i.RequiredCapabilities,
		&i.StopReason,
		&i.RequiredTools,
		&i.SizeClass,
	)
	return i, err
}

const createThenFixRun = `-- name: CreateThenFixRun :one
INSERT INTO runs (
    id, user_id, repo_id, kind, branch, base_branch,
    then_fix_of_run_id, review_target_run_id, dispatched_at,
    auto_approve, open_mr, review_requested, then_fix_requested,
    issue_title, issue_description
)
VALUES (
    $1, $2, $3::uuid, 'task', $4, $5,
    $6, NULL, now(),
    true, false, false, false,
    $7, $8
)
RETURNING id, user_id, repo_id, issue_iid, issue_title, issue_description, status, requeue_count, worker_id, session_id, last_seq, branch, mr_iid, failure_reason, plan_md, iteration_count, claimed_at, started_at, finished_at, created_at, updated_at, origin_column, board_column, move_pending_since, mr_state, auto_approve, autopilot_commented_at, kind, pipeline_id, pipeline_ref, failure_snapshot, fix_verdict, stop_kind, agent_source, agent_exclusions, repo_agents, title, resume_of_run_id, last_activity_at, health, health_reason, health_since, health_notified_at, target_run_id, mr_web_url, prd_done_path, prd_patch_settled_at, anthropic_secret_id, anthropic_secret_label, anthropic_select_reason, anthropic_headroom_pct, wait_on_limit, limit_resets_at, retry_not_before, limit_wait_count, rate_limit_type, open_question_id, revise_count, plan_source, planned_base_commit, require_base_match, milestones_candidate, milestones_frozen, milestones_completed, milestones_in_progress, budget_max_iterations, budget_wall_seconds, schedule_id, limit_dead_secret_id, report_only, report_md, ci_config_paths, model, override_subagent_model, fail_origin, priority, summary_intent, summary_plan, summary_deltas, issue_comments, base_branch, open_mr, dispatched_at, review_target_run_id, review_requested, then_fix_requested, then_fix_of_run_id, preserved_patch, required_capabilities, stop_reason, required_tools, size_class
`

type CreateThenFixRunParams struct {
	RunID            uuid.UUID   `json:"run_id"`
	UserID           uuid.UUID   `json:"user_id"`
	RepoID           uuid.UUID   `json:"repo_id"`
	Branch           pgtype.Text `json:"branch"`
	BaseBranch       pgtype.Text `json:"base_branch"`
	ThenFixOfRunID   pgtype.UUID `json:"then_fix_of_run_id"`
	IssueTitle       string      `json:"issue_title"`
	IssueDescription string      `json:"issue_description"`
}

// The dedicated insert for a FIX run (PRD #400 M5): a NORMAL task run that pushes fixes,
// derived from a diff-review's findings, back to the ORIGINAL task's branch. It mirrors
// CreateTaskReviewRun's immediate-dispatch shape but is IMPLEMENT-mode, not review-mode:
// review_target_run_id is NULL (this is not a review — it is a plain task the worker
// implements-and-pushes), and then_fix_of_run_id points at the original task it fixes
// (provenance + the uq_one_active_then_fix_per_target dedup). branch is the ORIGINAL's
// uzi/task/<orig> branch (the fix pushes here, where the user pulls); base_branch is the
// original's base. dispatched_at = now() so it is immediately claimable — the branch
// already exists (the original + review both used it), so unlike a direct handoff a fix
// needs no CLI seed push. auto_approve true (no plan gate); open_mr false (a fix is still a
// throwaway handoff); review_requested + then_fix_requested false (no recursion — a fix is
// never itself reviewed or re-fixed). id is caller-supplied like CreateTaskReviewRun.
func (q *Queries) CreateThenFixRun(ctx context.Context, arg CreateThenFixRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createThenFixRun,
		arg.RunID,
		arg.UserID,
		arg.RepoID,
		arg.Branch,
		arg.BaseBranch,
		arg.ThenFixOfRunID,
		arg.IssueTitle,
		arg.IssueDescription,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.IssueIid,
		&i.IssueTitle,
		&i.IssueDescription,
		&i.Status,
		&i.RequeueCount,
		&i.WorkerID,
		&i.SessionID,
		&i.LastSeq,
		&i.Branch,
		&i.MrIid,
		&i.FailureReason,
		&i.PlanMd,
		&i.IterationCount,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.MrState,
		&i.AutoApprove,
		&i.AutopilotCommentedAt,
		&i.Kind,
		&i.PipelineID,
		&i.PipelineRef,
		&i.FailureSnapshot,
		&i.FixVerdict,
		&i.StopKind,
		&i.AgentSource,
		&i.AgentExclusions,
		&i.RepoAgents,
		&i.Title,
		&i.ResumeOfRunID,
		&i.LastActivityAt,
		&i.Health,
		&i.HealthReason,
		&i.HealthSince,
		&i.HealthNotifiedAt,
		&i.TargetRunID,
		&i.MrWebUrl,
		&i.PrdDonePath,
		&i.PrdPatchSettledAt,
		&i.AnthropicSecretID,
		&i.AnthropicSecretLabel,
		&i.AnthropicSelectReason,
		&i.AnthropicHeadroomPct,
		&i.WaitOnLimit,
		&i.LimitResetsAt,
		&i.RetryNotBefore,
		&i.LimitWaitCount,
		&i.RateLimitType,
		&i.OpenQuestionID,
		&i.ReviseCount,
		&i.PlanSource,
		&i.PlannedBaseCommit,
		&i.RequireBaseMatch,
		&i.MilestonesCandidate,
		&i.MilestonesFrozen,
		&i.MilestonesCompleted,
		&i.MilestonesInProgress,
		&i.BudgetMaxIterations,
		&i.BudgetWallSeconds,
		&i.ScheduleID,
		&i.LimitDeadSecretID,
		&i.ReportOnly,
		&i.ReportMd,
		&i.CiConfigPaths,
		&i.Model,
		&i.OverrideSubagentModel,
		&i.FailOrigin,
		&i.Priority,
		&i.SummaryIntent,
		&i.SummaryPlan,
		&i.SummaryDeltas,
		&i.IssueComments,
		&i.BaseBranch,
		&i.OpenMr,
		&i.DispatchedAt,
		&i.ReviewTargetRunID,
		&i.ReviewRequested,
		&i.ThenFixRequested,
		&i.ThenFixOfRunID,
		&i.PreservedPatch,
		&i.RequiredCapabilities,
		&i.StopReason,
		&i.RequiredTools,
		&i.SizeClass,
	)
	return i, err
}

const dispatchTaskRun = `-- name: DispatchTaskRun :one
UPDATE runs
SET dispatched_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND kind = 'task' AND dispatched_at IS NULL
RETURNING id, user_id, repo_id, issue_iid, issue_title, issue_description, status, requeue_count, worker_id, session_id, last_seq, branch, mr_iid, failure_reason, plan_md, iteration_count, claimed_at, started_at, finished_at, created_at, updated_at, origin_column, board_column, move_pending_since, mr_state, auto_approve, autopilot_commented_at, kind, pipeline_id, pipeline_ref, failure_snapshot, fix_verdict, stop_kind, agent_source, agent_exclusions, repo_agents, title, resume_of_run_id, last_activity_at, health, health_reason, health_since, health_notified_at, target_run_id, mr_web_url, prd_done_path, prd_patch_settled_at, anthropic_secret_id, anthropic_secret_label, anthropic_select_reason, anthropic_headroom_pct, wait_on_limit, limit_resets_at, retry_not_before, limit_wait_count, rate_limit_type, open_question_id, revise_count, plan_source, planned_base_commit, require_base_match, milestones_candidate, milestones_frozen, milestones_completed, milestones_in_progress, budget_max_iterations, budget_wall_seconds, schedule_id, limit_dead_secret_id, report_only, report_md, ci_config_paths, model, override_subagent_model, fail_origin, priority, summary_intent, summary_plan, summary_deltas, issue_comments, base_branch, open_mr, dispatched_at, review_target_run_id, review_requested, then_fix_requested, then_fix_of_run_id, preserved_patch, required_capabilities, stop_reason, required_tools, size_class
`

type DispatchTaskRunParams struct {
	RunID  uuid.UUID `json:"run_id"`
	UserID uuid.UUID `json:"user_id"`
}

// Stamp the dispatch gate for a task run (PRD #400 Decision 6): the CLI calls this
// AFTER it has pushed local HEAD to the run's uzi/task/<id> branch, which is the moment
// the run becomes genuinely claimable (ClaimRun gates task claimability on
// dispatched_at). Owner-scoped (@user_id) so a caller holding a foreign run id stamps
// nothing and matches 0 rows — the handler turns that into the same 404 an unknown run
// gets. kind='task' is a guard against dispatching any other kind. dispatched_at IS NULL
// makes the stamp idempotent: a second dispatch matches 0 rows and the caller reads it
// as not-found rather than re-broadcasting a claimable signal.
func (q *Queries) DispatchTaskRun(ctx context.Context, arg DispatchTaskRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, dispatchTaskRun, arg.RunID, arg.UserID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.IssueIid,
		&i.IssueTitle,
		&i.IssueDescription,
		&i.Status,
		&i.RequeueCount,
		&i.WorkerID,
		&i.SessionID,
		&i.LastSeq,
		&i.Branch,
		&i.MrIid,
		&i.FailureReason,
		&i.PlanMd,
		&i.IterationCount,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.MrState,
		&i.AutoApprove,
		&i.AutopilotCommentedAt,
		&i.Kind,
		&i.PipelineID,
		&i.PipelineRef,
		&i.FailureSnapshot,
		&i.FixVerdict,
		&i.StopKind,
		&i.AgentSource,
		&i.AgentExclusions,
		&i.RepoAgents,
		&i.Title,
		&i.ResumeOfRunID,
		&i.LastActivityAt,
		&i.Health,
		&i.HealthReason,
		&i.HealthSince,
		&i.HealthNotifiedAt,
		&i.TargetRunID,
		&i.MrWebUrl,
		&i.PrdDonePath,
		&i.PrdPatchSettledAt,
		&i.AnthropicSecretID,
		&i.AnthropicSecretLabel,
		&i.AnthropicSelectReason,
		&i.AnthropicHeadroomPct,
		&i.WaitOnLimit,
		&i.LimitResetsAt,
		&i.RetryNotBefore,
		&i.LimitWaitCount,
		&i.RateLimitType,
		&i.OpenQuestionID,
		&i.ReviseCount,
		&i.PlanSource,
		&i.PlannedBaseCommit,
		&i.RequireBaseMatch,
		&i.MilestonesCandidate,
		&i.MilestonesFrozen,
		&i.MilestonesCompleted,
		&i.MilestonesInProgress,
		&i.BudgetMaxIterations,
		&i.BudgetWallSeconds,
		&i.ScheduleID,
		&i.LimitDeadSecretID,
		&i.ReportOnly,
		&i.ReportMd,
		&i.CiConfigPaths,
		&i.Model,
		&i.OverrideSubagentModel,
		&i.FailOrigin,
		&i.Priority,
		&i.SummaryIntent,
		&i.SummaryPlan,
		&i.SummaryDeltas,
		&i.IssueComments,
		&i.BaseBranch,
		&i.OpenMr,
		&i.DispatchedAt,
		&i.ReviewTargetRunID,
		&i.ReviewRequested,
		&i.ThenFixRequested,
		&i.ThenFixOfRunID,
		&i.PreservedPatch,
		&i.RequiredCapabilities,
		&i.StopReason,
		&i.RequiredTools,
		&i.SizeClass,
	)
	return i, err
}

const getActiveTaskReviewRunForWorkerTarget = `-- name: GetActiveTaskReviewRunForWorkerTarget :one
SELECT id, user_id, repo_id, issue_iid, issue_title, issue_description, status, requeue_count, worker_id, session_id, last_seq, branch, mr_iid, failure_reason, plan_md, iteration_count, claimed_at, started_at, finished_at, created_at, updated_at, origin_column, board_column, move_pending_since, mr_state, auto_approve, autopilot_commented_at, kind, pipeline_id, pipeline_ref, failure_snapshot, fix_verdict, stop_kind, agent_source, agent_exclusions, repo_agents, title, resume_of_run_id, last_activity_at, health, health_reason, health_since, health_notified_at, target_run_id, mr_web_url, prd_done_path, prd_patch_settled_at, anthropic_secret_id, anthropic_secret_label, anthropic_select_reason, anthropic_headroom_pct, wait_on_limit, limit_resets_at, retry_not_before, limit_wait_count, rate_limit_type, open_question_id, revise_count, plan_source, planned_base_commit, require_base_match, milestones_candidate, milestones_frozen, milestones_completed, milestones_in_progress, budget_max_iterations, budget_wall_seconds, schedule_id, limit_dead_secret_id, report_only, report_md, ci_config_paths, model, override_subagent_model, fail_origin, priority, summary_intent, summary_plan, summary_deltas, issue_comments, base_branch, open_mr, dispatched_at, review_target_run_id, review_requested, then_fix_requested, then_fix_of_run_id, preserved_patch, required_capabilities, stop_reason, required_tools, size_class FROM runs
WHERE worker_id = $1
  AND kind = 'task'
  AND review_target_run_id = $2
  AND status NOT IN ('completed', 'failed', 'cancelled')
LIMIT 1
`

type GetActiveTaskReviewRunForWorkerTargetParams struct {
	WorkerID    pgtype.UUID `json:"worker_id"`
	TargetRunID pgtype.UUID `json:"target_run_id"`
}

// Review-POST authorization (PRD #400 M4a, mirrors GetActiveJudgeRunForWorkerTarget): the
// caller's worker must own a NON-TERMINAL review run whose review_target_run_id is
// @target_run_id. Review-run-scoped, not user-scoped — a worker can only post the review of
// the target its own active review run is reviewing. Returns the review run so the caller
// re-asserts target.user_id == review.user_id independently.
func (q *Queries) GetActiveTaskReviewRunForWorkerTarget(ctx context.Context, arg GetActiveTaskReviewRunForWorkerTargetParams) (Run, error) {
	row := q.db.QueryRow(ctx, getActiveTaskReviewRunForWorkerTarget, arg.WorkerID, arg.TargetRunID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.IssueIid,
		&i.IssueTitle,
		&i.IssueDescription,
		&i.Status,
		&i.RequeueCount,
		&i.WorkerID,
		&i.SessionID,
		&i.LastSeq,
		&i.Branch,
		&i.MrIid,
		&i.FailureReason,
		&i.PlanMd,
		&i.IterationCount,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginColumn,
		&i.BoardColumn,
		&i.MovePendingSince,
		&i.MrState,
		&i.AutoApprove,
		&i.AutopilotCommentedAt,
		&i.Kind,
		&i.PipelineID,
		&i.PipelineRef,
		&i.FailureSnapshot,
		&i.FixVerdict,
		&i.StopKind,
		&i.AgentSource,
		&i.AgentExclusions,
		&i.RepoAgents,
		&i.Title,
		&i.ResumeOfRunID,
		&i.LastActivityAt,
		&i.Health,
		&i.HealthReason,
		&i.HealthSince,
		&i.HealthNotifiedAt,
		&i.TargetRunID,
		&i.MrWebUrl,
		&i.PrdDonePath,
		&i.PrdPatchSettledAt,
		&i.AnthropicSecretID,
		&i.AnthropicSecretLabel,
		&i.AnthropicSelectReason,
		&i.AnthropicHeadroomPct,
		&i.WaitOnLimit,
		&i.LimitResetsAt,
		&i.RetryNotBefore,
		&i.LimitWaitCount,
		&i.RateLimitType,
		&i.OpenQuestionID,
		&i.ReviseCount,
		&i.PlanSource,
		&i.PlannedBaseCommit,
		&i.RequireBaseMatch,
		&i.MilestonesCandidate,
		&i.MilestonesFrozen,
		&i.MilestonesCompleted,
		&i.MilestonesInProgress,
		&i.BudgetMaxIterations,
		&i.BudgetWallSeconds,
		&i.ScheduleID,
		&i.LimitDeadSecretID,
		&i.ReportOnly,
		&i.ReportMd,
		&i.CiConfigPaths,
		&i.Model,
		&i.OverrideSubagentModel,
		&i.FailOrigin,
		&i.Priority,
		&i.SummaryIntent,
		&i.SummaryPlan,
		&i.SummaryDeltas,
		&i.IssueComments,
		&i.BaseBranch,
		&i.OpenMr,
		&i.DispatchedAt,
		&i.ReviewTargetRunID,
		&i.ReviewRequested,
		&i.ThenFixRequested,
		&i.ThenFixOfRunID,
		&i.PreservedPatch,
		&i.RequiredCapabilities,
		&i.StopReason,
		&i.RequiredTools,
		&i.SizeClass,
	)
	return i, err
}

const getTaskReviewForTarget = `-- name: GetTaskReviewForTarget :one
SELECT id, target_run_id, review_run_id, user_id, status, summary_md, created_at, updated_at FROM task_reviews WHERE target_run_id = $1
`

// The review header for a reviewed task, for the CLI/panel read (PRD #400 M4a).
// UNIQUE(target_run_id) makes it at most one row. Owner-or-admin visibility is enforced by
// the caller (GetRunForViewer on the target run) BEFORE this read, not here — a plain
// by-target lookup, exactly like GetRunReviewForTarget.
func (q *Queries) GetTaskReviewForTarget(ctx context.Context, targetRunID uuid.UUID) (TaskReview, error) {
	row := q.db.QueryRow(ctx, getTaskReviewForTarget, targetRunID)
	var i TaskReview
	err := row.Scan(
		&i.ID,
		&i.TargetRunID,
		&i.ReviewRunID,
		&i.UserID,
		&i.Status,
		&i.SummaryMd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskReviewFindings = `-- name: ListTaskReviewFindings :many
SELECT id, review_id, file, symbol, line, severity, summary_md, rationale_md, created_at FROM task_review_findings
WHERE review_id = $1
ORDER BY CASE severity WHEN 'error' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END ASC,
         created_at ASC, id ASC
`

// The structured findings of a review (PRD #400 M4a), most-severe first then oldest-first.
// Served by idx_task_review_findings_review. Every free-text field was scrubbed + capped at
// the review POST, so the panel/CLI renders them as escaped text; this read adds no trust.
func (q *Queries) ListTaskReviewFindings(ctx context.Context, reviewID uuid.UUID) ([]TaskReviewFinding, error) {
	rows, err := q.db.Query(ctx, listTaskReviewFindings, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskReviewFinding{}
	for rows.Next() {
		var i TaskReviewFinding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.File,
			&i.Symbol,
			&i.Line,
			&i.Severity,
			&i.SummaryMd,
			&i.RationaleMd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTaskReviewWithFindings = `-- name: UpsertTaskReviewWithFindings :one
WITH upserted AS (
    INSERT INTO task_reviews (target_run_id, review_run_id, user_id, status, summary_md)
    VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT (target_run_id) DO UPDATE
        SET review_run_id = EXCLUDED.review_run_id,
            status        = EXCLUDED.status,
            summary_md    = EXCLUDED.summary_md,
            updated_at    = now()
    RETURNING id
),
cleared AS (
    DELETE FROM task_review_findings WHERE review_id = (SELECT id FROM upserted)
),
inserted AS (
    INSERT INTO task_review_findings
        (review_id, file, symbol, line, severity, summary_md, rationale_md)
    SELECT (SELECT id FROM upserted), x.file, x.symbol, x.line, x.severity, x.summary_md, x.rationale_md
    FROM jsonb_to_recordset($6::jsonb)
        AS x(file text, symbol text, line int, severity text, summary_md text, rationale_md text)
)
SELECT id FROM upserted
`

type UpsertTaskReviewWithFindingsParams struct {
	TargetRunID uuid.UUID   `json:"target_run_id"`
	ReviewRunID pgtype.UUID `json:"review_run_id"`
	UserID      uuid.UUID   `json:"user_id"`
	Status      string      `json:"status"`
	SummaryMd   string      `json:"summary_md"`
	Findings    []byte      `json:"findings"`
}

// Persist a review's header + its findings for a reviewed task in ONE atomic statement
// (PRD #400 M4a), the same CTE shape the judge's UpsertRunReviewWithRecommendations uses:
// upsert the task_reviews header (UNIQUE(target_run_id) makes a re-review REPLACE rather
// than 23505), clear the old findings, insert the fresh set from a jsonb array. A single
// CTE gives atomicity without a service-level transaction (workersvc holds no pool). The
// finding rows arrive already validated + scrubbed in Go; the table CHECK on severity is
// the backstop.
func (q *Queries) UpsertTaskReviewWithFindings(ctx context.Context, arg UpsertTaskReviewWithFindingsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTaskReviewWithFindings,
		arg.TargetRunID,
		arg.ReviewRunID,
		arg.UserID,
		arg.Status,
		arg.SummaryMd,
		arg.Findings,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
