package preset

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"k8s.io/apimachinery/pkg/api/resource"
)

// The size DISPLAY golden (PRD #58 M6): what the web renders in the provision
// picker, so a user choosing a size is not choosing blind.
//
// WHY THIS FILE LIVES IN THE CONTROLLER, and not in api/internal/hostedsvc/testdata
// beside the names golden — which is where the PRD's design put it (the PRD is
// corrected in the same commit as this file). The quantities must reach the UI
// WITHOUT the api ever learning them: Decision 7 pins that the api ships a preset
// NAME and nothing a pod spec is made of, and size_contract_test.go next door says
// so in its own words ("the api may not know cpu/memory, because it may not be the
// authority on a pod spec"). Putting the numbers in the api's testdata forces one of
// three things, and all three are worse than a second file:
//
//   - the api module AUTHORS them, so a second copy of this table lives in api/ and
//     the api becomes an authority on a pod spec — the exact thing Decision 7 forbids;
//   - THIS module writes into the api's tree — a cross-module write, and a regenerate
//     from either side silently clobbers the other's fields;
//   - nobody generates it and hosted_sizes.json becomes hand-maintained, which deletes
//     M2's producer gate (workersize.Names IS that golden) to buy nothing.
//
// Two files, each generated by the module that is actually the authority, keeps every
// existing gate and adds no new authority. The names chain is untouched:
//
//	workersize.Names -> hosted_sizes.json -> this table (asserted BOTH ways by
//	preset_contract_test.go) -> this golden -> the web constant (asserted by
//	web/src/lib/workerSizes.test.ts)
//
// Every link is gated, so a number cannot drift silently from the pod spec it
// describes — which is the whole point, since a size label that lies is worse than no
// label at all.
//
// Decision 7 is not bent: nothing on the wire carries quantities, workersize stays
// names-only, and this module remains the sole authority that renders. The golden is
// a BUILD-TIME artifact — the drift gate is a test, never a runtime read.
//
// Regenerate with `UPDATE_GOLDEN=1 go test ./internal/preset/...`.
const sizeDisplayFixture = "testdata/hosted_size_specs.json"

// sizeSpecGolden is the fixture's shape.
//
// RAW k8s quantity strings, never pre-rendered prose ("2 CPU, 4Gi RAM"): prose is
// where a lie hides, and it would make the two consumers assert against a sentence
// instead of a value. The web does its own rendering; this file carries facts.
//
// REQUEST AND LIMIT BOTH, because the presets are Burstable and Decision 7 names
// "cpu, memory" as if each were singular. The web shows the limits (a ceiling is what
// a user is choosing between); the requests are here so this golden describes the pod
// spec completely rather than the half that happens to be displayed today.
type sizeSpecGolden struct {
	Sizes []sizeSpecEntry `json:"sizes"`
	// Nix is FLAT — outside the per-size list, because it does not vary by size or by
	// template (measured byte-identical across base and jvm). Decision 7's original
	// display shape carried a per-size `nix` field, which would have shipped a table
	// with one repeated value; its own later correction removes it, and
	// TestNixSizeIsFlatAcrossEveryPresetAndTemplate pins the property.
	Nix string `json:"nix"`
}

type sizeSpecEntry struct {
	Name          string `json:"name"`
	CPURequest    string `json:"cpu_request"`
	CPULimit      string `json:"cpu_limit"`
	MemoryRequest string `json:"memory_request"`
	MemoryLimit   string `json:"memory_limit"`
	Data          string `json:"data"`
}

// buildSizeDisplayGolden renders the table in the API'S display order.
//
// The order comes from the names golden rather than from SizeNames(), and that is
// load-bearing twice over: SizeNames() returns MAP KEYS, so it is randomly ordered
// and would produce a different file on every run; and "smallest first" is the api
// registry's own decision (workersize.Names), so taking it from there means the
// picker cannot silently reorder itself when this table is edited.
//
// A name in the golden with no entry here would render a zero Spec — but that cannot
// reach this function unnoticed: TestPresetTableCoversEveryAPISize fails first, by
// name, with the stranded-worker explanation.
func buildSizeDisplayGolden(t *testing.T) sizeSpecGolden {
	t.Helper()
	out := sizeSpecGolden{Nix: nixSize.String()}
	for _, name := range readGolden(t, "hosted_sizes.json", "sizes") {
		s, ok := sizes[name]
		if !ok {
			t.Fatalf("the api ships size %q with no entry in this preset table; "+
				"TestPresetTableCoversEveryAPISize explains the consequence", name)
		}
		out.Sizes = append(out.Sizes, sizeSpecEntry{
			Name:          name,
			CPURequest:    s.CPURequest.String(),
			CPULimit:      s.CPULimit.String(),
			MemoryRequest: s.MemoryRequest.String(),
			MemoryLimit:   s.MemoryLimit.String(),
			Data:          s.DataSize.String(),
		})
	}
	return out
}

// This table IS the golden. Edit a preset quantity and this goes red until the golden
// is regenerated — and regenerating turns web/src/lib/workerSizes.test.ts red until
// the displayed constant is updated too. That chain is the feature: it makes a number
// on screen impossible to leave contradicting the pod that gets rendered.
func TestHostedSizeSpecsGolden(t *testing.T) {
	got, err := json.MarshalIndent(buildSizeDisplayGolden(t), "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got = append(got, '\n')

	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.MkdirAll(filepath.Dir(sizeDisplayFixture), 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		if err := os.WriteFile(sizeDisplayFixture, got, 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Log("golden file updated")
		return
	}

	want, err := os.ReadFile(sizeDisplayFixture)
	if err != nil {
		t.Fatalf("read golden (regenerate with UPDATE_GOLDEN=1 go test ./internal/preset/...): %v", err)
	}
	if string(got) != string(want) {
		t.Fatalf("the preset table drifted from the size DISPLAY golden.\n"+
			"This golden is what the provision picker shows a user. If the preset change is deliberate, "+
			"regenerate it (UPDATE_GOLDEN=1 go test ./internal/preset/...) and update the web constant "+
			"(web/src/lib/workerSizes.ts), whose own test reads this file. Leaving them apart ships a size "+
			"label that lies about the pod the user actually gets.\n got:\n%s\nwant:\n%s", got, want)
	}
}

// Every string in the golden must parse as a k8s quantity, and match the table it
// came from. This is what "assert structurally" means for this consumer: the file is
// facts, so a typo is caught as a value, never as a diff in a sentence.
//
// It is not redundant with the golden comparison above: that one proves the file
// matches the table, this one proves the SHAPE is a quantity the renderer could
// actually use — the property the web then relies on when it prints the string
// verbatim.
func TestSizeDisplayGoldenCarriesParseableQuantities(t *testing.T) {
	raw, err := os.ReadFile(sizeDisplayFixture)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc sizeSpecGolden
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Sizes) == 0 {
		// A golden that parsed to nothing makes every loop below vacuously pass — the
		// "test that cannot fail" this PRD's Decision Log keeps catching.
		t.Fatal("the display golden carries no sizes")
	}
	if _, err := resource.ParseQuantity(doc.Nix); err != nil {
		t.Errorf("nix %q is not a k8s quantity: %v", doc.Nix, err)
	}

	for _, e := range doc.Sizes {
		s, ok := sizes[e.Name]
		if !ok {
			t.Errorf("the display golden carries size %q, which this preset table does not", e.Name)
			continue
		}
		for _, f := range []struct {
			field, got string
			want       resource.Quantity
		}{
			{"cpu_request", e.CPURequest, s.CPURequest},
			{"cpu_limit", e.CPULimit, s.CPULimit},
			{"memory_request", e.MemoryRequest, s.MemoryRequest},
			{"memory_limit", e.MemoryLimit, s.MemoryLimit},
			{"data", e.Data, s.DataSize},
		} {
			q, err := resource.ParseQuantity(f.got)
			if err != nil {
				t.Errorf("size %q %s = %q, not a k8s quantity: %v", e.Name, f.field, f.got, err)
				continue
			}
			if q.Cmp(f.want) != 0 {
				t.Errorf("size %q %s = %q, but the preset table says %s", e.Name, f.field, f.got, f.want.String())
			}
		}
	}
}
