#!/usr/bin/env bash
# Generate / drift-check the e2e/README.md phase-registry table (PRD #966 M2).
#
# usage:
#   scripts/check-e2e-registry-doc.sh            # CHECK: regenerate, diff, fail on drift
#   scripts/check-e2e-registry-doc.sh --write    # WRITE:  splice the fresh table into README
#
# 🔴 WHY THIS EXISTS. e2e/README.md's registry table (columns NN|slug|lane|
# critical|title) is GENERATED from the phase-file headers in e2e/phases/, not
# hand-maintained -- a new phase file must appear in the README or the doc is a
# lie. This is the `docs:sync` drift-check shape: `--write` regenerates the table
# and splices it into README between the literal markers; the default check mode
# regenerates to a temp and `diff`s it against the committed README, non-zero on
# drift. `task e2e:registry-doc` is the writer; `task check:e2e-registry-doc`
# (this script, no args) is the gate.
#
# 🔴 CHEAP HEADER READ ONLY -- NEVER THE FULL SUITE. This reads only the phase-file
# header comments (the same fields `./e2e/run-e2e.sh --list` prints, which itself
# needs no docker). It never stands up the stack. docs/dev-conventions.md:79
# ("./e2e/run-e2e.sh and ./scripts/smoke.sh are not gate recipes") stays true: the
# gate touches the harness's HEADERS, not a `run-e2e.sh` invocation.
#
# EXIT CODES:
#     2 = the instrument is broken (README or markers missing, or no phase files)
#     1 = drift: the committed table differs from the freshly generated one
#     0 = clean (check mode), or written (--write mode)
# `task`'s own rc is 201 for all of them.
set -euo pipefail

MODE="check"
case "${1:-}" in
  ""|check) MODE="check" ;;
  --write)  MODE="write" ;;
  *) echo "usage: scripts/check-e2e-registry-doc.sh [--write]" >&2; exit 2 ;;
esac

ROOT="$(git rev-parse --show-toplevel)" || {
  echo "check-e2e-registry-doc: not inside a git work tree" >&2; exit 2
}
cd "$ROOT" || { echo "check-e2e-registry-doc: cannot cd to repo root: $ROOT" >&2; exit 2; }

README="e2e/README.md"
PHASES_DIR="e2e/phases"
BEGIN_MARKER='<!-- registry:begin (generated by `task e2e:registry-doc`; do not edit by hand) -->'
END_MARKER='<!-- registry:end -->'

[ -f "$README" ] || { echo "check-e2e-registry-doc: $README not found" >&2; exit 2; }
[ -d "$PHASES_DIR" ] || { echo "check-e2e-registry-doc: $PHASES_DIR not found" >&2; exit 2; }

# The markers must both be present, or the doc has no place for the generated
# table -- an instrument failure, not drift (a silent no-op would let the table
# rot). grep -F for the literal so a marker-text edit is caught here, not later.
if ! grep -qF -- "registry:begin" "$README" || ! grep -qF -- "registry:end" "$README"; then
  echo "check-e2e-registry-doc: ================================================================" >&2
  echo "check-e2e-registry-doc: INSTRUMENT BROKEN -- the registry:begin / registry:end markers" >&2
  echo "check-e2e-registry-doc: are missing from $README. The generated table has nowhere to go." >&2
  echo "check-e2e-registry-doc: Restore both marker lines (see the script header)." >&2
  echo "check-e2e-registry-doc: ================================================================" >&2
  exit 2
fi

_hdr() { sed -n "s/^# $1:[[:space:]]*//p" "$2" | head -1; }

# gen_table -- emit the markdown table (header + separator + one row per phase),
# rows ordered by the NN filename prefix (the glob is already lexical). Titles are
# `|`-escaped so a pipe in a title can never break the column count.
gen_table() {
  local f base nn slug lane critical title any=0
  printf '| NN | slug | lane | critical | title |\n'
  printf '|---|---|---|---|---|\n'
  for f in "$PHASES_DIR"/[0-9][0-9]-*.sh; do
    [ -e "$f" ] || continue
    any=1
    base="$(basename "$f" .sh)"
    nn="${base%%-*}"
    slug="${base#[0-9][0-9]-}"
    lane="$(_hdr lane "$f")"
    critical="$(_hdr critical "$f")"
    title="$(_hdr title "$f")"
    title="${title//|/\\|}"
    printf '| %s | %s | %s | %s | %s |\n' "$nn" "$slug" "$lane" "$critical" "$title"
  done
  [ "$any" = 1 ] || return 1
}

TABLE="$(mktemp)"
NEWREADME="$(mktemp)"
trap 'rm -f "$TABLE" "$NEWREADME"' EXIT

if ! gen_table > "$TABLE"; then
  echo "check-e2e-registry-doc: INSTRUMENT BROKEN -- no phase files matched $PHASES_DIR/NN-*.sh." >&2
  echo "  Generating an empty table would be vacuous; treating as an instrument failure." >&2
  exit 2
fi

# Splice: everything up to and including the begin marker, a blank line, the fresh
# table, a blank line, then the end marker and everything after it. A blank line on
# each side of the table is required for GitHub to render it after an HTML comment.
awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v tablefile="$TABLE" '
  BEGIN { state = 0 }
  index($0, "registry:begin") { print begin; print ""; while ((getline l < tablefile) > 0) print l; print ""; state = 1; next }
  index($0, "registry:end")   { print end; state = 0; next }
  state == 1 { next }          # drop the old table body between the markers
  { print }
' "$README" > "$NEWREADME"

if [ "$MODE" = write ]; then
  cp "$NEWREADME" "$README"
  echo "check-e2e-registry-doc: wrote the phase-registry table into $README ($(grep -c '^| [0-9]' "$README") phases)."
  exit 0
fi

# CHECK: diff the committed README against the freshly spliced one.
if diff -u "$README" "$NEWREADME" > /dev/null 2>&1; then
  echo "check-e2e-registry-doc: clean -- $README's registry table matches the phase headers ($(grep -c '^| [0-9]' "$README") phases)."
  exit 0
fi

echo "check-e2e-registry-doc: DRIFT -- $README's registry table is stale vs the phase headers:" >&2
diff -u "$README" "$NEWREADME" >&2 || true
echo "" >&2
echo "  Regenerate with:  task e2e:registry-doc   (or scripts/check-e2e-registry-doc.sh --write)" >&2
echo "  then commit $README. The table is generated from e2e/phases/NN-*.sh headers." >&2
exit 1
